### ISSUE TITLE
gem install fpm - broken?

### ISSUE THREAD

**Issue by hartsantler** [jordansissel/fpm#1000]
running `gem install fpm` i get this error:
```bash
ERROR:  Could not find a valid gem 'fpm' (>= 0) in any repository
ERROR:  Possible alternatives: fpm
```

**Comment by hartsantler** [comment]
update:
i ran `gem install fpm` again and this time it worked, must have been my bad internet connection, although i would have expected gem to report there was a timeout, and not that it could not find a valid gem fpm.

why not release fpm as a regular DEB or RPM package, so users can simply do:
```bash
apt-get install fpm
```

**Comment by epylar** [comment]
There are a number of possible reasons for this.  Next time you see it, could you try:

```gem install fpm -V```

and attach the output?
