### ISSUE TITLE
Unable to sign an RPM

### ISSUE THREAD

**Issue by dtolj** [jordansissel/fpm#1005]
After adding --rpm-sign i get an error

fpm -s dir -t rpm --rpm-sign -n test /myfiles

``
Process failed: rpmbuild failed (exit code 1). Full command was:["rpmbuild", "-bb", "--define", "buildroot /tmp/package-rpm-build20150911-26067-4uy83p/BUILD", "--define", "_topdir /tmp/package-rpm-build20150911-26067-4uy83p", "--define", "_sourcedir /tmp/package-rpm-build20150911-26067-4uy83p", "--define", "_rpmdir /tmp/package-rpm-build20150911-26067-4uy83p/RPMS", "--define", "_tmppath /tmp", "--sign", "/tmp/package-rpm-build20150911-26067-4uy83p/SPECS/test.spec"] {:level=>:error}
``

**Comment by satoshi** [comment]
Where is your --rpm-rpmbuild-define key with _gpg_name?  And is your gpg key imported?

**Comment by satoshi** [comment]
Be sure to read the fine manual before filing bug(s).  I've signed RPMs successfully via FPM.

**Comment by el-dude** [comment]
@satoshi can you link me to the fine manual that explain these options?

**Comment by satoshi** [comment]
@el-dude you can find docs like https://gist.github.com/fernandoaleman/1376720/aaff3a7a7ede636b6913f17d97e6fe39b5a79dc0.  This isn't really a fpm issue, as fpm simply passes options to rpmbuild underneath.

**Comment by el-dude** [comment]
@satoshi thanks, but what I was looking for was clear documentation on the options that FPM supports to be passed to rpmbuild. For example you suggested that `-rpm-rpmbuild-define` be used. Is there a doc that explains all the options and what they're for? So it would be more clear to pass `-rpm-rpmbuild-define --rpm-sign` when you would like to sign an rpm your trying to build with FPM.

**Comment by satoshi** [comment]
@el-dude It's been a while, but I think I figured it out myself by reading rpmbuild docs.  It is debatable how far FPM should go documenting rpmbuild parameters.  Your argument is certainly valid, as lack of docs on FPM side is a bit unfriendly.

**Comment by nicobrevin** [comment]
@satoshi @el-dude If anyone has a spare half an hour to write something up, there is a bit of an effort going in to improving docs - https://fpm.readthedocs.io/en/latest

**Comment by murillopaula** [comment]
@satoshi my gpg key is imported and I'm defining `--rpm-rpmbuild-define ~/.rpmmacros` but I get the same errors. Any idea why?

**Comment by murillopaula** [comment]
@satoshi OK, I realized that I had to use the format `--rpm-rpmbuild-define KEY VALUE` insteado of defining a file. But the command still fails because it looks like GPG/RPM asks for the GPG private key password. How do I pass it to `fpm`?

**Comment by satoshi** [comment]
I don't remember exactly (it's been 2.5 years).  Iirc I had ssh-agent kind of thing to basically cache the key so I didn't need to type in my password when running fpm.  I might be misremembering though.

**Comment by murillopaula** [comment]
@satoshi I'm not using ssh-agent. Any other way to pass the passphrase of my private gpg key to fpm?

**Comment by satoshi** [comment]
It's not ssh-agent, it's gpg-agent which works kind of like ssh-agent. https://linux.die.net/man/1/gpg-agent

**Comment by murillopaula** [comment]
Ok, already solved it. I was getting the error because I did not have the package `rpmsign` installed. After installing it, the signing worked as expected. Thanks for your attention and help anyways @satoshi
