### ISSUE TITLE
forwarding rpm build flags -- replacefiles in particular

### ISSUE THREAD

**Issue by ajoslin103** [jordansissel/fpm#1007]
I'm trying to build an rpm that overwrites a file that is installed by another package (one of my dependencies) and I get

Transaction Check Error:
  file /etc/exim/exim.conf from install of EPCRTGMail-Vers_1.0_25_r1a78f0b-1.noarch conflicts with file from package exim-4.72-7.el6.x86_64

If I could add the rpm flag --replacefiles to the installation somehow...

I'm using the -s dirs and ./exim/=/etc/exim/ to deliver my modified copy of the exim.conf file

**Comment by ajoslin103** [comment]
ok, so after a bunch of reading I guess I shouldn't be asking for this...

but what would _you_ do if your install wanted to add custom sections to a conf file ?

and to be symmetrical, how would you remove those sections if your package was uninstalled ?

**Comment by ajoslin103** [comment]
I'm using diff & patch -- best I could find

**Comment by hatt** [comment]
Packages generally should't share config files. If it was really required, I'd have up/down patches as post install/remove scripts.

**Comment by ajoslin103** [comment]
I did end up using patches, but they were forward/reverse -- what's up/down ?

**Comment by hatt** [comment]
Different way of saying the same thing :)

If multiple packages need to share a config, usually a core package or sometimes a config package is used as a dependency, with actual files in their relevant packages. No two packages should ever own the same file.
