### ISSUE TITLE
Creating custom deb packages

### ISSUE THREAD

**Issue by waghanza** [jordansissel/fpm#1025]
Hi,

I am using `fpm` to create `deb`, in order to **deploy** them.
I have a `folder` with specific **debian** files with

``` sh
changelog
compat
control
...
```

How can I precise a **path** to `fpm` to use those files (and not default ones) ?
Regards,

**Comment by hamilyon** [comment]
To crate deb package from proper `changelog`, `compat`, `rules` etc. files use `dpkg-buildpackage`. If they are in different directory, create symlink for them to be in `./debian/`

Or there is some reason you use fpm?

**Comment by waghanza** [comment]
Yes, I use `fpm` since it's very simple :+1:  
I could use **dh_make**, but I want to create an application that use `fpm` to build binary packages
* rpm
* deb
There is no way to give a specific format options with `fpm` ?

**Comment by JimPanic** [comment]
You can either use:
```
    --deb-meta-file FILEPATH      (deb only) Add FILEPATH to DEBIAN directory
```
…to define the directory to those files (I haven't tested that yet)

Or specify the files independently:
```
    --deb-changelog FILEPATH      (deb only) Add FILEPATH as debian changelog
    --deb-custom-control FILEPATH (deb only) Custom version of the Debian control file.
    --deb-config SCRIPTPATH       (deb only) Add SCRIPTPATH as debconf config file.
    --deb-templates FILEPATH      (deb only) Add FILEPATH as debconf templates file.
```

I personally have used `--deb-custom-control` so far, and it works.
