### ISSUE TITLE
Suffix

### ISSUE THREAD

**Issue by ubellavance** [jordansissel/fpm#1052]
Hi,

I tried using this option but it doesn't seem to change anything.

-S, --package-name-suffix PACKAGE_NAME_SUFFIX a name suffix to append to package and dependencies.

Is it a known issue?  What is the targeted purpose for this option? What does it change?  If it adds a suffix to dependencies would it mean that a php dependency would become phpsuffix?

Thanks,

**Comment by hatt** [comment]
This functionality is from around 2012 and doesn't seem to have followed through. Prefix support was added individually to specific packagers while suffix seems to have been dropped completely. I'm not sure if a global prefix or suffix is a good idea, but for suffix to work we'd need to either add it to each packager or somehow force it in the parent package class. Probably something to discuss with @jordansissel and the community at large I suppose. Seems easy enough to implement if we have a consensus on how it should work.
