### ISSUE TITLE
Support for APK

### ISSUE THREAD

**Issue by sporkmonger** [jordansissel/fpm#1066]
Now that Alpine is becoming default distro for Docker containers, does it make sense to introduce support for APK? Alpine is particularly rough in some cases just because of musl, so support for it might be more challenging than other package management tools.

**Comment by jordansissel** [comment]
+1 :)

**Comment by jordansissel** [comment]
https://github.com/jordansissel/fpm/pull/1054 is an open PR to add APK support to fpm - I haven't tested it, and I confess I have no experience with Alpine (other than it won't boot for me on hyper-v! haha, computers! *flips table*) 

If I get some time this week, I will start fiddling with 1054, but having wonderful humans like yourself help test #1054 would be awesome. Let's continue the discussion on that PR - thoughts?

**Comment by aacebedo** [comment]
APK support would be so useful !

**Comment by Knetic** [comment]
Jordan merged #1054 not long ago, so for those looking for APK support, it's in as of a2540649fcb9e433dfb7f1d623152e407d92f4a6

**Comment by jordansissel** [comment]
#1054 merged
