### ISSUE TITLE
trying to package fpm

### ISSUE THREAD

**Issue by ajoslin103** [jordansissel/fpm#1074]
Hello,

I am trying to build an rpm of my freshly installed fpm (on a freshly updated CentOS7) this way as our developers create their software (on their CentOS 7 machines) then they can easily rpm their outputs,

This is my fpm command ( /usr/local/sbin/fpm  symlinks to /usr/local/bin/fpm )

fpm --version 1.0.6 --depends ruby --depends rubygems --depends rpm-build -t rpm -s dir -n fpm /usr/local/share/gems/*/fpm* /usr/local/bin/fpm /usr/local/sbin/fpm 

But when I run fpm I get this error: (and not being a ruby person I can't figure out what else I have to add as a dependency just to run fpm, not to build it)

# fpm
/usr/share/rubygems/rubygems/dependency.rb:296:in `to_specs': Could not find 'childprocess' (>= 0) among 10 total gem(s) (Gem::LoadError)
	from /usr/share/rubygems/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1198:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:1198:in `activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1180:in `activate'
	from /usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/sbin/fpm:22:in `<main>'

**Comment by jordansissel** [comment]
YOu're missing the childprocess gem library (and probably others)

**Comment by ajoslin103** [comment]
added all gems, still didn't work -- abandoning this as a bad idea...
