### ISSUE TITLE
Provide SPEC file as a parameter

### ISSUE THREAD

**Issue by semion-arest** [jordansissel/fpm#1092]
I've been using fpm and it truly eased the packaging flow a lot, however recently I run into a problem in which I have to provide multiple metadata fields to the rpm SPEC file. E.g. description, vendor, summary etc. 

Since there's no option to provide the SPEC as it can be done for deb packages using --deb-custom-control, I either have to include the values hardcoded into my script or read them from an external file into the variables, which I give to fpm.

I read that fpm "moving towards making SPEC files unneeded" (https://github.com/jordansissel/fpm/issues/866), but the last date of this announcement was time ago.

Is there any other solution besides the workarounds I mentioned? Thanks.

**Comment by hatt** [comment]
Really all you can do is one of the following:
* edit the SPEC we template (`-e` option)
* pass the flags to set all your metadata in a build script
* use an fpmrc file which has the options set and fpm will use it like you passed the flags

The description, summary, vendor, etc can all be set by flags, is it that you don't want to do that or just want to automate them for a given package set without using a bash wrapper or something?

**Comment by semion-arest** [comment]
>edit the SPEC we template (-e option)

No, since the build process is automated.

>pass the flags to set all your metadata in a build script

I am not sure I understood correctly: you mean a build script which acts as a wrapper, gets the whole bunch of parameters (in which there are multiline parameters such as "description") and then passes them to the fpm?
If yes, then this is kind of what I am doing now:
Part of the parameters (such as description and summary) are hardcoded now in the packaging script which calls the fpm, and part of them I get from the build script whcih performs many build stages and packaging is one of them. But in the end I have to feed the whole set of parameters to the fpm, which doesn't look as a convenient way.

Also to pass the multiline description parameter I had to use something like:
#!/bin/bash
...
PRODUCT_DESCRIPTION="line1\nline2\n ..."
fpm ... --description "`printf "$PRODUCT_DESCRIPTION"`"
...
which doesn't look like a clean way.

The whole thing I want, is simply having a SPEC file with all the necessary fields, that fpm will read this file and make the rpm package according to the SPEC, in the same way it can be done for a deb control file, for which the --deb-custom-control exists. That's it. 
Instead of this, I have to give the list of the fields to the fpm in an awkward ways.

>use an fpmrc file which has the options set and fpm will use it like you passed the flags

I didn't find a documentation for this, could you please elaborate? Where this file should be located? What do I write into it? Will it allow to create multiline parameter values?

**Comment by hatt** [comment]
The fpmrc file isn't really documented anywhere but it's basically a file called `.fpmrc` in the directory you call FPM from that has one CLI flag per line, same syntax as Ack basically. I'm not sure if it works with multiline but there's one way to find out. Your values would still be hardcoded but at least you wouldn't need a wrapper then.

Regarding using a custom SPEC file in the same way a custom Debian control file is used, they aren't really analogues. A control file is packaged into the `.deb` file to provide the package metadata. A SPEC file however is used by `rpmbuild` to build the RPM and isn't included in the resulting package (afaik). I suppose we could add a facility to provide the spec file but then all the auto versioning and other things we do for different sources would break so only dir or tar packaging would work.

**Comment by semion-arest** [comment]
Ok, thanks for the help.

**Comment by jordansissel** [comment]
As a possible compromise, if it's desirable, I could see fpm having an "--rpm-metadata-from-spec" which would read only the tags (`Name`, `Version`, `Release`, `Arch` etc from the specfile and use those values for the output package. Thoughts?

**Comment by jordansissel** [comment]
I do agree that an .fpmrc is probably the best place to put these kinds of things, though. I agree it's not well documented, and I'll see about fixing that soon. <3
