### ISSUE TITLE
Add pleaserun support

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1112]
Example invocation:

```
fpm -s pleaserun -n httpd-service -t deb /usr/bin/httpd
```

The above would use pleaserun to create any necessary init/systemd/upstart/etc files and after-install steps and produce a .deb package called 'httpd-service' that, upon install, would select the "best" available service runtime (systemd, etc) and install the service.

Ideally this would produce a deb (as example above) that could install on any deb-using platform and would select upstart, systemd, sysvinit, or whatever, upon install, for whatever is right for the target machine.

**Comment by jordansissel** [comment]
This gets a bit tricky because the args handling in the fpm cli is a bit strict, so today it isn't possible to implement a `pleaserun` source package type that would support multiple arguments to the service to run (like `fpm -s pleaserun -t deb /usr/bin/httpd -D` would fail due to fpm's cli validation)

**Comment by untergeek** [comment]
👍

**Comment by jordansissel** [comment]
Progress underway! Weeeeee.

**Comment by jordansissel** [comment]
Current status:

Tested on a stock CentOS 6.7 with an rpm built on Fedora 23.
```
% sudo initctl status example
initctl: Unknown job: example
% sudo rpm -i example-service-1.0-1.x86_64.rpm
Platform upstart (0.6.5) detected. Installing service.
To start this service, use: initctl start example
% sudo initctl status example
example stop/waiting
% sudo initctl start example
example start/running, process 1849
% sudo initctl status example
example start/running, process 1849
% sudo initctl stop example
example stop/waiting
% sudo rpm -e example-service
Running cleanup to remove service for package example-service
% sudo initctl status example
initctl: Unknown job: example
```

**Comment by jordansissel** [comment]
Lots of shell scripts in this patch (because some of the implementation is executed during package installation, so we can really rely on /bin/sh). I need to think about how to test this.

**Comment by liger1978** [comment]
I'm not sure I understand this.  Would this create a package that just creates the service definition files (but does not contain any other files?  For me a more useful option would be for `fpm` to make use of `pleaserun` to augment a package with an appropriate service definition file.

Example:

Lets say we have a rubygem that runs a WEBrick web server (r10k_gitlab_webook_server is a good example).  When we convert the gem to an RPM for use on (e.g.) CentOS 7 it would be very useful if one could supply arguments to fpm that allowed the resulting RPM to include a systemd unit file that allowed one to start and stop the WEBrick web server.

**Comment by jordansissel** [comment]
@liger1978 the fpm cli only does one transformation (source to target package). However, the FPM ruby API lets you do multiple, so you can create one rpm with both the service definitions and the artifacts for your application.

Allowing fpm to do multiple transformations (say, pleaserun + dir to rpm) would be lovely, but as a new feature, it is out of scope for this PR.

**Comment by jordansissel** [comment]
#1119 implements this.
