### ISSUE TITLE
--workdir option not taken into account

### ISSUE THREAD

**Issue by ppoilbarbe** [jordansissel/fpm#1124]
We creates big data packages (~3-6Gb) and we tried tu use `--workspace` option to put working directory elsewhere since `/` is filled up with our data.
But this don't seem to work: it always uses `/tmp`.
Interrupting FPM with _^Z_ and looking in the specified directory will show an empty one while `/tmp/package-*` are created. The option is read from command line since the message `Setting workdir {:workdir=>"/home/pp//tmp", :level=>:info}` is printed.

**Comment by jordansissel** [comment]
Ouch. This is definitely a bug.
