### ISSUE TITLE
Log output in JSON format

### ISSUE THREAD

**Issue by bastimeyer** [jordansissel/fpm#1130]
Just a little feature request regarding the log output:

It would be much easier for third-party applications/tools to parse the output messages, if the stdout/stderr log were in the JSON format. Right now it's kind of useless for any Node.js related tool, since (afaik) there no parsers for the currently used format. By using JSON, the log can be read/parsed in every application.

Thanks!

**Comment by JonasGroeger** [comment]
As a workaround, you can parse this with

    sed 's_.*"\(.*\)".*_\1_'

This will do:

    $ echo 'Created package {:path=>"package_1.0.0_all.deb"}' | sed 's/.*"\(.*\)".*/\1/'
    package_1.0.0_all.deb

The pattern is looking for everything between `"` (quotes).

**Comment by josephholsten** [comment]
I'd be interested in seeing this, did you happen to put together an implementation?
