### ISSUE TITLE
Dependent gem json's update breaks fpm gem install on ruby < 2.0

### ISSUE THREAD

**Issue by sarguru** [jordansissel/fpm#1147]
Json's new release needs ruby > 2.0, so it breaks places in which older version of ruby is used. Is it possible to do something like

 ```spec.add_dependency("json", ">= 1.7.7", "< 2")``` ?

The current workaround Im doing is to 

```gem install json  -v 1.8.3``` before
```gem install fpm```

**Comment by jordansissel** [comment]
https://github.com/jordansissel/fpm/pull/1146 just merged to fix this.

**Comment by jordansissel** [comment]
fpm 1.6.2 published with this fix.

**Comment by jordansissel** [comment]
Or not... `gem push` is stuck on my workstation. I'll publish as soon as I can :\

**Comment by jordansissel** [comment]
```% gem push fpm-1.6.2.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: fpm (1.6.2)

```

wooo

**Comment by sarguru** [comment]
<3
