### ISSUE TITLE
[Query] Can fpm support package formats that bundle dependencies? (AppImage, Flatpak, Guix, gx, Snappy)

### ISSUE THREAD

**Issue by kwill** [jordansissel/fpm#1149]
Some new(ish) package formats bundle (most) dependencies in the package itself. (Their common goals seem to include multi-distro support and "solving the dependency problem".) Is this approach supportable?

These formats include:
- AppImage http://appimage.org
- Flatpak http://flatpak.org
- Guix https://www.gnu.org/software/guix/manual/html_node/Packaging-Guidelines.html [1]
- gx https://github.com/whyrusleeping/gx [2]
- Snappy https://snapcraft.io

If this is possible, support to/from each format presumably warrants separate tickets? Which would be the best resource to point the maintainers of AppImage et al to, if they wanted to contribute to fpm themselves?

[1] [2] Guix and gx have other implementation details that would require individual investigation.

**Comment by kwill** [comment]
AppImage support is already ticketed: https://github.com/jordansissel/fpm/issues/1133

**Comment by kwill** [comment]
See also https://github.com/mikix/deb2snap

**Comment by hatt** [comment]
I've been investigating Snap and AppImage over the past few days for FPM. As far as dependencies, it would depend on how easily the source gives up it's dependencies. Ruby gems would be a relatively simple one while Perl modules not so much. The main thing I see is that all these formats are tailored to Linux and require compilation steps, which is a little bit annoying for cross-platform compatibility. I don't think anyone expects to build for Linux on OSX though so that's probably not a big deal.

**Comment by kwill** [comment]
Snap / Snappy support is ticketed at https://github.com/jordansissel/fpm/issues/1181

**Comment by elopio** [comment]
I'd be happy to help on the snapcraft side. My ruby is not strong though.
@hatt from your experiments, did you see anything that could make it easier for you to support snaps?

**Comment by hatt** [comment]
@elopio actually snap is the easiest of the formats I looked at for this - the biggest issues are as I detailed above figuring out dependencies for building, and then a nice way to get extra metadata (ports, interfaces, plugins, etc) into the snap definition.

There is a SquashFS gem for Ruby now which makes generating the packages quite easy so it's pretty much just the metadata for the package that is finicky. The one thing I'm not sure on is given FPM would build the package into a staging directory and just dump it in a snap archive, I can't think of a good way to deal with the parts definition for 3rd party libraries. It's not really important unless someone wants to build a snap from source again anyway though. There is also some path stuff to deal with, like [this](https://bugs.launchpad.net/snapcraft/+bug/1612818).

**Comment by elopio** [comment]
@hatt I don't know much about fpm, but I initially imagined that it would generate a snapcraft.yaml, and then call snapcraft to generate the package. Why do you want to generate the package with ruby inside FPM?

**Comment by hatt** [comment]
@elopio other than a few specific package formats, FPM generates all its packages natively and without the build tools of whatever the target is. If it was just a wrapper for snapcraft, I would still need snapcraft running on my system and make sure my data was compatible with the rest of the toolkit. The goal is to get a deployable package at the end, not a full featured all the things blueprint.

**Comment by elopio** [comment]
I understand @hatt, thanks.

**Comment by kwill** [comment]
It looks like there is nothing in principle stopping bundled formats being supported. Closing query as answered.
