### ISSUE TITLE
Python to Deb - get_metadata.py:  'list' object has no attribute 'decode'

### ISSUE THREAD

**Issue by bashbang** [jordansissel/fpm#1160]
How to replicate:
[env]
Python 2.7.2, fpm 1.0.2 (I realize this is a very old version but the issue also shows up in newer versions of fpm)

[command]
`fpm --verbose -s python -t deb thrift==0.9.1`

[error]
Trying to download {:package=>"thrift==0.9.1", :level=>:info}
Searching for thrift==0.9.1 {:level=>:info}
Reading http://pypi.python.org/simple/thrift/ {:level=>:info}
Best match: thrift 0.9.1 {:level=>:info}
Downloading https://pypi.python.org/packages/c9/76/86ba27252c48545a60ee85110b87cf2072bd7e9e2c302bbe04c5ab443758/thrift-0.9.1.tar.gz#md5=8989a8a96b0e3a3380cfb89c44e172a6 {:level=>:info}
Processing thrift-0.9.1.tar.gz {:level=>:info}
 {:level=>:info}
Extracted editable version of thrift==0.9.1 to /tmp/package-python-build20160712-12212-9scza/thrift==0.9.1/thrift {:level=>:info}
 {:level=>:info}
If it uses setuptools in its setup script, you can activate it in {:level=>:info}
"development" mode by going to that directory and running:: {:level=>:info}
 {:level=>:info}
    /usr/bin/python setup.py develop {:level=>:info}
 {:level=>:info}
See the setuptools documentation for the "develop" command for more info. {:level=>:info}
 {:level=>:info}
fetching package metadata {:setup_cmd=>"env PYTHONPATH=/var/lib/gems/1.8/gems/fpm-1.0.2/lib/fpm/package python setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build20160712-12212-9scza/metadata.json", :level=>:info}
running get_metadata {:level=>:info}
Traceback (most recent call last): {:level=>:info}
  File "setup.py", line 95, in <module> {:level=>:info}
    run_setup(True) {:level=>:info}
  File "setup.py", line 91, in run_setup {:level=>:info}
    **extensions {:level=>:info}
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup {:level=>:info}
    dist.run_commands() {:level=>:info}
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands {:level=>:info}
    self.run_command(cmd) {:level=>:info}
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command {:level=>:info}
    cmd_obj.run() {:level=>:info}
  File "/var/lib/gems/1.8/gems/fpm-1.0.2/lib/fpm/package/pyfpm/get_metadata.py", line 69, in run {:level=>:info}
    u(self.distribution.get_author_email()), {:level=>:info}
  File "/var/lib/gems/1.8/gems/fpm-1.0.2/lib/fpm/package/pyfpm/get_metadata.py", line 23, in u {:level=>:info}
    return s.decode('utf-8') {:level=>:info}
AttributeError: 'list' object has no attribute 'decode' {:level=>:info}
Process failed: /bin/bash failed (exit code 1). Full command was:["/bin/bash", "-c", "env PYTHONPATH=/var/lib/gems/1.8/gems/fpm-1.0.2/lib/fpm/package python setup.py --command-packages=pyfpm get_metadata --output=/tmp/package-python-build20160712-12212-9scza/metadata.json"] {:level=>:error}

[hypothesis]
packages with multiple authors will use a list which the fmp code isn't managing well and failing to read the list and encode into unicode. I suspect single authors won't use a list and will still build correctly.

[my fix]
edit "get_metadata.py"

``` python
if PY3:
    def u(s):
        return s
else:
    def u(s):
        if isinstance(u, unicode):
            return u

        if isinstance(s, list):
            s = s.pop()

        return s.decode('utf-8')
```

It seems to me the return u is returning the function which I'd not expect to work at all.  I realize this is a hack and is incomplete as it only returns the single author and not the correct list, but it bypasses the problem until a permanent fix can be implemented.

**Comment by jordansissel** [comment]
> AttributeError: 'list' object has no attribute 'decode' {:level=>:info}

I agree that the bug here seems to be that we don't expect the `author` to be a list. Your proposed fix seems reasonable. Would you mind submitting a PR for this?

**Comment by bashbang** [comment]
I've finally got around to implementing this code change.  I'll please need push permissions to create the branch to make the PR.

**Comment by jordansissel** [comment]
You don't need permissions on this repo to open a PR. Fork the repo on
github and push the branch to your fork, then open a PR from your branch.

**Comment by bashbang** [comment]
Done
