### ISSUE TITLE
RPM there is currently no way to provide distribution/custom suffix

### ISSUE THREAD

**Issue by akamensky** [jordansissel/fpm#1166]
RPM packages are often (almost always) are marked with distribution (el5/el6/el7). Example: http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/

But right now there is no way to specify this during the build time (unless I provide full package name, which I don't want to).

At first I though --rpm-os should do that, but it does not.

Anyhow, there must be either --rpm-releasever option, or --suffix option (optionally taking a list of values).

**Comment by akamensky** [comment]
The reason for this is that in my case I ma using make to actually compile binaries and package them. As the result of different glibc version on el6 and el7 I need to compile two versions. Thus I need to have a way to specify that...

**Comment by jordansissel** [comment]
Maybe the --iteration flag (this sets the rpm release tag)? I don't know
what's common for rpms in this manner. My experience is that different
distro rpms are served from different repositories.

**Comment by akamensky** [comment]
@jordansissel --iteration sets iteration in version (which is X.X.X-X - last number is iteration), distribution tag is completely different.

**Comment by akamensky** [comment]
@jordansissel Please look at the example link of Zabbix rpm repository. Yes it is as you say 3rd party repository, but it still follow convention of placing distro tag into it. For example Amazon Linux puts there "amzn" instead of "el6" (although it is based off Centos6)

**Comment by jordansissel** [comment]
In this zabbix package, the filename is this: http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-2.4.0-1.el6.x86_64.rpm

The 'el6' is the distro, right?

If I download it and ask the RPM about itself, I see the following:

```
% rpm -qip zabbix-2.4.0-1.el6.x86_64.rpm | grep el6
Release     : 1.el6
```

So, Zabbix is doing what I was proposing you to do. They embed the 'distro' in the `Release` tag in the package. 

Since `fpm`'s `--iteration` flag sets the `Release` tag for rpms, we can do this with fpm without changes to fpm:

```
% fpm -s empty -t rpm -n example --iteration 1.el6
% rpm -qip example-1.0-1.el6.x86_64.rpm| grep el6
Release     : 1.el6
```

**Comment by akamensky** [comment]
That worked.

Though still feels hacky...
