### ISSUE TITLE
fpms common command-line options should have long (e.g. --output_type) version, too.

### ISSUE THREAD

**Issue by fwolfst** [jordansissel/fpm#1187]
`fpm` is so much fire-and-forget that I use it in some scripts and it basically just-works(tm). But on revisiting the scripts, I wonder about what e.g. the option `-s` or `-t` was about. Most options like '-f' have their speaking alternative, like '--force', which I will always use in scripts so that I understand directly what happens. Unfortunately, two often used options do not have a long version.

It would be great if these "short" version would be accompanied by respective long versions. I propose:

    option "-t", "OUTPUT_TYPE"
    -> option ["-t", "--output-type"], "OUTPUT_TYPE"

    option "-s", "INPUT_TYPE",
    -> option ["-s", "--input-type"], "INPUT_TYPE"

Give me a go and I branch and merge request. As a bonus I would add (and this one is more complicated :) ):

    -C CHDIR -> --chdir

**Comment by hatt** [comment]
Off the top of my head I think they're `source` and `to`. Tools like iconv use `to` and `from` but then you can't use `-f` for `force`. Since it already says input/output type in the help, sounds like reasonable enough flags. See PR.

**Comment by fwolfst** [comment]
Awesome. I would have done it the same :)
Thanks. I guess you'll close this issue with the PR.

**Comment by jordansissel** [comment]
@hatt source and target, though in the code they are called `input` and `output` ... we may claim that I am not the most consistent in naming ;P
