### ISSUE TITLE
fpm should support bz2 format of data

### ISSUE THREAD

**Issue by shalq** [jordansissel/fpm#1212]
# fpm  --iteration 37.56 --verbose --debug -s deb -t deb linux-image-4.4.0-37_4.4.0-37.56_amd64.deb

Invalid package configuration: Unknown compression type 'gz'  {:level=>:error, :file=>"fpm/command.rb", :line=>"495", :method=>"rescue in execute"}
# ar t /opt/redstone/builds/workload/ubuntu-xenial.wiki/linux-image-4.4.0-37_4.4.0-37.56_amd64.deb

debian-binary
control.tar.gz
data.tar.bz2

To fix this issue, fpm should support bz2 .

**Comment by jordansissel** [comment]
This only affects `-s deb` right?

**Comment by jordansissel** [comment]
#1213 merged.
