### ISSUE TITLE
Post installation command

### ISSUE THREAD

**Issue by waghanza** [jordansissel/fpm#1220]
Hi,

I know that there a way to add a script as à trigger to package installation (after-install).

Actaully this is suitable for a bunch of commands.

I have just a ldconfig to run.

Is there any suitable option for me ?

Regards,

**Comment by hatt** [comment]
Does `--after-install FILE` do what you are looking for?

**Comment by waghanza** [comment]
Not exactly

`--after-install` is looking to a **file**. I have only some commands to run (and I hope I have to include a script in my `package`)

**Comment by hatt** [comment]
If you have more than one command and it's going in a script, that's exactly what this is for. Unless you mean to embed a script in the package itself and have the after-install call it for you?

**Comment by waghanza** [comment]
if fact, I mean I want to trigger some commands after an end user install the package, like :
+ `ldconfig`
+ **create** a specific `user`
+ ...

I dont want to embed a script in the **package**

**Comment by waghanza** [comment]
for more explianation, I've created a **package** for ruby `latest` **version**
https://packagecloud.io/waghanza/plunder/packages/fedora/24/ruby-2.3.3-1.x86_64.rpm
and I want to trigger `ldconfig` (to renew cache) after user installation

how can I do that ?

**Comment by hatt** [comment]
I understand now. RPM post/pre scriptlets are embedded in the package metadata but are not scripts in the package contents themselves. You just make a script file that contains everything you want to do and pass the filename to FPM with the `--after-install` or whatever other event you want. FPM will put the contents of the script you give (as a file) into the appropriate block in the spec file.

I think the confusion here is that while the flag takes a file and not direct commands, it does in fact embed it in the spec and not as a separate file going into the package itself.

**Comment by waghanza** [comment]
ok, I understand now.

I think `option` name is **confusing** (at least for me).

I'll try this later

**Comment by rayyanjaweed** [comment]
Does the --after-install tag accept more than one file ?

**Comment by maxadamo** [comment]
@rayyanjaweed again? :smile: Please read the thread first.
