### ISSUE TITLE
[deb] support activate-noawait and interest-noawait

### ISSUE THREAD

**Issue by philtay** [jordansissel/fpm#1225]
Currently `--deb-activate` and `--deb-interest` options allow to specify `activate` and `interest` triggers only. Please add `--deb-activate-noawait` and `--deb-interest-noawait` options to support `activate-noawait` and `interest-noawait` triggers too. More info on deb-triggers [here](http://man7.org/linux/man-pages/man5/deb-triggers.5.html). It looks like a trivial PR, but I don't speak Ruby.

**Comment by nthykier** [comment]
Very much a good idea.  The average user of triggers generally want the "-noawait" variant and notably it avoids the entire problem of "trigger-cycles".  I would go so far to as to recommend people to use the noawait triggers by default in the documentation.

**Comment by philtay** [comment]
ping @jordansissel

**Comment by jordansissel** [comment]
The link to more information on triggers looks like a lot of nice details.
Thanks!

I personally don't use triggers, so I don't have much self interest in this
feature. If someone comes up with a proposal, I am open to patches for this.

**Comment by ppoilbarbe** [comment]
I have done it... It's not quite difficult even if I do not understand all the magic under the hood of Ruby (I did just mimic what have been done for --deb-interest and --deb-activate).
Do you prefer a patch or a merge request ?

**Comment by jordansissel** [comment]
#1359 merged
