### ISSUE TITLE
a way to use the -v version tag without it being embedded in the filename

### ISSUE THREAD

**Issue by joannbrereton** [jordansissel/fpm#1233]
I'm not sure if this is the right place for a question/request like this.  Feel free to delete if it is not.

I'm using fpm within Jenkins to create an RPM.   Looks something like this:

/usr/bin/fpm -s dir -t rpm --rpm-user ${APP_USER} --rpm-group ${APP_GROUP} -p ${WORKSPACE}/rpms -v ${MYDATE} -C $WORKSPACE/buildroot -n ${APPLICATION} --prefix=${SERVICE_HOME} --url "${BUILD_URL}" --description "${APPLICATION}" .

What I end up with is an npm named ${APPLICATION}-${MYDATE}-1.x86_64.rpm

Is there some way to keep the versioning (for yum) but NOT have it embedded in the filename of the npm?

**Comment by jordansissel** [comment]
The `-p` flag lets you specify the output path, which can include the full filename.


FOr your example: `-p ${WORKSPACE}/rpms/NAME.ARCH.EXTENSION` should work. (Where 'NAME', etc, are literally the word "NAME" which fpm uses as a template for the package name, and architecture, and file extension)

**Comment by joannbrereton** [comment]
Excellent, thank you.
