### ISSUE TITLE
`--prefix` doesn't work nicely with virtualenv

### ISSUE THREAD

**Issue by nicobrevin** [jordansissel/fpm#1248]
As per @josegonzalez's suggestion, here's an issue to discuss my ill-ease with the current set of options for virtualenv packaging.

I'm not particularly happy with the inconsistencies in the virtualenv support, it looks like someone else's conventions have been baked in to the way the options are structured, instead of just using prefix . I've thought about changing it, but this will probably make lots of people sad, because I can't think how to do it without breaking existing behaviour. Perhaps the simplest option could be to get the --prefix option to take preference over all the other prefix-altering options (--virtualenv-install-location, automatically naming the last path segment after the egg spec/`dirname requirements.txt`) - currently prefix adds an extra set of path segments in front.

**Comment by nicobrevin** [comment]
Some examples that show that it's difficult to put stuff exactly where you want it:

    # puts everything under /opt/usr/share/python/absolute
    fpm -f -s virtualenv -t deb --name test --prefix /opt --virtualenv-install-location  absolute

    # puts everything under /opt/absolute
    fpm -f -s virtualenv -t deb --name test --virtualenv-install-location /opt absolute

    # if I want everything under /opt/test, I need to:
    mkdir test
    echo 'absolute' > test/requirements.txt
    cd test && fpm -f -s virtualenv -t deb --name test --virtualenv-install-location /opt requirements.txt

So perhaps changing behaviour to get --prefix to take precedence over the --virtualenv-install-location and auto-dir name thing is the fix?

**Comment by jordansissel** [comment]
I'm in favor of this. We could make --virtualenv-install-location deprecated and have --prefix be preferred.

**Comment by toddjames** [comment]
Can't wait to see this implemented. Thanks for taking the initiative, @nicobrevin. I've been struggling to get virtualenvs working to my liking in fpm, and I think this will solve it.

**Comment by nicobrevin** [comment]
@toddjames yeah, just realised the tests were failing in #1262, which is possibly why not included in 1.8

**Comment by nicobrevin** [comment]
#1262 Was merged
