### ISSUE TITLE
before-install script fails

### ISSUE THREAD

**Issue by yambakshi** [jordansissel/fpm#1250]
I created an RPM with a bash before-install script that checks if Java is installed on current machine.
The code looks like that:
```
#!/bin/sh


# Check if Java is installed
if type -p java; then
    echo "Found Java executable in PATH";
    _java=java;
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo "Found Java executable in JAVA_HOME";
    _java="$JAVA_HOME/bin/java";
else
    echo "Java is required";
    exit 1;
fi
```

When I run the script on a machine with Java installed (_sh before_install.sh_) it works, but when the RPM installation runs it, it fails to find the installed Java, prints:

> Java is required

And the installation fails (as it should).

Any ideas?

**Comment by josegonzalez** [comment]
You'll need to include java as a dependency - whether that is openjdk or oracle for your specific os - to the built rpm package. `--depends` is the flag you should specify on fpm `itself`.
