### ISSUE TITLE
Setting environment variable for a specific package

### ISSUE THREAD

**Issue by waghanza** [jordansissel/fpm#1251]
Hello,

Many languages
* `ruby`
* `python`
* `go`

have **environment variables** defined.

Generally, it could be change on the command line.

Example :

~~~python
PYTHONPATH=/opt/python python c 'import os;print(os.environ["PYTHONPATH"])'
~~~

Can I specify a **specific** value to **fpm** for that ?

Regards,

PS : Not sure if really an `fpm` question

**Comment by josegonzalez** [comment]
What exactly is your goal here? Rephrased, what are you trying to do that you need to set environment variables for FPM?

**Comment by waghanza** [comment]
in fact, it's not **for** `fpm`, but **with** `fpm`

i want to add environment variable after the `package` installation

**Comment by josegonzalez** [comment]
What are you going to use that environment variable for? During the installation process? For running the service?

**Comment by waghanza** [comment]
this environment variable will be use by the interpreter himself

**Comment by josegonzalez** [comment]
This sounds like you want to set something for the running of the service, after it is installed.

The common way to do this is to have a file in `/etc/default` that is sourced by your application - either via a wrapper or directly - which will have configuration for your app. Many process managers - upstart, init, systemd - will allow you to source an environment file to extend the running application environment, and I would say its the preferred method of modifying an app's runtime configuration.

If you cannot execute your application via a wrapper *or* read in external configuration, there isn't anything fpm can do here.
