### ISSUE TITLE
pleaserun: support upgrades for environment variables

### ISSUE THREAD

**Issue by cfstras** [jordansissel/fpm#1263]
This issue is more-or-less exploratory, I wanted to get some feedback before building something nobody but me wants.

Right now, (at least in my example case), the pleaserun package overwrites configuration files at install.
(for reference, my pacakges always call "/usr/share/pleaserun/$package/install.sh", even on upgrade).

If a package wants to add new environment variables with an upgrade, there should be some kind of control-flow to allow that. If you were to build a new version, and add another entry to `:pleaserun_environment_variables`, you have the choice that they either don't appear at all, or to overwrite the existing config (by doing what I describe in the paragraph above).

I realize this is an essential problem that package managers have to tackle. There should be support for the "just make it work"-version that fits the fpm motto (as percieved by myself).

Here's an example for how to do that:
- extract variable names from existing config
- append only non-existing variables, and leave the rest alone

Implemented in: https://github.com/cfstras/fpm/commit/2315d1a3892550dd9edbdf2b211372b74efabd2b
Obviously, this is missing support for removing obsolete variables, and also it's an ugly monster that requires awk.

Thoughts and criticism welcome!

**Comment by nicobrevin** [comment]
I find this sort of task a lot easier using configuration management tools
rather than using post install hooks, but I appreciate that this might not
work for you.

Another option could be that you source environment variables from a .d
directory rather than a single file. Then adding new ones is a lot simpler.

**Comment by hatt** [comment]
I'm would echo what @nicobrevin has suggested with using a `.d` directory; it's somewhat a standard and you can prioritise load order by name prefixing (ie: `10-important.sh, 99-bleh.sh`). Usually software uses `/etc/system/default` or `/etc/defaults` depending on platform as a master loader, and then sources from the `.d` directory as appropriate. I think that's a relatively good pattern, and even without the system defaults dirs the `.d` pattern is quite robust.

Configuration management also simplifies a lot of this, but understandable isn't always an option.

**Comment by cfstras** [comment]
Thanks for your suggestions! I'm going to close this, as it does not really concern fpm.
