### ISSUE TITLE
C Project Support

### ISSUE THREAD

**Issue by Darren996** [jordansissel/fpm#1274]
Hi,

Sorry for the dumb question.  I have about 10 days to figure out how to make a package.  I'm a raspbian noob.  Does this work for C projects?  If it doesn't is there one that does?  I just need to deploy a service.

Thanks,
Darren

**Comment by nicobrevin** [comment]
Yep, it can, but fpm isn't a build tool - you still need to compile
everything yourself.

Iirc there is a simple example in http://bit.ly/mMJMGP

If you need something more substantial, the vagrant project includes a
quite complex example of compiling a bunch of c projects inside a custom
prefix using autotools and then slurping up the result in to a package
using fpm - https://github.com/mitchellh/vagrant-installers.

Hth,
Nick

**Comment by Darren996** [comment]
Thanks for the reply.   So it doesn't make the package it just converts from one package to another?

**Comment by josegonzalez** [comment]
That is correct. You'll need to still build the artifact you want to ship.
