### ISSUE TITLE
fpm packaging ?

### ISSUE THREAD

**Issue by steph-ben** [jordansissel/fpm#1276]
I didn't find any packaging for fpm itself ... which is an interesting fact for a packaging helper ? :-)

Ideally, I would like to be able to do:
` yum install fpm`

Any place I'm missing ?

**Comment by liger1978** [comment]
I've packaged it for CentOS 7, details here: https://gitlab.com/harbottle/ergel

**Comment by josegonzalez** [comment]
If you would like to implement official packaging of fpm, please file a pull request and we'll be sure to attempt to incorporate it within our release cycle.
