### ISSUE TITLE
`find_spec_for_exe': can't find gem fpm (>= 0.a) (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by RSamal** [jordansissel/fpm#1295]
Hi,

I am trying to run fpm through Jenkins in Jenkinsfile but getting the below exeception. Any suggestion?
`/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems.rb:270:in `find_spec_for_exe': can't find gem fpm (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/fpm:22:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by Overdrivr** [comment]
I'm getting the same error. What did you do to solve it ?

**Comment by vikingzp** [comment]
do not use root
