### ISSUE TITLE
Travis-ci builds are failing

### ISSUE THREAD

**Issue by pillarsdotnet** [jordansissel/fpm#1317]
Dunno why, but even the most trivial change results in a failed build.

See for example [PR#1315](https://github.com/jordansissel/fpm/pull/1315).

**Comment by jordansissel** [comment]
I don't watch travis for failures, honestly. I test locally and this satisfies me. I understand other folks may rely on travsi results, though :)

The travis failures I see most are on OSX and are likely related to long filenames being rejected by the OS during the test suite run. I haven't looked much more beyond that.

**Comment by josephholsten** [comment]
I notice that recent PRs are passing tests. I'm going to close this, but if you've noticed sporadic errors or anything else, let us know!
