### ISSUE TITLE
Use Python scripts for pre/post install scripts

### ISSUE THREAD

**Issue by mkvonarx** [jordansissel/fpm#1319]
I'd like to use Python scripts for the pre/post install scripts (--before-install, --after-install etc.) for my rpm packackages.

Although fpm accepts Python script files on the command line, they are still marked as plain shell scripts in the RPM. rpm -qp --scripts says "preinstall scriptlet (using /bin/sh):". And and installation attempt via yum install of course fails because the script does not contain valid Bash script.

The rpm -qp --scripts output seems to indicate that it could be possible to use another script interpreter than /bin/sh. Otherwise it probably wouldn't print this information.

Is there a way to tell fpm to mark the pre/post install scripts as Python scripts and to tell rpm that they are Python scripts?

**Comment by jordansissel** [comment]
I have never tried this, but I can confirm the rpm format supports an
indicator of what the type is for each script. I don't know of anyone who
has done this in the wild.

As a workaround, you could have a shell script call your python script with
'exec your-python.py "$@"'

**Comment by mkvonarx** [comment]
Thanks for the quick reply. I think I can live with that workaround. Or just write a Bash script.

**Comment by jhermann** [comment]
Or this:

```console
$ cat xmagic.py
#!/bin/sh
"""/usr/bin/python3" -x "$0" "$@" ; exit "$?"""
import sys
print("Hello from sh and Python {}!".format(sys.version.split()[0]))
$ ./xmagic.py 
Hello from sh and Python 3.5.2!
```
