### ISSUE TITLE
updating config files for rpm targets

### ISSUE THREAD

**Issue by apiemont** [jordansissel/fpm#1322]
was dealing with config files for rpm targets: I have marked one file as such, e.g. created the package with

```
$ fpm  -f -s dir -t rpm -n foo -v 1.0.0 --iteration 2 --description "A sample package" --config-files /etc/send_nsca.cfg opt/sbin/send_nsca=/sbin/send_nsca  opt/etc/send_nsca.cfg=/etc/send_nsca.cfg
$ rpm -qp --filesbypkg foo-1.0.0-1.x86_64.rpm 
foo                       /etc/send_nsca.cfg
foo                       /sbin/send_nsca
```

 then installed the rpm via

```
# yum localinstall foo-1.0.0-1.x86_64.rpm
# rpm -qc foo
/etc/send_nsca.cfg
```

then I edited that file, (only uncommented one line), then created a new package (just bumped revision number via the iteration option) and updated it

`# yum localupdate foo-1.0.0-2.x86_64.rpm `

and what I find in /etc is only the original config file (with my line commented out), but no .rpmnew one

```
# find  /etc -iname "*send_*"
/etc/send_nsca.cfg
# 
```

am I missing something? thx

**Comment by ocontant** [comment]
I'm just guessing here, but it might be close to what is going on. 

You create RPM version 1.0.0-1 with some content,
You then create a new RPM 1.0.0-2 with the same content as 1.0.0-1

The hash of the file described in you RPM file are identical.  So when you run yum localupdate RPM-1.0.0-2, RPM installer detect identical hash for the current installed version and skip it. 


Does it sound like this is what's going on?

**Comment by apiemont** [comment]
yes, I believe it so. To verify I created a 1.0.0-3 package with a new line in its config file (which wasn't there in the 1.0.0-2), and when installing (with yum localupdate) I get now the expected result (excerpt only):

`Running transaction
  Updating   : foo-1.0.0-3.x86_64                                                                                                       1/2 
warning: /etc/send_nsca.cfg created as /etc/send_nsca.cfg.rpmnew
`
Thanks for the hint, this issue can be closed.
