### ISSUE TITLE
fpm builder for Packer.io

### ISSUE THREAD

**Issue by thefosk** [jordansissel/fpm#1334]
Is anybody working on a fpm builder for [Packer](https://www.packer.io/)?

**Comment by nicobrevin** [comment]
Do you mean as an output? Or a packer script for building an fpm dev
environment?

**Comment by thefosk** [comment]
As an output.

**Comment by nicobrevin** [comment]
Isn't packer meant for building machine images? I mean you could, I just
wonder why.  Are you trying to put a root fs in to a package?

**Comment by thefosk** [comment]
Because I am trying to build rpm and deb packages along with images.

**Comment by nicobrevin** [comment]
You could do it with a shell post provisioner. Say you're building a
vagrant box, you run fpm in a shell post processor and output the package
in to a shared folder. Is this the kind of integration you're thinking of?

**Comment by thefosk** [comment]
@nicobrevin you are correct, that worked.
