### ISSUE TITLE
"missing" dependency on Fedora

### ISSUE THREAD

**Issue by Salamandar** [jordansissel/fpm#1351]
I couldn't build Fpm on Fedora 25, and finally found out I had to install libffi-devel. It should be in the documentation !

**Comment by shevegen** [comment]
Perhaps a file called INSTALL.md or INSTALLATION.md with some recommended build installation (may be already existing; I did not find it).

**Comment by jordansissel** [comment]
The install docs are here: http://fpm.readthedocs.io/en/latest/installing.html

But I just now notice that there's no link specifically to the install docs from the readme, I will fix that. Thank you for pointing this out!

**Comment by josegonzalez** [comment]
Also please add it as the default url when visiting the project page (its at the top near the project description, only repo admins can do this).

**Comment by jordansissel** [comment]
@josegonzalez good idea, I just now linked to http://fpm.readthedocs.io/en/latest/ for the github repo -- was that what you meant?
