### ISSUE TITLE
How do I strip libraries in my RPM?

### ISSUE THREAD

**Issue by vkotovv** [jordansissel/fpm#1353]
Hi,

I've seen in the [changelog](https://github.com/jordansissel/fpm/blob/master/CHANGELOG.rst) that stripping libraries was disabled long time ago. But how do I use that if I need to [strip](https://sourceware.org/binutils/docs/binutils/strip.html) my executables and libraries in my produced RPM?

**Comment by vkotovv** [comment]
As for now, I just run strip command manually before running fpm

**Comment by josegonzalez** [comment]
Yeah, if you want to have stripped binaries/libraries, you'll want to do that stripping when creating the binaries.
