### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by nicobrevin** [jordansissel/fpm#1366]
Hi there,

I have some sponsored company time to do an actual day's work on a FOSS thing, and I think I'd like to spend that time improving the docs for fpm, but in order for it to not be a waste of time (and given I'm in NZST) I could do with some:

* assurance it might get merged
* guidance on what you will or won't accept

Beyond that, my plan was to look at the recent requests for help for inspiration,  and improve the docs by providing more reference as well as by providing more illustrated examples.

Thoughts?

**Comment by josegonzalez** [comment]
> assurance it might get merged

It'll probably get merged at some point. As far as I know, no one with commit bit gets paid to look at `fpm`, so the limitation there is time.

> guidance on what you will or won't accept

Anything that breaks functionality won't be accepted. There may be a bit of back and forth in terms of cleaning up functionality, so you'll need to be patient on that.

> Beyond that, my plan was to look at the recent requests for help for inspiration, and improve the docs by providing more reference as well as by providing more illustrated examples.

Go for it, examples and expanded docs would be lovely!

**Comment by jordansissel** [comment]
To add to what Jose said, I am sure FPM users would love to have some
better docs. :)
