### ISSUE TITLE
RPM packages fails to create folder hierarchy on install

### ISSUE THREAD

**Issue by fmanea** [jordansissel/fpm#1386]
I have build a package with fpm, but on each folder that is needed to be created it gives me:
```error: Failed dependencies: /usr/lib64/jvm/openjdk-9/bin is needed by openjdk-9```
 
Something that is close to this issue:
https://stackoverflow.com/questions/21557015/build-rpm-to-just-install-files

**Comment by jordansissel** [comment]
I think you need to set `--rpm-auto-add-directories` when creating your package.

If that doesn't help, can you show your full `fpm` command?

**Comment by fmanea** [comment]
Hello, It did help, thank you!
If I got your attention, is there a way to add symbolic links to some binaries inside the package rpm, with this tool? I know, that in yocto this was possible.
Have a good day!

**Comment by jordansissel** [comment]
@fmanea yay! :)

As for symbolic links, can you open a new ticket and describe it a bit further?
