### ISSUE TITLE
Specifying version for gem source no longer works

### ISSUE THREAD

**Issue by miked63017** [jordansissel/fpm#1388]
If you run the command:
```
fpm -s gem -t rpm --verbose 'mustache == 0.99.8'
```
the variable ```version``` is set to nil in the input method of gem.rb

This is the output before it eventually times out:
```
Setting workdir {:workdir=>"/tmp", :level=>:info}
Working with: {:gem=>"mustache == 0.99.8", :version=>nil, :level=>:info}
Trying to download {:gem=>"mustache == 0.99.8", :version=>nil, :level=>:info}
ERROR:  Could not find a valid gem 'mustache == 0.99.8' (>= 0) in any repository {:level=>:info}
```

Maybe I am doing something wrong, IDK, but I made a quick change to gem.rb to make it work on my system:

```
  def input(gem)
    # 'arg'  is the name of the rubygem we should unpack.
    split_up = gem.split(" ")
    path_to_gem = download_if_necessary(split_up[0], split_up[2])
........
```

Maybe a little hackish, but I needed it to work right now. I can put in a PR if it helps, but I am leaning towards me probably doing something wrong. Whats weird IMO is that this same syntax seems to work fine with python specified as the source type:

```
fpm -t rpm -s python 'colorama == 0.3.7'
Created package {:path=>"python-colorama-0.3.7-1.noarch.rpm"}
```

This is fpm version 1.8.1 installed via rubygems I am using.

**Comment by jordansissel** [comment]
Interesting; I dont' think I've ever tried this specific case where you specify a kind of query "mustache == 0.99.8" as the input to the `-s gem`

I use this the `-v` flag for this purpose:

```
% fpm -s gem -t rpm -v 0.99.8 mustache
Created package {:path=>"rubygem-mustache-0.99.8-1.noarch.rpm"}

% rpm -qlp rubygem-mustache-0.99.8-1.noarch.rpm | grep gemspec
/home/jls/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/specifications/mustache-0.99.8.gemspec
```

**Comment by jordansissel** [comment]
I'm open to making something like this work, but it's unclear if it ever did work?

Testing on other versions of fpm:

* 1.8.1: 

```
% fpm -s gem -t rpm "mustache == 0.99.8"
/home/jls/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fpm-1.8.1/lib/fpm/package/gem.rb:92:in `download': Unexpected number of gem files in /tmp/package-gem-build-2a93445e3f8006e5606f8f11318e45319c51f1edb501037f78ed99e59821/mustache == 0.99.8,  0 should be 1 (RuntimeError)
```

* 1.5.0: 

```
% fpm -s gem -t rpm "mustache == 0.99.8"
s/home/jls/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fpm-1.5.0/lib/fpm/package/gem.rb:89:in `download': Unexpected number of gem files in /tmp/package-gem-build20170727-5090-1joywzv/mustache == 0.99.8,  0 should be 1 (RuntimeError)
```

* fpm 1.4.0

```
% fpm -s gem -t rpm "mustache == 0.99.8"
/home/jls/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/fpm-1.4.0/lib/fpm/package/gem.rb:89:in `download': Unexpected number of gem files in /tmp/package-gem-build20170727-5279-1hjoxuq/mustache == 0.99.8,  0 should be 1 (RuntimeError)
```

**Comment by miked63017** [comment]
How is version even set in the input method? It seems to work in the python
one but not the gem source, I did not dive in too deep but I cannot see why
version is set in the python source, but nil in the gem source.

**Comment by jordansissel** [comment]
My intent originally was that users would specify the version with `-v` flag and the package sources would do the right thing, so:

* `fpm -s gem -t rpm -v 1.2.3 foo` would fetch the `foo` gem version 1.2.3 and build an rpm of it
* `fpm -s python -t rpm -v 1.2.3 foo` would fetch `foo` python package version 1.2.3 from pypi and build an rpm of it.

Does this kind of thing work with the python source? Can you show me an example?

**Comment by miked63017** [comment]
Seems to work with python:
[root@stldaurajkns01 tmp]# fpm -t rpm -s python --verbose -v 0.3.7 colorama
Setting workdir {:workdir=>"/tmp", :level=>:info}
Trying to download {:package=>"colorama", :level=>:info}
Searching for colorama==0.3.7 {:level=>:info}

but still not with gem:
[root@stldaurajkns01 tmp]# fpm -s gem -t rpm --verbose -v 0.5.2
archive-tar-minitar
Setting workdir {:workdir=>"/tmp", :level=>:info}
Trying to download {:gem=>"archive-tar-minitar", :version=>nil,
:level=>:info}

**Comment by jordansissel** [comment]
Whoa, version is nil? What version of fpm are you using? When I run it, I see this:

```
% fpm -s gem -t rpm --verbose -v 0.5.2 archive-tar-minitar
Setting workdir {:workdir=>"/tmp", :level=>:info}
Trying to download {:gem=>"archive-tar-minitar", :version=>"0.5.2", :level=>:info}
```
^^ `:version => "0.5.2"`

**Comment by miked63017** [comment]
Running 1.8.1 from rubygems

Thanks,
Mike Donlon

**Comment by miked63017** [comment]
Wait that last one might be because I only partially removed my change now
that I think about it. Won't be back to the computer till tomorrow though
to confirm.

Thanks,
Mike Donlon

**Comment by miked63017** [comment]
Sorry for the delay, it works on my copy too. Closing...Thanks!
