### ISSUE TITLE
remove failed: No such file or directory when upgrading a packge

### ISSUE THREAD

**Issue by bortek** [jordansissel/fpm#1409]
I have built an rpm package using fpm and now upgrading a previously installed rpm (which was not build with fpm) . when running "yum update" it first tries to remove the existing rpm and then install new one. 

While removal I get lots of these warnings

   Cleanup: some_rpm_file_name.rpm
warning: file /some/file/here: remove failed: No such file or directory

These files do not exist in the old rpm (only in new one) and it warns because it tries to remove the files that are in the new package. Which is kinda strange. Anyhow. How do I supress these warning when I build rpm using fpm, is it possible?

**Comment by Paradox98** [comment]
I have the same problem, how did you solve it

**Comment by bortek** [comment]
Oh this was so much in the past. Sorry but I have no recollection of how I solved it.
