### ISSUE TITLE
fpm gem fails to install ubuntu 14

### ISSUE THREAD

**Issue by introllo** [jordansissel/fpm#1414]
Hi. Apologies if this is a dupe. I checked the issues list and didn't see my scenario. So, thought I'd add an issue and ask for help!

We've been successfully using FPM on Ubuntu 16 docker images. Now, I'm moving to Ubuntu 14 (yeah, yeah I know) and provisioning w/Ansible (tho I don't think Ansible is a factor) to a Vagrant VM.

Ansible fails with "rc -9". A "gem install -V fpm" on the remote fails with "Killed". Neither work well for my plan to get home tonight. Sudo/non-sudo fail similarly.  All the dependencies are installed in an earlier play.  Advice is greatly appreciated.

Details...
vagrant@ansible:~$ ansible myagent1 -b -m gem -a 'name=fpm state=present include_doc=no'
myagent1 | FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/gem install --include-dependencies --user-install --no-rdoc --no-ri fpm", 
    "failed": true, 
    "msg": "", 
    "rc": -9, 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}

vagrant@ansible:~$ ansible myagent1 -b -m command -a "lsb_release -cr"
myagent1 | SUCCESS | rc=0 >>
Release:	14.04
Codename:	trusty

vagrant@ansible:~$ ansible myagent1 -b -m command -a "ruby -v"
myagent1 | SUCCESS | rc=0 >>
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

vagrant@ansible:~$ ansible myagent1 -b -m command -a "gem -v"
myagent1 | SUCCESS | rc=0 >>
1.8.23

vagrant@ansible:~$ ansible myagent1 -b -m command -a "gem install -V fpm"
myagent1 | FAILED | rc=-9 >>
non-zero return code

vagrant@myagent1:~$ gem install -V fpm
GET http://rubygems.org/latest_specs.4.8.gz
200 OK
GET http://rubygems.org/specs.4.8.gz
200 OK
Killed

**Comment by jordansissel** [comment]
>  Killed

No idea why it was killed. I doubt `gem` did this on purpose. My first guess would be the Linux OOM killer causing this (you're on a vm, possibly with not enough ram? I don't know). You can check `dmesg` on your vm and look for any oom killer logs.

**Comment by introllo** [comment]
Yep. That's in play here. Rebuilding VMs with more mem. Will try again. Thx!
