### ISSUE TITLE
RFE: can you add support for using multi-threaded compression in rpmbuild

### ISSUE THREAD

**Issue by amnonbc** [jordansissel/fpm#1419]
e.g. by defining

`%define _binary_payload w7T.xzdio
`
in the spec file?

Thanks!
   Amnon

**Comment by jordansissel** [comment]
For a workaround, you can use the `--rpm-rpmbuild-define` flag. This should work:

`--rpm-rpmbuild-define "_binary_payload w7T.xzdio"`

**Comment by amnonbc** [comment]
:+1:

**Comment by amnonbc** [comment]
how would this interact with the `--rpm-compression` flag?

**Comment by amnonbc** [comment]
@jordansissel I tried it, and it unfortunately does not work with fpm-1.9.3

`fpm --debug --rpm-rpmbuild-define "_binary_payload w7T.xzdio" -e -t rpm -s dir -n foo .`

yields

```
# Use gzip payload compression
%define _binary_payload w9.gzdio
```
