### ISSUE TITLE
'fpm -s pleaserun' option isn't recognised by fpm 1.9.3

### ISSUE THREAD

**Issue by neomatrix369** [jordansissel/fpm#1424]
When I try the following:

```
fpm -s pleaserun <rest of the args> 
```
I get the below error and does not build an `.rpm` or `.deb` package:

```
No parameters given. You need to pass additional command arguments so that I know what you want to build packages from. For example, for '-s dir' you would pass a list of files and directories. For '-s gem' you would pass a one or more gems to package from. As a full example, this will make an rpm of the 'json' rubygem: `fpm -s gem -t rpm json` {:level=>:warn}
Fix the above problems, and you'll be rolling packages in no time! {:level=>:fatal}
```

I do have the `pleaserun` gem installed on my system. I also tried this, and got the above error:
```
fpm -s pleaserun <rest of the args>  --pleaserun-name [name of service] \ --pleaserun-chdir /opt/[sub-folder where deb/rpm can be installed]

```

Is this a known issue or am I not passing in the right parameters.

**Comment by jordansissel** [comment]
> fpm -s pleaserun <rest of the args> 

Please provide your entire command line. I can't tell you what is missing from the details you've provided.

**Comment by neomatrix369** [comment]
Hey @jordansissel I found another issue which helped me resolve this one, i'll link it back for posterity - https://github.com/jordansissel/fpm/issues/1112

So all sorted for now!

**Comment by neomatrix369** [comment]
We can close this issue.
