### ISSUE TITLE
.IPK packages for OpenWrt

### ISSUE THREAD

**Issue by mcandre** [jordansissel/fpm#1428]
https://openwrt.org

**Comment by westurner** [comment]
- Docs: https://wiki.openwrt.org/doc/techref/opkg
- Docs: https://wiki.openwrt.org/doc/packages
- Docs: https://wiki.openwrt.org/doc/devel/packages

**Comment by westurner** [comment]
See: #1323 opkg packages

**Comment by mcandre** [comment]
Closing as duplicate
