### ISSUE TITLE
Install instructions would be nice.

### ISSUE THREAD

**Issue by jafcobend** [jordansissel/fpm#1441]
And "gem" is not an option I'll use. I mean, why would I download your tarball from here and then install from some unknown external source? Might be nice if you used fpm to make fpm packages. :-)

In short I downloaded the tarball I want. Where's the instructions for installing from the tarball?

According to your manifesto this is a bug. For me its a critical issue making the project completely unusable. I have no intention of digging into Ruby just to figure out how to install your app.

**Comment by liger1978** [comment]
There is  a discussion of native packages here: https://github.com/jordansissel/fpm/issues/1438

If you want to build and install from source, you'll need ruby, rubygems, ruby development libraries and bundler installed. This works for me:

```
wget https://github.com/jordansissel/fpm/archive/v1.9.3.tar.gz
tar xvsf v1.9.3.tar.gz
cd fpm-1.9.3/
bundle install --path=bundle --binstubs
bundle exec make gem
make install
```

**Comment by josegonzalez** [comment]
Closing in favor of continuing packaging discussion in #1438. Thanks for reporting, and hopefully you can help us figure out what the best way of maintaining and distributing packages is for our users.
