### ISSUE TITLE
Dockerfile Contribution

### ISSUE THREAD

**Issue by dmuth** [jordansissel/fpm#1453]
Hi,

I didn't see a Dockerfile, so I wanted to contribute one.  I built this and use it to build a container in which I can run FPM:

```
FROM alpine:latest

RUN apk add --update \
        ruby \
        ruby-dev gcc \
        libffi-dev \
        make \
        libc-dev \
        rpm && \
        gem install --no-ri --no-rdoc fpm
```

To build and launch this container in interactive mode, you'd use this command:

`docker build -t fpm . && docker run -it -v $(pwd):/mnt fpm`

The current directory would be mounted in `/mnt` in the container.

Please let me know if you have any questions or would like me to turn this into a PR.

Thanks,

-- Doug

**Comment by jordansissel** [comment]
I'm in favor.

There's probably a bunch of missing dependencies that would prevent many of the package types (cpan, python, etc) from working, but this is a fabulous start.

Can you submit a PR with this as-is and I'll merge?

**Comment by dmuth** [comment]
Sure thing!  Will do!

I use your project frequently at work and it's been a huge timesaver, so I'd love to contribute back.

I don't see any sort of test package in the repo, so here's what I'd like to try:

- Creating a script that will convert the test package into different formats (tgz, rpm, and deb to start with), and verify that things went successfully.
- Writing a Dockerfile to run this script

If you're cool with that, can I put that into the test/ directory?

-- Doug

**Comment by jordansissel** [comment]
> I don't see any sort of test package in the repo, 

Ahh, I can explain. fpm has a test suite that lives in the `spec` directory. That said, I don't know if fpm has a test suite that can be invoked as a user, for example, after `gem install fpm` -- but I'm open us having one. Alternately, we can do some kind of test from this docker image where we check out `fpm` from git and run the test suite from there.

**Comment by dmuth** [comment]
Okay, let me try out a couple of ideas.  Will make a pull request to a different branch (assuming that's possible) when I have something. :-)

**Comment by jordansissel** [comment]
```
% docker run -v $PWD:/fpm:Z -it 4b104be11d52 /bin/sh
/ # cd /fpm
/fpm # gem install --no-ri --no-rdoc bundler
/fpm # bundle install
/fpm # bundle exec rspec
```

This lets you run the fpm test suite this way.

Some general failures:

* deb -- the `tar` on alpine doesn't have the expected feature set for fpm:

```
% fpm -s empty -t deb -n example
Process failed: tar failed (exit code 1). Full command was:["tar", "-C", "/tmp/package-deb-build-28e4285f7e445daa4937ca8eb4bbd9059398abadce9f33d89a07a91f8428/control", "-zcf", "/tmp/package-deb-build-28e4285f7e445daa4937ca8eb4bbd9059398abadce9f33d89a07a91f8428/control.tar.gz", "--owner=0", "--group=0", "--numeric-owner", "."] {:level=>:error, :file=>"fpm/command.rb", :line=>"505", :method=>"rescue in execute"}
```

* pacman fails also due missing `bsdtar`

```
/fpm # fpm -s empty -t pacman -n example
Process failed: /bin/sh failed (exit code 127). Full command was:["/bin/sh", "-c", "LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' .PKGINFO"] {:level=>:error}
```

* rpm tests fail, but functionally seem to work. This is due to alpine's use of busybox which provides an incompatible cpio:

```
/fpm # bundle exec rspec -e RPM
...
cpio: unrecognized option: make-directories
```

**Comment by jordansissel** [comment]
Other tests are skipped automatically (like perl) when requisite tools are missing (like cpanm, etc).

**Comment by dmuth** [comment]
Hmm... so if I install bsdtar (libarchive-tools), pacman still fails.  I've only used fpm for converting tar to RPM so that's new to me.

I don't have any experience with rspec, so running it as per the example above results in a bunch of output that I don't fully understand, unfortunately.

Suggestions on how to proceed?  I was originally planning on writing a shell script to try creating some different archive formats like what you did above, but I don't want to duplicate existing effort.  

A few ideas:

1) I could get up to speed on rspec (can you recommend any primers)
2) I could try creating Dockerfiles for other distros (CentOS and Ubuntu to start with)
3) Both #1 and #2.

I'm learning towards #3, what do you think?

-- Doug

**Comment by jordansissel** [comment]
Hey no worries.

> I was originally planning on writing a shell script to try creating some different archive formats like what you did above, but I don't want to duplicate existing effort.

I think this is a good approach.

If you want to learn rspec, then I would encourage using rspec for this. However, if you want to write shell, shell is great also! 

My intuition is to solve the problem the easiest way you can, first, then we can iterate on any implementation changes. By this, I mean, if you write a shell script that verifies a few things about fpm-in-docker, then that is fabulous, and we can use it.

**Comment by dmuth** [comment]
I don't have anything to PR yet, but you can see what I have in progress at https://github.com/dmuth/fpm/commits/master

I tried a bash testing system called BATS, which produces TAP-compatible output and worked great in Ubuntu, but seems to mysteriously fail Alpine, so I may need to rethink that approach.  I will take another whack at it tomorrow and PR when I'm fairly confident that I have something that'll work on at least two distros. :-)

**Comment by bwaterkamp** [comment]
Two quick hints:

1. Are you aware of this repo? https://github.com/alanfranz/fpm-within-docker  Looks like Alan put a lot of work in it. 

2. >  but seems to mysteriously fail in Alpine

Docker can be quite confusing with different combinations of entrypoint and cmd: 
Your Dockerfile has an ENTRYPOINT written in Shell Form, but no CMD-Command. So CMD will be inherited from the base image, which has a CMD-Command in Exec Form. Differences are explained in https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact and http://www.johnzaccone.io/entrypoint-vs-cmd-back-to-basics/

This combination should result in "/bin/sh -c /mnt/test.sh". As far as i know, Alpine uses almquist shell (ash) as a default shell and this will not change when you install bash. So your BATS-test will be executed by ash, not bash. Untested solutions: 

1. ENTRYPOINT [“/bin/bash", "/mnt/test.sh"]
2. CMD [“/bin/bash", "/mnt/test.sh"] 

Both should work in this case, because the parent image (alpine) has no entrypoint.

**Comment by dmuth** [comment]
Gonna quote you out of order here:

> Docker can be quite confusing with different combinations of entrypoint and cmd:

Oh yeah, I'm aware. :-)  I was actually testing that out interactively, and doing `--entrypoint bash` to bring up an interactive shell and working from there.  BATS still failed mysteriously when running it interactively in Alpine, though.

> Are you aware of this repo? https://github.com/alanfranz/fpm-within-docker

Whoa, I was not!  I just looked through a few distros, and the author has pretty complete coverage for just about everything but Alpine.

[I just opened an issue there](https://github.com/alanfranz/fpm-within-docker/issues/6) and asked if he was interested in some tests for Alpine.

I think, based on that project, I can stop my work on this one and close this issue out--unless you had a different direction in mind?

Thanks,

-- Doug

**Comment by jordansissel** [comment]
> Are you aware of this repo? alanfranz/fpm-within-docker

Very cool!

**Comment by bwaterkamp** [comment]
>  BATS still failed mysteriously when running it interactively in Alpine, though.

Sounds like an interesting thing to debug, but the priority is way to low at the moment. 

> I think, based on that project, I can stop my work on this one and close this issue out--unless you had a different direction in mind?

Not really. fpm-within-docker is an impressive peace of work. You need some time to work through documentation and examples, but that's completely ok for me. This is the only use case i could think of for another Dockerfile/Image: Get started quickly, if you don't need the full build/package/test workflow. But i have no use for this personally. 

Another quick hint: If you need to test more things inside containers, take a look at [inspec](https://inspec.io) . I like BATS for scripts, but inspec takes testing infrastructure things (like DEB/RPM) to the next level and works inside containers without any dependencies. Just switch the target for inspec exec from ssh to docker and run the same tests you use for your vms, to verify you got the same things inside. 

PS: fpm rocks!

**Comment by jordansissel** [comment]
#1818 was merged and should resolve this, in theory. #1818 is a fork of #1682 which added docker pieces and implements this idea to make the fpm usable from docker (testing and using).

`make docker-test-minimal`
`make docker-test-everything`
`make docker-release-minimal`
`make docker-release-everything`

I appreciate y'alls work on this!
