### ISSUE TITLE
FPM install fails on CentOS 7.5 with dependency errors.

### ISSUE THREAD

**Issue by msleevi** [jordansissel/fpm#1497]
When attempting to install fpm on CentOS 7.5 systems, you will run into a dependency error from [ruby-xz](https://rubygems.org/gems/ruby-xz) which dropped a new version (for the first time in 2 1/2 years!) yesterday. That had a requirement of ruby 1.9.3 which was within the standard CentOS packages, however this has been upgraded to 2.3.0 with the most recent release.

CentOS 7.5 is a little behind the game, so I get if this issue gets closed, and I wouldn't want to force the package maintainers into a corner by moving from a free dependency to a versioned dependency, but I thought the issue should be brought up at least.

This is the output from the console on a CentOS 7.5 system.

```
[vagrant@localhost ~]$ sudo gem install --version 1.9.3 --bindir /usr/bin fpm
Fetching: clamp-1.0.1.gem (100%)
Successfully installed clamp-1.0.1
ERROR:  Error installing fpm:
        ruby-xz requires Ruby version >= 2.3.0.
[vagrant@localhost ~]$ ruby --version
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```

Information on the underlying OS.

```
[vagrant@localhost ~]$ cat /etc/*elease
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)
```

There are some steps to circumvent this issue by upgrading ruby ahead of the standard CentOS repositories and I will post those after I get them stable.

**Comment by msleevi** [comment]
There are two reasonable workarounds that I have been able to identify for this.

1. Use `rvm` to install a later version of ruby.

Steps
```bash
# curl -sSL https://rvm.io/mpapis.asc | gpg --import -
# curl -L get.rvm.io | bash -s stable
# source /etc/profile.d/rvm.sh (need to be running as root for this to be in this location)
# rvm reload
# rvm requirements run
# rvm install <version >= 2.3.0 >
# rvm list (check the installed versions)
# rvm use <version installed> --default (if not already selected, see rvm list)
# gem install...
```
[Source](https://tecadmin.net/install-ruby-latest-stable-centos/)

2. Download an external rpm

There is a repository in github defined for them [here](https://github.com/feedforce/ruby-rpm/releases).

```bash
# wget -O <local file> <remote location from repo above>
# rpm -Uvh <local file>
```

I think the `rvm` approach might be more stable given the dependencies ruby has.

**Comment by jordansissel** [comment]
fpm 1.10.0 was released today to fix this. Can you try that?

**Comment by msleevi** [comment]
Like a charm! Thanks @jordansissel!

Feel free to close.

**Comment by jordansissel** [comment]
Woohoo! :)
