### ISSUE TITLE
Unwanted directories added to RPM

### ISSUE THREAD

**Issue by hellosputnik** [jordansissel/fpm#1503]
When creating an RPM from a virtualenv (whether I use -s dir or -s virtualenv), unwanted directories and files are included in the RPM.

I do not specify `/usr/lib/.build-id` anywhere and `--edit` does not show the directories in the spec, but `rpm -qlp output.rpm` shows the directories.

I have tried excluding and disabling dependencies, but nothing prevents those directories from showing up and failing my installations :( Has anyone else run into this issue?

When I try to install the generated RPM, yum complains about conflicts on `/usr/lib/.build-id/$file` from the Python package that contains the virtualenv I used. If I uninstall the Python package, then I can install the FPM package (which is broken because it's missing those necessary Python packages that I uninstalled).

**Comment by hellosputnik** [comment]
I uninstalled the Python package and installed an older version of the same Python package and installation was successful. However, the mysterious files and directories still exist in my RPM.

**Comment by hellosputnik** [comment]
Thanks @daoxxx! I really appreciate your response!

**Comment by daoxxx** [comment]
@hellosputnik You're welcome. Guess you shold close the issue.
