### ISSUE TITLE
Perl CPAN Support, Broken Version match Statement

### ISSUE THREAD

**Issue by wbraswell** [jordansissel/fpm#1514]
There is a problem with a "match" operator, and possibly the surrounding regex or data types or version number checking, not sure on the details yet, working on it now.

```
[wbraswell@MACHINE ~]$ fpm --no-cpan-test --cpan-verbose --verbose --debug-workspace --workdir /home/wbraswell/rperl_packager_tmp/ -t rpm -s cpan Alien::PCRE2
...
Asking metacpan about a module {:module=>"MIME::Base64", :level=>:info}
plugin directory {:plugin=>"cpan", :pathtype=>:build_path, :path=>"/home/wbraswell/rperl_packager_tmp/package-cpan-build-47c2d390986f703bc6eb1bc7413e44eda3b90493c40e48f2241312d9e32e"}
/home/wbraswell/repos_github/fpm-fork-latest/lib/fpm/package/cpan.rb:163:in `block in input': undefined method `match' for 5.004:Float (NoMethodError)
        from /home/wbraswell/repos_github/fpm-fork-latest/lib/fpm/package/cpan.rb:160:in `each'
        from /home/wbraswell/repos_github/fpm-fork-latest/lib/fpm/package/cpan.rb:160:in `input'
        from /home/wbraswell/repos_github/fpm-fork-latest/lib/fpm/command.rb:352:in `block in execute'
        from /home/wbraswell/repos_github/fpm-fork-latest/lib/fpm/command.rb:351:in `each'
        from /home/wbraswell/repos_github/fpm-fork-latest/lib/fpm/command.rb:351:in `execute'
        from /usr/local/share/gems/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /home/wbraswell/repos_github/fpm-fork-latest/lib/fpm/command.rb:574:in `run'
        from /usr/local/share/gems/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /home/wbraswell/repos_github/fpm-fork-latest/bin//fpm:7:in `<main>'
```

The offending line is here:
https://github.com/jordansissel/fpm/blob/master/lib/fpm/package/cpan.rb#L163

**Comment by jordansissel** [comment]
I wonder if this is a bug or weird interaction with the YAML from the perl module? 

Looking at MIME::Base64:

```
% grep '"perl"' module/META.json
            "perl" : "5.004"
% grep perl: module/META.yml
  perl: 5.004
```

Now, in the JSON, "5.004" is a string, but in the YAML, 5.004 is a number, not a string!

I believe we can fix this weirdness by changing the code to force it to be a string:

```diff
-m = version.match(/^(\d)\.(\d{3})(\d{3})$/)
+m = version.to_s.match(/^(\d)\.(\d{3})(\d{3})$/)
```

Interestingly, I can't reproduce your error. when I test it by hand:

```
% bin/fpm --no-cpan-test --cpan-verbose --verbose --debug-workspace -t rpm -s cpan Alien::PCRE2
...
Created package {:path=>"perl-Alien-PCRE2-0.015000-1.noarch.rpm"}
```

I'm not sure I understand how your scenario is failing, but given I can see how `META.yml` can be loaded that the `perl` dependency will appear as a number/float to fpm which will cause this failure for you.

That said, I think we can do this change (making `version` into a string before trying to match it...)

**Comment by jordansissel** [comment]
I'll push a branch. Can you test?

**Comment by jordansissel** [comment]
https://github.com/jordansissel/fpm/pull/1515 is a PR which should fix this. @wbraswell, can you test since I can't reproduce the failure?

**Comment by wbraswell** [comment]
just testing with the problematic Digest input, yes it does seem to work with simply adding the ".to_s" as you have outlined!

**Comment by jordansissel** [comment]
@wbraswell thank you for testing! I'll merge #1515.

I'd like to put out a patch release for this now, but since we ran into this snag, I want to just make one last check to see if you have any other issues before I push a release?

**Comment by wbraswell** [comment]
@jordansissel 
give me about 5 more minutes to finish running my medium-difficulty test, if that looks good then we can push another release

**Comment by wbraswell** [comment]
it works on medium difficulty, 53 RPMs successfully created, looks good!
I say go for it, let's have another release :-)

**Comment by jordansissel** [comment]
Wooo! Thank you much for testing :)

**Comment by jordansissel** [comment]
```
Pushing gem to https://rubygems.org...
Successfully registered gem: fpm (1.10.2)
```

**Comment by wbraswell** [comment]
running high-difficulty tests now, will report any issues
