### ISSUE TITLE
Perl CPAN Support, Frozen cpanm Command, Broken I/O Handling In execmd()

### ISSUE THREAD

**Issue by wbraswell** [jordansissel/fpm#1522]
@liger1978 
Discussion of this issue started here:   https://github.com/jordansissel/fpm/issues/1519

Specifically, these two comments:
https://github.com/jordansissel/fpm/issues/1519#issuecomment-402541298
https://github.com/jordansissel/fpm/issues/1519#issuecomment-402543327

Essentially, this issue causes 2 different negative situations.

First, we can not see any of the output of the `cpanm` commands, including the critically important configure & build processes such as `Makefile.PL` and `Build.PL` and `make` and `gcc` and `as` etc etc.  If I don't know what is happening with `cpanm` then I really have no idea what is happening at all.

Second, we experience an actual freeze/hang during one of the `gcc` and/or `as` commands, as shown in the comments linked above.

I have tracked this problem to one line:
https://github.com/wbraswell/fpm/blob/master/lib/fpm/util.rb#L165
```
if block_given?
```

If I simply replace this line with `if false` then both parts of this issue appear to be solved!  I can now see all the output generated in real time, and the mysterious hanging gcc/as processes no longer hang!  Unfortunately, by doing so I also re-introduce the previous bug 1519, because we need an empty STDIN to be present for any possible interactive processes:
https://github.com/jordansissel/fpm/issues/1519

So, in order to achieve a hybrid solution I actually have to disable all the STDOUT and STDERR parts, while leaving the STDIN parts in tact.  I have done this in my latest commit:
https://github.com/wbraswell/fpm/commit/3171ee9f834ff5e1f6af64b869a67227574689d8

Since I am not familiar with the `execmd()` subroutine and how Ruby handles all the I/O magic, I will not presume that my temporary solution is correct enough to create a pull request.  In fact, I assume this would be a not-entirely-correct solution, and that we need to somehow figure out why the hanging is actually happening in order to create a permanent solution.

**Comment by liger1978** [comment]
I'm not seeing this other issue (CentOS 7).  I've pushed again to https://github.com/liger1978/fpm/tree/1519 which adds the extra required `safesystemin()` calls in `cpan.rb`.

**Comment by wbraswell** [comment]
@liger1978 
This is the command which freezes w/out my hybrid solution:
```
$ fpm --no-cpan-test --cpan-verbose --verbose --debug-workspace --workdir /home/wbraswell/rperl_packager_tmp/ -t rpm -s cpan RPerl
Setting workdir {:workdir=>"/home/wbraswell/rperl_packager_tmp/", :level=>:info}
[[[ DEBUG CHECKPOINT 010 ]]] {:level=>:info}
Asking metacpan about a module {:module=>"RPerl", :level=>:info}
[[[ DEBUG CHECKPOINT 000 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT 001 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT 002 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT 006 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT 007 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT 008 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT 011 ]]] {:level=>:info}
Downloading perl module {:distribution=>"RPerl", :version=>nil, :level=>:info}
[[[ DEBUG CHECKPOINT 012 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT 013 ]]] {:level=>:info}
Setting package name from 'distribution' {:distribution=>"RPerl", :level=>:info}
Installing any build or configure dependencies {:level=>:info}
[[[ DEBUG CHECKPOINT 060 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT, safesystemin(), 100 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT, safesystemin(), 101 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT, safesystemin(), 120 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT, safesystemin(), 121 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT, safesystemin(), 122 ]]] {:level=>:info}
[[[ DEBUG CHECKPOINT, safesystemin(), 123 ]]] {:level=>:info}
***FROZEN HERE***
```
https://github.com/jordansissel/fpm/issues/1519#issuecomment-402543327

**Comment by liger1978** [comment]
What OS are you using? I'll spin up a Docker container running the same as you.

**Comment by liger1978** [comment]
@wbraswell Thanks William. I see you're on CentOS 7 as well. The only difference is that my container is CentOS 7.5. I'm just trying to build your package at the moment.  It's a big one, so it is taking some time! :)

**Comment by wbraswell** [comment]
The place where it freezes due to this issue 1522 is confusing and mysterious:
https://github.com/jordansissel/fpm/issues/1519#issuecomment-402543327
I was not able to figure out even what particular CPAN module was being built when it freezes on `as -I . -I /usr/local/include -I /usr/lib64/perl5/CORE --64 -o XS.o`.
Thankfully, my fix for this issue at least allows me to move forward, even without a full explanation!

**Comment by liger1978** [comment]
@jordansissel I give up with this.  What wbraswell says is correct.  `execmd` is behaving mysteriously.

**Comment by wbraswell** [comment]
@liger1978 
Thanks for trying!  :-)

**Comment by wbraswell** [comment]
As with #1519, this issue is solved by PR https://github.com/jordansissel/fpm/pull/1955 by @NicholasBHubbard, great job everyone! :-)
