### ISSUE TITLE
Perl CPAN Support, Build Binary and/or Source Packages

### ISSUE THREAD

**Issue by wbraswell** [jordansissel/fpm#1526]
Sometimes we need to be able to tell `rpmbuild` to create source packages in the SRPMS directory, either instead of or in addition to the normal binary packages in the RPMS directory.  This is accomplished by passing the `-ba` or `-bb` or `-bs` options to `rpmbuild`.

**Comment by jordansissel** [comment]
This is a pretty dramatic change which could mislead users. FPM cannot build what most folks would consider to be an SRPM. 

Can you show me an example of how this might be used?

**Comment by wbraswell** [comment]
@jordansissel 
Yes you are correct, after working more on this issue I realized that it is not enough to simply pass the `-ba` or `-bb` or `-bs` options to `rpmbuild`, this will essentially create an empty or fake SRPM which can not actually be utilized by users.
I believe I may have a way to properly accomplish the building of SRPM files, possibly without the use of FPM-Cookery, so for now I will leave this issue open and I will eventually come back to report my findings.

**Comment by wbraswell** [comment]
Deprecated in favor of more specific issue:
https://github.com/jordansissel/fpm/issues/1954
