### ISSUE TITLE
Is it possible to specify a minimum version of a dependency with --deb-pre-depends?

### ISSUE THREAD

**Issue by MatthijsM** [jordansissel/fpm#1531]
I have a "util" deb package that provides some bash scripts that I want to utilize in the "run after install" script of a second deb package when I install it using apt-get.  More importantly, I want to make sure that the latest version of the util package is installed.  In a Debian control file I can specify a minimum version of a dependency as follows:

Depends: common-apt (>=180724114914)

Is it possible to do the same with the --deb-pre-depends argument?

When I tried passing the following argument,  I received the errors found at the bottom of the post.

--deb-pre-depends common-apt (>=180724114914)

All flags should be before the first argument (stray flags found: ["--deb-pre-depends"] {:level=>:warn}
Invalid package configuration: Cannot package the path...

**Comment by jordansissel** [comment]
Good question!

Can you try putting your dependency in quotes?

```
--deb-pre-depends "common-apt (>=180724114914)"
```

**Comment by MatthijsM** [comment]
Thanks for the reply Jordan!

Unfortunately that didn't work for me either.  =(  The error I get is:

Invalid package configuration: Cannot package the path '/usr/local/APT/packageSource/secondPackage/local/./(>', does it exist? {:level=>:error}

I only get the "All flags..." error I reported earlier if I also pass a second --deb-pre-depends.  Passing two works fine if I don't attempt to add the version information.

**Comment by jordansissel** [comment]
hmm, can you show your full fpm command line?

**Comment by MatthijsM** [comment]
Here it is (with two deb-pre-depends):

fpm -s dir -t deb -n common-activemq515 -C /usr/local/APT/packageSource/common-activemq515/local --prefix /usr/local -v 180725103616 --after-install /usr/local/APT/packageSource/common-activemq515/run-after-install.sh --before-remove /usr/local/APT/packageSource/common-activemq515/run-before-remove.sh --deb-pre-depends "common-apt (>=180724114914)" --deb-pre-depends "common-jdk8" .

**Comment by MatthijsM** [comment]
I think it might be a problem on my end.  We are building this command in a script and when you asked me for it, I added an echo to the script to get that for you.  When I took the command I posted above and pasted it the terminal and ran it, it ran fine.  We must be losing quotes when we run it within the script.

**Comment by MatthijsM** [comment]
Hi Jordan.  It works now that we call the command using eval!  Thanks for the hint about the quotes.

**Comment by jordansissel** [comment]
Wooo! Glad it's working now :)
