### ISSUE TITLE
Python rpms contain pyc files with invalid timestamps

### ISSUE THREAD

**Issue by dmurnane** [jordansissel/fpm#1538]
When fpm copies files from the python staging dir to the RPM staging dir, it doesn't preserve timestamps, so the timestamp in the pyc files don't match the py files contained in the RPM. This means when you install the RPM and import the package as root, it recompiles the pyc files and the RPM no longer verifies cleanly.

The rpm was generated with
```
fpm -s python -t rpm python-consul
```

```
bash# rpm -qV python-consul
bash# python
Python 2.7.5 (default, Feb 20 2018, 09:19:12) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import consul
>>> 
bash# rpm -qV python-consul
.M5....T.    /usr/lib/python2.7/site-packages/consul/__init__.pyc
SM5....T.    /usr/lib/python2.7/site-packages/consul/base.pyc
.M5....T.    /usr/lib/python2.7/site-packages/consul/std.pyc
```

It looks like setting preserve=true on the copy_entry in lib/fpm/package/rpm.rb creates packages with valid pyc timestamps.

**Comment by gcoxmoz** [comment]
Just chased this one down too.  The .pyc must be newer-than (not equal-in-time-to) the .py.  The copy_entry is dropping in time-equivalent files, so the rpm loses that fpm did a py-compile during build.  This leads to a pyc recompile by the first script invocation that has write perms to the .pyc file (probably root).

OP's 1-liner suggestion in comment 0 is likely good enough for rpm.  I personally don't know/care about wider cases, though they might bear investigating.

**Comment by jordansissel** [comment]
This should be fixed by https://github.com/jordansissel/fpm/pull/1559
