### ISSUE TITLE
[query] Can I install fpm with isolated dependencies?

### ISSUE THREAD

**Issue by kwill** [jordansissel/fpm#1539]
My understanding is that `gem install fpm` will install fpm and dependencies in the same environment as other gem-based installations. I would like to install fpm for immediate use (like gem), but also with isolated dependencies (like bundler). Is this possible?

    foo install fpm
    fpm --version # run fpm command
    foo update fpm # update fpm package
    fpm --version # new version

The only alternative I can think of is:

    git checkout path/to/fpm
    cd fpm
    bundler install
    fpm --version # run fpm command
    git pull # update fpm source
    fpm --version # new version

Related links:

* https://stackoverflow.com/questions/51762303

**Comment by mathieu-aubin** [comment]
@kwill -- Maybe you'd like to get to know [*__Ruby enVironment (Version) Manager (RVM)__*](https://rvm.io) if you don't already.

You can install/use different ruby interpreters and create custom gemsets, tagged to whatever you'd like and use them at will... Almost certainly, if i get the just of your question, you'll be glad to have heard about it.

Check the basics of it explained [here](https://rvm.io/rvm/basics)...

**Comment by kwill** [comment]
Thanks for the hint! I discovered rbenv and managed the following:

```
sudo apt install rbenv
rbenv install 2.4.1
rbenv local 2.4.1 # enter the environment
gem install fpm
fpm --version
rbenv local --unset
```

There may be ways to make rbenv-based gems easier to run (not having to enter/exit the environment), but those are beyond the scope of this query.

**Comment by mathieu-aubin** [comment]
gem install fpm --version 1.10.0
gem install fpm --version 1.10.1
gem install fpm --version 1.10.2
...
~/.rvm/gems/ruby-2.4.4/gems/fpm-1.10.0/bin/fpm --version
~/.rvm/gems/ruby-2.4.4/gems/fpm-1.10.1/bin/fpm --version
~/.rvm/gems/ruby-2.4.4/gems/fpm-1.10.2/bin/fpm --version

... so why not use RVM?

**Comment by kwill** [comment]
Unfortunately RVM isn't yet packaged for Debian (my baseline). For my purposes they are much of a muchness. But thanks again for the suggestion, it pointed me in the right direction!

**Comment by mathieu-aubin** [comment]
curl -sSL https://get.rvm.io | bash -s stable --ruby

This installs rvm no matter what.
