### ISSUE TITLE
Add C/C++ auto dependency for RPM packaging

### ISSUE THREAD

**Issue by http403** [jordansissel/fpm#1591]
It will be nice that fpm can scan the dependencies in ELF binary using tools like `ldd` and automatically add them into RPM dependency list.

http://ftp.rpm.org/max-rpm/s1-rpm-depend-auto-depend.html

**Comment by KantarBruceAdams** [comment]
Does --rpm-autoreq do this?

**Comment by http403** [comment]
Close as stale and not interested anymore
