### ISSUE TITLE
Intelligently autoincrement "iteration" when editing a package.

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#16]
If we are going from deb to deb, or rpm to rpm, the resulting package should use the source package's "iteration" + 1.

**Comment by cheyngoodman** [comment]
I'm manually doing this with bash scripts but think this would be a good native feature.

"If fpm is not helping you make packages easily, then there is a bug in fpm."

When packaging, I want to run the same exact command for packaging to the same location repeatedly, which currently requires an manual / scripted increment which is done external from FPM.

I expected the command below to work twice in a row without error.
```
fpm \
  -s 'dir' \
  -t 'rpm' \
  -n 'packagename' \
  -v '0.0.1' \
  'path/to/dir'
```

But instead returns, `File already exists, refusing to continue: packagename-0.0.1-1.x86_64.rpm {:level=>:fatal}`.

Has there been any more interest in this feature?

Specifically, if `--iteration` is not included, assume auto-iterate. Or if the requested iteration already exists, assume auto-iterate.

**Comment by jordansissel** [comment]
Ooh hmm.. I like this idea. Maybe a new flag to handle it?
—increment-iteration or something?

**Comment by cheyngoodman** [comment]
Sounds appropriate. I'm poking around a bit to see how to add this.

I see the flags in `lib/fpm/command.rb`.

Then the default iteration is set to 1 per `pkgin`, `pacman`, and `rpm` package types.

Other outputs `freebsd`, `solaris` appear to only use iteration if supplied. I'm unsure how `deb` outputs make use of this variable.

fpm already `output_check(output_path)` per package type, I believe if `--auto-iterate` is supplied,
1. Find files in output path dir that match iteration regex
2. Sort files and select latest iteration
3. Use latest iteration + 1 as iteration and continue, or possibly "retry" the build with the new iteration

I need to review, to see if fpm can change iteration and continue or if there's more to it. I believe the `output_check` needs to occur earlier that other instances where iteration may be used.

Is there anything else I'm missing for this feature?
