### ISSUE TITLE
Created RPM package conflicts with file from package filesystem

### ISSUE THREAD

**Issue by scottdwyer** [jordansissel/fpm#1607]
I am creating a RPM package of my own software using FPM. But when installing the package it gives the following conflict:

file /usr/local/share/info from install of mysoftware-1.x86_64 conflicts with file from package filesystem-3.9-2.fc29.x86_64

I updated to the latest 1.11 version of FPM, but the issue persists. It is my understanding that this is caused from the package trying to create existing system directories. What can I do to resolve this?

**Comment by diasjorge** [comment]
Hi, so the package manager won't let you install packages that would overwrite other package's files.

The solution I've used in the past is to keep a copy in my package like. file-to-overwrite.mine and then copy it over using a post install hook. 

E.g:

```
cp /destination/file-to-overwrite /my/package/file-to-overwrite.original
cp file-to-overwrite.mine /destination//file-to-overwrite
```

You could do the reverse on a preuninstall hook too.

**Comment by scottdwyer** [comment]
It isn't overwriting any other files, it is the directory. I do suppose that your workaround could work for me, if I can figure out how to implement it. I just don't think I should have to do a workaround for this.

**Comment by liger1978** [comment]
What is your fpm command line?

**Comment by scottdwyer** [comment]
`fpm -s dir -t rpm -m "$maintainer" -C ./installers/program --name $name --version $version --iteration 1 --depends "$glibdepends $libcver" --description $description --url $url --vendor $vendor --license $license  --before-install program-uninstall.sh`

**Comment by liger1978** [comment]
I don't see a file spec at the end of your command. You are chdiring
into  ./installers/program
with "-C" but then I don't see a list of the files you are packaging at the
end.

**Comment by scottdwyer** [comment]
The folder structure is as follows:
installers/program/usr/local/bin/executable-programgram
installers/program/usr/local/bin/programgram-subfolder/programgram-scripts
installers/program/usr/local/share/applications/destop-config-file
installers/program/usr/local/share/doc/programgram-subfolder/document-files
installers/program/usr/local/share/info/ (empty folder? Hmmmm, this is the one it is catching)
installers/program/usr/local/share/man/man1/programgram-man-file

**Comment by scottdwyer** [comment]
Dang, that was it, the empty folder. I would not have expected that, but I guess I understand why it could happen. Since there was nothing in the folder, it thought that the folder was what it was supposed to create, which conflicted with the fact the folder already existed and was owned by the filesystem. Lesson learned. Case solved and closed.

**Comment by jordansissel** [comment]
rpm makes certain file ownership aspects kind of confusing, and fpm doesn't do a great job of surfacing that. :\

You might be successful in using `--no-rpm-auto-add-directories` flag to your `fpm` invocation and that should tell fpm to not declare the directories in the package.

**Comment by scottdwyer** [comment]
My issue was resolved by removing the empty directory from the installation source. However, for future reference, I am curious about the `--no-rpm-auto-add-directories` option. I do have sub-directories that get added. Would this option cause them to not be added by the RPM installer? When using this option, would I need to create the sub-directories with a before-install script? Just curious how the option works, as I could not find any documentation on it.
