### ISSUE TITLE
fpm not found even after successful installation 

### ISSUE THREAD

**Issue by Ahmedshabaz06** [jordansissel/fpm#1613]
Successfully installed fpm-1.11.0
Parsing documentation for fpm-1.11.0
Installing ri documentation for fpm-1.11.0
Done installing documentation for fpm after 0 seconds
1 gem installed

--
$ fpm --version
-bash: fpm: command not found
-------------
Appreciate any quick help
This is on Mac OS

**Comment by mathieu-aubin** [comment]
look for an executable named fpm using find. i assume all the stuff installed is within your home (i am not familiar with macos tho so change the search path accordingly)

    find ~/ -type f -name 'fpm' -executable

Then, check your path and make sure it contains the location of the found executable

hopefuly it helps

**Comment by Ahmedshabaz06** [comment]
I did add the path, but it doesn't output when I type $PATH but when I cat the file I can see the Path for the bin, al though it works when I source the bash_profile and run the same command.

**Comment by DEHughes** [comment]
Same issue
$ fpm --version
-bash: fpm: command not found

If I use the full path I get:

/usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/bin/fpm --version
Traceback (most recent call last):
        5: from /usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/bin/fpm:4:in `<main>'
        4: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from /usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/lib/fpm.rb:14:in `<top (required)>'
        1: from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/lib/fpm/package/python.rb:151: syntax error, unexpected ']' (SyntaxError)
...n headers, s.string[s.pos ... ]
...                              ^
/usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/lib/fpm/package/python.rb:155: syntax error, unexpected ']'
...n headers, s.string[s.pos ... ]
...                              ^
/usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/lib/fpm/package/python.rb:169: syntax error, unexpected ']'
      puts input[s.pointer...]
                             ^

**Comment by DEHughes** [comment]
find ~/ -type f -name 'fpm' -executable
Does not find anything.

**Comment by mathieu-aubin** [comment]
> find ~/ -type f -name 'fpm' -executable Does not find anything.

just widen your search, as i mention you might need to change the path to search. Use the entire drive if you must, i only used the home path as an example because i thought that's where macos users installed their stuff in

**Comment by DEHughes** [comment]
I did, and I found it at: /usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/bin/fpm.

But /usr/lib64/ruby/gems/2.5.0/gems/fpm-1.17.0/bin/fpm --version gives the traceback above with the Syntax errors.

I also have: /usr/bin/fpm.ruby2.5 that is commented with:

> cat fpm.ruby2.5
#!/usr/bin/ruby.ruby2.5
#
# This file was generated by RubyGems.
#
# The application 'fpm' is installed as part of a gem, and
# this file is here to facilitate running it.
#

Running this gives the same syntax error as above.
