### ISSUE TITLE
feature proposal: allow alternative prefix options to choose existing directory on customer site

### ISSUE THREAD

**Issue by mlakes-sigsci** [jordansissel/fpm#1617]
This is in regards to the --prefix option which allows specifying target install directory.
This is great for most of our cases, but we have encountered case where customer installs to completely non standard directory.
It would be useful if we could specify alternative target directory as well, whereby pkg will choose the directory that **exists** on the customer host.
Example: 
fpm --prefix /usr/local/libexec/trafficserver --alt-prefix /elsewhere/usr/local/libexec/trafficserver

For most customers, --prefix would take affect
For "special" customers, --alt-prefix would take affect

Note: I dont know if this could even be supported by yum or deb, etc

**Comment by josegonzalez** [comment]
As far as I know, that's not really how most package managers support things. It's more of an "extract" to a known path, without a custom prefix.

For your "special" customers, it may be worth creating special binaries for them and allowing them to install from those binaries. You could even build this into your enterprise pricing :D

**Comment by mlakes-sigsci** [comment]
Answer is accepted.
