### ISSUE TITLE
Trying to package librdkafka can't find setup.py

### ISSUE THREAD

**Issue by chicks-net** [jordansissel/fpm#1618]
Howdy folks,

I'm trying to package [`librdkafka`](https://github.com/edenhill/librdkafka) but it doesn't seem to follow the expected format for a python package:

```
$ fpm -s python -t deb librdkafka/
Could not find 'setup.py' {:path=>"librdkafka/setup.py", :level=>:error}
/usr/share/gems/gems/fpm-1.10.2/lib/fpm/package/python.rb:101:in `input': Unable to find python package; tried librdkafka/setup.py (RuntimeError)
        from /usr/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:352:in `block in execute'
        from /usr/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `each'
        from /usr/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:351:in `execute'
        from /usr/share/gems/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /usr/share/gems/gems/fpm-1.10.2/lib/fpm/command.rb:574:in `run'
        from /usr/share/gems/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /usr/share/gems/gems/fpm-1.10.2/bin/fpm:7:in `<top (required)>'
        from /usr/bin/fpm:23:in `load'
        from /usr/bin/fpm:23:in `<main>'
```

**Comment by chicks-net** [comment]
I couldn't find anything in the docs that would hint at what to do for a python module that is missing the `setup.py`.

**Comment by jordansissel** [comment]
I've never used librdkafka, but judging from the project's README, this appears to be a C/C++ library. The Python library that uses it appears to be https://github.com/Parsely/pykafka -- and you should be able to do `fpm -s python -t deb pykafka` (note: this may require librdkafka to be installed locally while building)

**Comment by chicks-net** [comment]
I was definitely confused.  Thanks Jordan for pointing out what I was missing here.

**Comment by jordansissel** [comment]
@chicks-net Glad we could team up and get you on the path to success :)
