### ISSUE TITLE
Debian package using non-gzip compression are broken

### ISSUE THREAD

**Issue by ayufan** [jordansissel/fpm#1647]
It seems that using fpm 1.11.0 is broken unless `--debian-compression` gzip is used. It seems to produce control.tar.gz in a format that is defined by `debian-compression` instead of using gzip as extension states.

This seems to be using `control.tar.gz` as a filename instead of `controltar`: https://github.com/jordansissel/fpm/blob/v1.11.0/lib/fpm/package/deb.rb#L800

**Comment by thekvs** [comment]
I confirm this issue. Any news when it might be fixed?

**Comment by jordansissel** [comment]
Thank you for confirming :)

From the description, I think there’s probably enough information for
someone to begin working on a fix. I don’t have any estimate.
