### ISSUE TITLE
How to configure the format used in FPM::Package::Deb.to_s?

### ISSUE THREAD

**Issue by Rylon** [jordansissel/fpm#1659]
Hi @jordansissel 

We've encountered an unusual issue with the Debian Epoch being missing from the resulting .deb filename. Although the Deb package type supports epoch, when the filename is generated via `.to_s()`, it is not included in the default format, which I can see is determined here:

https://github.com/jordansissel/fpm/blob/master/lib/fpm/package/deb.rb#L1043-L1047

I can see that this method supports passing in a format, defaulting to:
`"NAME_FULLVERSION_ARCH.EXTENSION"`.

We'd like to change it to match the Debian packaging spec:
`"NAME_EPOCH:FULLVERSION_ARCH.EXTENSION"`.

Is it possible to set this via some mechanism, or do we need to monkey patch?

Behind the scenes we're using `fpm-cookery` and monkey patching in the recipe does work, but feels wrong :D 

Thanks for your time :)

**Comment by jordansissel** [comment]
From the API you can choose the output name with the .output(...) method,
iirc.

From the CLI, you can choose this with the ‘-p’ flag.

(I’m on my phone so it’s hard to verify — lemme know if either of these
works.)

**Comment by Rylon** [comment]
Thanks @jordansissel yeah that should work too, however we were hoping to generate the format automatically based on the metadata, rather than specifying it statically. The only thing wrong with the default pattern (for `.deb` at least) is the filename excludes the `epoch`, which means we'd replace an existing package with a different epoch.

**Comment by jordansissel** [comment]
Pkg.to_s(...) will let you name based on metadata.

pkg.output(pkg.to_s(“NAME...EPOCH...”))

**Comment by Rylon** [comment]
Thanks Jordan, I'm going to close this as I think the issue is how exactly to pass this through from FPM Cookery, and I already opened a separate issue there :)

Thanks!
