### ISSUE TITLE
Implement in Go

### ISSUE THREAD

**Issue by mcandre** [jordansissel/fpm#1684]
Could we reimplement fpm in Go in order to shrink the software stack required to run fpm?

**Comment by josegonzalez** [comment]
Sure, anyone could do this - in fact, there is such a project [here](https://github.com/goreleaser/nfpm).

However, given the backlog of issues/prs in this project, I don't think it's feasible for us to rewrite this in golang. If you find something like `nfpm` useful, I definitely recommend contributing to that project to make it a viable competitor to fpm.
