### ISSUE TITLE
Building proper source rpms?

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#17]
From BayLISA last night -

Some folks really like srpms. It would be awesome if fpm could produce these.

This will likely require the 'fpm build recipe' stuff lusis and I have been discussing, where you have a tool similar to freebsd ports, gentoo ebuild, or homebrew, that knows how to download, version, and build things (so we can put them in the rpm spec).

**Comment by 7AC** [comment]
Shouldn't the `%{SOURCERPM}` attribute be empty then?

**Comment by jordansissel** [comment]
@7AC in the built rpm? Hmm.. I suppose. I never looked at that tag/macro so I wasn't aware of it. Can you show me what you mean?

**Comment by 7AC** [comment]
The `SOURCERPM` tag is set to something that doesn't exist. It would be great to generate the SRPM as well, but without it knowing there isn't one would help work around it in my scripts.

```
> rpm -qp --qf='%{SOURCERPM}\n' built-with-fpm.i686.rpm 
built-with-fpm-1.0.0-1.src.rpm
> yumdownloader --source built-with-fpm
No Match for argument built-with-fpm
```

**Comment by jordansissel** [comment]
Interesting. I don't know how to remove that tag/field from the rpm, but I agree with you that fpm should remove that information, if possible.

**Comment by bby-bishopclark** [comment]
> You should put all of those steps into a reusable script. You should share that script. Building an SRPM? Not as awesome. Not as sharable. not as readable.

The SRPMs you've seen don't have the SPEC file encapsulated in the archive in well-preserved state that's trivially easily to parse?  The ability to share an SRPM (or archive it) seems to have been pretty important, and I've done just that - repeated a build and shared a build script - both with new ones and one more than a decade old.
