### ISSUE TITLE
--config-files should recurse if argument is a directory

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#171]
It should be as easy as `--config-files etc/myproject`

**Comment by dkorel-copperleaf** [comment]
I must be missing something here. My understanding is that `--config-files` marks a file (in the package, or filesystem, or both?) as being a config file. This implies - leave the file alone. Don't delete it when the application is removed. When i remove the package, the config file is gone. This is not the behavior i want - i want to be able to install and preserve a file from removal. How can i achieve this?
