### ISSUE TITLE
[QUESTION] Is FPM maintained any longer?

### ISSUE THREAD

**Issue by weakcamel** [jordansissel/fpm#1712]
First of all, let me thank you for FPM. It is a great project and I absolutely appreciate all the hard work and effort put in it by the author and all contributors!

I couldn't help but notice that there is a growing backlog of issues and PR in this repository. Last release 1.11.0 happened in February 2019. Usually that's a sign that the project maintainer is no longer able to actively work on it (be it for personal or professional reasons) which is absolutely understandable in OSS world.

What I wanted to ask is the plans for FPM: is it reasonable to assume that FPM will no longer be maintained in its current form? Is it useful to be raising new issues at this point or is it just adding more unecessary noise?

Knowing that will let the users (me included of course :-)) make an informed decision whether to use it, not use it or consider a fork of it.

Thank you in advance.

**Comment by weakcamel** [comment]
Stumbled across related issue from a year ago: https://github.com/jordansissel/fpm/issues/1653

**Comment by jordansissel** [comment]
I don’t have much time lately to dedicate to this project. FPM is fairly
stable, and though there are bugs to fix, if there is a particular change
you need, filing an issue specific to that bug/issue would be a great next
step.

That said, I welcome contributions (patches, testing/evaluating PRs, docs
improvements, bug reports, etc).

**Comment by weakcamel** [comment]
@jordansissel Many thanks for the reply. It's really good to know that this project isn't quite end of life then.

I'll go ahead and raise the issue then and as it's related to `sh`, I may be able to provide a patch - unfortunately, I'm not a Ruby developer so can't be of much help with the core.

**Comment by truckingsim** [comment]
@jordansissel would it be possible to do a release for loosening up the JSON versions?

You mentioned doing one when you merged the pr: https://github.com/jordansissel/fpm/pull/1600 but there is now a vuln in JSON <2.3.0.  

The fix is in master just not the latest release and would be great to get one with that fix.

**Comment by weppos** [comment]
> @jordansissel would it be possible to do a release for loosening up the JSON versions?
> 
> You mentioned doing one when you merged the pr: #1600 but there is now a vuln in JSON <2.3.0.
> 
> The fix is in master just not the latest release and would be great to get one with that fix.

I agree, that would be really appreciated :)

**Comment by jordansissel** [comment]
I’ll see about doing a release soon.

**Comment by jordansissel** [comment]
Since my last comment, several fpm versions have been released :)

> @jordansissel would it be possible to do a release for loosening up the JSON versions?

#1950 will remove the `json` dependency which should help 👍

**Comment by jordansissel** [comment]
One small pitch before I close this since I think this answered the question --

I'm available for hire to consult on your fpm usage and improve your investment in using fpm by adding new tests based on your use of fpm. If that is of interest to you, please let me know  -- jls@semicomplete.com
