### ISSUE TITLE
gem version 1.11.0 requires json gem version < 2.0, please release new fpm gem version

### ISSUE THREAD

**Issue by skaes** [jordansissel/fpm#1741]
The json gem version requirement has already been relaxed on master, but no new gem has ben built and released on rubygems.org.

As far I know, all 1.x json gems have security issues, so we constantly get warnings about using insecure json gems.

It would help us quite a bit if you could a release a new gem version from the current master.

**Comment by jordansissel** [comment]
#1950 removes the `json` dependency and should fix this.

**Comment by jordansissel** [comment]
fpm 1.15.0 is released and, I believe, has resolve this issue.
