### ISSUE TITLE
1.12 seems to have broken --before-upgrade and --after-upgrade

### ISSUE THREAD

**Issue by toran414** [jordansissel/fpm#1750]
We have a build using these flags, and after upgrading fpm to 1.12 the build started failing.  If I revert to 1.11, or just remove these two flags from the build it works fine.

Error message:
`Process failed: rpmbuild failed (exit code 1). Full command was:["rpmbuild", "-bb", "--target", "noarch", "--define", "buildroot /tmp/package-rpm-build-06b8fa1624894ee4291366ab54c0ecea4b49cc64c8cc61f9103a9f411ef9/BUILD", "--define", "_topdir /tmp/package-rpm-build-06b8fa1624894ee4291366ab54c0ecea4b49cc64c8cc61f9103a9f411ef9", "--define", "_sourcedir /tmp/package-rpm-build-06b8fa1624894ee4291366ab54c0ecea4b49cc64c8cc61f9103a9f411ef9", "--define", "_rpmdir /tmp/package-rpm-build-06b8fa1624894ee4291366ab54c0ecea4b49cc64c8cc61f9103a9f411ef9/RPMS", "--define", "_tmppath /tmp", "/tmp/package-rpm-build-06b8fa1624894ee4291366ab54c0ecea4b49cc64c8cc61f9103a9f411ef9/SPECS/file-mover.spec"] {:level=>:error}`

**Comment by x-lll** [comment]
Same problem
OS: Centos7
Installing from
```yaml
    - curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    - curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    - curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
    - curl -L get.rvm.io | bash -s stable
    - source /etc/profile.d/rvm.sh
    - rvm reload
    - rvm requirements run
    - rvm install 2.3.0 -j 50
    - rvm list
    - gem install --no-ri --no-rdoc fpm
    - fpm --version
```
Execute: fpm -s dir -t rpm -n apps \
      -v $(cat /opt/apps/version.json | jq -r '"\(.maj).\(.min).\(.bld)"') \
      -C /opt/apps/  --prefix /opt/apps/ --verbose \
      --after-install /opt/apps/after-install \
      --before-remove /opt/apps/before-remove \
      --before-upgrade /opt/apps/before-upgrade \
      --description "app"

Error: :message=>"error: line 72: Too many names: %pre upgrade()

**Comment by thomas-pean** [comment]
The same for me : Centos 7, RPM packaging, --before-upgrade --after-upgrade flags
The same command was OK on the 1.11 version.

**Comment by jovandeginste** [comment]
The changes in 8a40cd1db7c6b36ef04300339fa36b15cdeb67ca eat too much whitespace:

```
 %pre <% if attributes[:rpm_macro_expansion?] -%><%= " -e " %> <% end -%>
```

When no `rpm_macro_expansion` is set, all whitespace (including newlines) after `%pre` are eaten, and thus results in:

```
%pre upgrade() {
```

It should be (and was, prior to v1.12.0):

```
%pre
upgrade() {
```

**Comment by jovandeginste** [comment]
(Same for the other macro's: `post`, `preun`, `postun`)

**Comment by jovandeginste** [comment]
After some testing, I believe the final `-%>` should just be `%>`, which would result in:

```
%pre -e
upgrade () {
```

Can anyone confirm?

**Comment by ola-pt** [comment]
I have seen the same error message as well after attempting to use `--after-upgrade`:
`error: line 80: Too many names: %post upgrade() { {:level=>:info}
 {:level=>:info}
Process failed: rpmbuild failed (exit code 1). Full command was:["rpmbuild", "-bb", "--define", "buildroot /tmp/package-rpm-build-7f32c223fd3a13bcd12aaded5d048e5620510231a297cd5d7fe85b5c51a8/BUILD", "--define", "_topdir /tmp/package-rpm-build-7f32c223fd3a13bcd12aaded5d048e5620510231a297cd5d7fe85b5c51a8", "--define", "_sourcedir /tmp/package-rpm-build-7f32c223fd3a13bcd12aaded5d048e5620510231a297cd5d7fe85b5c51a8", "--define", "_rpmdir /tmp/package-rpm-build-7f32c223fd3a13bcd12aaded5d048e5620510231a297cd5d7fe85b5c51a8/RPMS", "--define", "_tmppath /tmp", "--sign", "/tmp/package-rpm-build-7f32c223fd3a13bcd12aaded5d048e5620510231a297cd5d7fe85b5c51a8/SPECS/pt-php-fpm.spec"] {:level=>:error}
`
I have not tried your fix @jovandeginste I can try it later today
