### ISSUE TITLE
Remove rexml - rexml broken in Ruby versions below 2.3

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1800]
Another game to play just like #1795. This time, it's `rexml`.

`rexml` is a direct dependency in fpm and is used by only one place, `osxpkg.rb`

https://github.com/jordansissel/fpm/blob/master/lib/fpm/package/osxpkg.rb#L107

It looks like this code is only used when `fpm -s osxpkg ...` (using an osx package as source/input to fpm).

I'm guessing we can probably remove `rexml` and parse the xml ourselves without a library.

https://github.com/jordansissel/fpm/blob/dbd8bafb5d057af7808e29d1df2302c42d79eb0b/lib/fpm/package/osxpkg.rb#L108-L110

It's used to grab the attributes from what looks like `<pkg-info identifier="..." version="...">` element.

Reference: #1784 and #1798

**Comment by rubyFeedback** [comment]
Good old XML ... may it rest in peace.

(I stopped using XML already in 2005 or so, at the least for my own projects. YAML replaced my personal needs in this regard.)

**Comment by jordansissel** [comment]
#1950 should fix this by moving delaying the loading of rexml and only using that library when attempting to read a macOS `.pkg` file.

**Comment by jordansissel** [comment]
#1950 is merged. Closing this :)

**Comment by jordansissel** [comment]
fpm 1.15.0 is released and, I believe, has resolve this issue. Please let me know if you find otherwise in a new issue (if a new problem) or this issue (if same problem)
