### ISSUE TITLE
How fpm builds the arch64 rpm package？

### ISSUE THREAD

**Issue by kahose** [jordansissel/fpm#1802]
![image](https://user-images.githubusercontent.com/82327413/124536296-529e8a00-de4a-11eb-871c-2fcf0cf69e49.png)
As shown in the figure, I want to package it out to be arch64 instead of x86

**Comment by jordansissel** [comment]
You can set the package architecture with the ‘-a’ flag. For example `-a
aarch64` — let me know if this helps :)

**Comment by kahose** [comment]
Thanks, this is useful

**Comment by jordansissel** [comment]
One other note: if you package is not architecture specific, you can use ‘-a all’ to declare your package doesn’t have any architecture limitations.

For example, if your package is purely python, this doesn’t have any architecture-specific code, so you could use this setting.

**Comment by kahose** [comment]
This is so cool
