### ISSUE TITLE
Nochroot option in spec file for rpm packages

### ISSUE THREAD

**Issue by Friedrich42** [jordansissel/fpm#1805]
I can't find how to add --nochroot to spec file for rpm package. Is there any argument I can pass to add it?

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/installation_guide/s1-kickstart2-postinstallconfig

**Comment by ipbeegle** [comment]
If you look at the [template](https://github.com/jordansissel/fpm/blob/master/templates/rpm.erb#L159) that FPM uses for generating the RPM spec file, it doesn't support adding the `--nochroot` option. You'd have to modify the template on your system to include the option you want, or build your RPM using another tool.

**Comment by jordansissel** [comment]
I can’t get that page to load on mobile (something keeps popping up over
the content and closing it makes it come back)

It’s possible a feature needs to be added to fpm to support this. I’ll try
to read it on a non-mobile device later.

**Comment by Friedrich42** [comment]
@jordansissel You can also check pdf version (32.7. Post-installation Script)
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/pdf/installation_guide/Red_Hat_Enterprise_Linux-6-Installation_Guide-en-US.pdf

**Comment by Friedrich42** [comment]
@ipbeegle Thank you for the hint! I'll do it on my system, but it would be nice feature to add these parameters to fpm

**Comment by ipbeegle** [comment]
@Friedrich42 No worries!

@jordansissel Yeah you're right about adding an option. Adding all of the supported options for RPM spec file scriptlets might be a bit much, but maybe something like `--rpm-post-override-options="--nochroot"` or something. This could cause confusion with the `--rpm-macro-expansion` flag though.
