### ISSUE TITLE
Use pip by default, if possible.

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1820]
fpm has supported `pip` for a while as an optional alternative to `easy_install`. I'm not sure if easy_install is even available anymore on newer Python installations, and pip seems to be the recommended/default way to install python packages.

Objective: fpm should now try to use `pip` if it is available and fall back to `easy_install` if needed.

I don't know what negative impact this might have.

easy_install has been [deprecated since 2019 ](https://setuptools.readthedocs.io/en/latest/history.html#v42-0-0), per the python setuptools release notes:

> Breaking Changes
> ... Mark the easy_install script and setuptools command as deprecated

On my workstation, a recent-ish install of Ubuntu 18.04, easy_install isn't installed for me when installing Python. I don't even see it available in `apt search easy_install`. Pip, however, is available as an Ubuntu `python-pip` package.

Supporting Links:
* https://packaging.python.org/discussions/pip-vs-easy-install/
* https://setuptools.readthedocs.io/en/latest/history.html#v42-0-0

Related: https://github.com/jordansissel/fpm/issues/1780

**Comment by jordansissel** [comment]
Tonight, we found a way to invoke pip using `python -m pip <command line>` and it works nicely! for both Python 2 and 3. Nice!

**Comment by rubyFeedback** [comment]
I am using mostly ruby but also python. pip sort of IMO is the default nowadays. I batch-install python addons via a ruby gem most of the time but when I am lazy, or on windows, pip really is great. I don't even remember easy_install anymore to be honest...
