### ISSUE TITLE
Debian versioned provides allows invalid version strings

### ISSUE THREAD

**Issue by pteichman** [jordansissel/fpm#1825]
Hi folks, I've been specifying `--provides 'foo (<< 1.0.0-54)'` for quite a while, but fpm only recently started passing through the version string ( #1788 #1803 ).

My `<<` inequality is broken: dpkg only allows exact version Provides with `=`. If fpm checked for that, I would have caught the error at build time rather than install time. I don't know if policy enforcement like that is considered one of fpm's responsibilities, but heads up if so. Thanks!

Ref: https://www.debian.org/doc/debian-policy/ch-relationships.html#id9

**Comment by jordansissel** [comment]
Thanks for this report! I had wondered if anything would be accidentally
broken by the recent change to pass through the provides value.

I am in favor of having fpm report an error for invalid Debian provides
fields because fpm should help you make a correct package, and in this
case, it created an incorrect one.

**Comment by jordansissel** [comment]
Copying and quoting Debian's manual here for posterity, citing from https://www.debian.org/doc/debian-policy/ch-relationships.html#id9 as noted above --

> The relations allowed are <<, <=, =, >= and >> for strictly earlier, earlier or equal, exactly equal, later or equal and strictly later, respectively. The exception is the Provides field, for which only = is allowed.

Nice. So only `=` is allowed. I think we can have fpm report an error if we try any other operators.

**Comment by jordansissel** [comment]
I forgot to mention this in the commit, but https://github.com/jordansissel/fpm/pull/1829 fixes this and adds test coverage to keep it working :)

**Comment by pteichman** [comment]
Excellent, thanks a ton!
