### ISSUE TITLE
Feature Request: provide an intended path to an original path

### ISSUE THREAD

**Issue by vacy** [jordansissel/fpm#1837]
Hello and thank you for this amazing project, it eases my workflows so much!!
And especially those Project Principles were inspiring for me :)

I got a feature request that would come in handy for my small lab.
I create RPMs this way:

`fpm -s dir -t rpm -n pkgname -v 1.0 /root/bin/script`

Would be neat being able to tell fpm that the file i hand over should be packaged as another path.
e.g. like this:
`fpm -s dir -t rpm -n pkgname -v 1.0 /original/path/file:/intended/path/file`
`fpm -s dir -t rpm -n pkgname -v 1.0 /root/bin/git/bin/script:/root/bin/script`

**Comment by jordansissel** [comment]
I'm glad you mentioned, because I just looked at the latest docs vs the current release docs and I found a bunch of stuff missing. I'll open an issue to figure out what was removed/replaced to fix it before the next release. <3

**Comment by vacy** [comment]
awesome :)
