### ISSUE TITLE
Reject invalid version strings for debian packages.

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1847]
While writing docs tonight, I found that fpm can create a debian package with an invalid version string.

```
% fpm -s empty -t deb -v "v1.2.3" -n example
Created package {:path=>"example_v1.2.3_amd64.deb"}

% dpkg --field example_v1.2.3_amd64.deb Version
dpkg-deb: error: parsing file '/tmp/dpkg-deb.AlPRzj/control' near line 2 package 'example':
 'Version' field value 'v1.2.3': version number does not start with digit
```

**Comment by mthbrown** [comment]
Just ran into this as well

**Comment by jordansissel** [comment]
Based on #1968 and this issue, I'd like two behaviors:

1. If the version string is something like 'v1.2.3' then fpm should drop the 'v' and use '1.2.3' for the version field
2. Excluding the item above, if it's an invalid version string, fpm should log an actionable error message and exit with failure.

Item 1 (vX.Y.Z) should help with automatic versioning that some folks do with Git tags where a release is tagged vX.Y.Z for a version number.
