### ISSUE TITLE
packaging deb using 1.14.0 leads to a NameError

### ISSUE THREAD

**Issue by kares** [jordansissel/fpm#1854]
namely `NameError: uninitialized constant FPM::Package::CPAN` (compared to version 1.13.x)

due the use of the [`FPM::Package::CPAN`](https://github.com/jordansissel/fpm/blob/v1.14.0/lib/fpm/package/deb.rb#L680) from https://github.com/jordansissel/fpm/commit/13621c97229ee66b17e99ec0ecb765e1f0511fc7 (in the `FPM::Package::Deb` class)

trying to use `require "fpm/package/deb"` one needs to these extra "seemingly unrelated" requires:
```ruby
require "fpm/package/gem"
require "fpm/package/cpan"

require "fpm/package/deb"
...
dir.convert(FPM::Package::Deb)
```
(likely a similar limitation exists for `FPM::Package::Rpm` -> `require "fpm/package/gem"`)

**Comment by jordansissel** [comment]
Thanks for trying the new version!

That’s odd.. is this for Logstash (which I think invokes fpm using the Ruby
api)? I don’t get this error using the cli.

Should be an easy fix and I’ll get this fixed shortly.

**Comment by jordansissel** [comment]
```
% bundle exec ruby -r./lib/fpm/package/deb.rb -e 'FPM::Package::Deb.new.convert(FPM::Package::Deb)'
/home/jls/projects/fpm/lib/fpm/package/deb.rb:680:in `converted_from': uninitialized constant FPM::Package::CPAN (NameError)
```

Reproduced via api

**Comment by jordansissel** [comment]
I'm on the fence about the "best" solution here. Added `require` is simple, but maybe checking the type as a string instead of a const...

**Comment by jordansissel** [comment]
fpm 1.14.1 pushed which has (hopefully) fixed this. Can you try?

**Comment by jsvd** [comment]
Confirmed it works now, thanks for the super fast fix <3
