### ISSUE TITLE
virtualenv shebang path length relocation issues

### ISSUE THREAD

**Issue by jdratlif** [jordansissel/fpm#1874]
When using `-s virtualenv`, fpm creates a temp directory for the venv that is very long (over 80 characters).

Recent versions of pip (not sure how recent -- I know version 9 from CentOS 7 doesn't do this, but version 20 and 21 both do), recognize when the shebang path is too long. When they create console scripts, rather than being a standard python script, they wrap the python in a bash script that calls exec. This isn't fixed by virtualenv-tools, so the path doesn't get fixed and the scripts don't work when deployed by the RPM.

I'm not sure where best to fix this. I reported this to the virtualenv-tools3 project, and I'm hoping they fix it and this becomes moot. In the meantime, I've patched my version of fpm 1.14.1 with sed.

This changes line 267 of package.rb to use ::Dir.mktmpdir() instead of Stud::Temporary.directory.
`sed -i -E -e  '267s/Stud::Temporary.directory\(\"package-#\{type\}-build\"\)/::Dir.mktmpdir()/' package.rb`

This is not perfect, as it only buys some more space. This is why I have not submitted this as a pull request, because it's just a hack.

I'm not sure how to fix this properly. I don't know if there is a better shorter method for the temp directory, or if there is some way to tell pip (or maybe setuptools -- i'm not sure what's creating the bash wrapper) to stop doing this.

This is the issue I opened on virtualenv-tools3.
https://github.com/Yelp/virtualenv-tools/issues/26

Thanks for any assistance.

This is a way to demonstrate the issue:

```bash
fpm -s virtualenv -t rpm --name my_apps_venv -v 1.2.3 --prefix /usr/share/my_org/my_app_name/venv requirements.txt
```

Here is requirements.txt

```
asgiref==3.4.1
click==8.0.3
dataclasses==0.8
h11==0.13.0
importlib-metadata==4.8.3
typing_extensions==4.0.1
uvicorn==0.16.0
zipp==3.6.0
```

After installation, I get this script `/usr/share/my_org/my_app_name/venv/bin/uvicorn`:

```
#!/bin/sh
'''exec' /tmp/package-virtualenv-build-3dd05a4275124c5f1696ca844877ed4ce3932e6c0c6cdfff9972b048ddaf/usr/share/my_org/my_app_name/venv/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from uvicorn.main import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by jkugler** [comment]
I just got bitten by this bug as well.

**Comment by jdratlif** [comment]
This should work if you have virtualenvtools3 3.1.0 or later as this behavior has been patched now.
