### ISSUE TITLE
document more available packaging types

### ISSUE THREAD

**Issue by mcandre** [jordansissel/fpm#1884]
The documentation claims support an an exceptionally wide variety of packaging types. However, the page listing the syntax for the types omits most of them.

> fpm is a tool which lets you easily create packages for Debian, Ubuntu, Fedora, CentOS, RHEL, Arch Linux, FreeBSD, macOS, and more!

https://fpm.readthedocs.io/en/latest/index.html

versus

> cpan deb dir empty npm rpm

https://fpm.readthedocs.io/en/latest/packaging-types.html

**Comment by jordansissel** [comment]
Hi! 

I also would like more types included in that list. Some small history here is that part of #1838 and #1839 added more detailed examples and dedicated documentation for a few package types -- mostly as a first step towards more comprehensive per-type package documentation. I haven't had energy to write additional examples.

As an easier next step, we could have all package type docs with only the flag documentation, such as this flag section for cpan: https://fpm.readthedocs.io/en/v1.14.1/packages/cpan.html#cpan-specific-command-line-flags

I'll see what I can do.

**Comment by jordansissel** [comment]
```
% ls lib/fpm/package/*.rb | fex /-1.1 | sort | xargs -n1 sh -c 'if [ -f "docs/packages/$1.rst" ] ; then echo "✅ Found d
ocs for $1"; else echo "❌ missing per-package docs for $1"; fi' -
❌ missing per-package docs for apk
✅ Found docs for cpan
✅ Found docs for deb
✅ Found docs for dir
✅ Found docs for empty
❌ missing per-package docs for freebsd
❌ missing per-package docs for gem
✅ Found docs for npm
❌ missing per-package docs for osxpkg
❌ missing per-package docs for p5p
❌ missing per-package docs for pacman
❌ missing per-package docs for pear
❌ missing per-package docs for pkgin
❌ missing per-package docs for pleaserun
❌ missing per-package docs for puppet
❌ missing per-package docs for python
✅ Found docs for rpm
❌ missing per-package docs for sh
❌ missing per-package docs for snap
❌ missing per-package docs for solaris
❌ missing per-package docs for tar
❌ missing per-package docs for virtualenv
❌ missing per-package docs for zip
```

For each missing type, we can create a single file as `docs/packages/<name>.rst` and put some kind of boilerplate that includes the CLI doc page.

Further steps would be to add the `Supported Uses in FPM` section and any other content, depending on energy and expertise available.

**Comment by jordansissel** [comment]
fpm v1.14.2 released that includes an improvement for this issue. https://fpm.readthedocs.io/en/stable/packaging-types.html

Example screenshot from the sidebar:

![image](https://user-images.githubusercontent.com/131818/160998679-0b710241-6c6d-401b-b685-5e511465f59e.png)

**Comment by mcandre** [comment]
Looks like the documentation has since been updated to match in both pages. Thank you for continuing to assist developers!
