### ISSUE TITLE
osxpkg: Unable to use generated package in newer versions of MacOS

### ISSUE THREAD

**Issue by mcataga** [jordansissel/fpm#1908]
Since fpm is using pkgbuild under the hood, could we add a parameter that passes the value to the '--install-location' parameter of pkgbuild? 

Without the ability to specify that parameter, the installation location defaults to the root. Which in Mac OS Catalina and above is defaulted to read-only, so the package created ends up unusable.

**Comment by jordansissel** [comment]
Yes!

I think we can reuse an existing parameter that fpm has, `--prefix`. Other package types like RPM use this for controlling a similar feature.

I looked at the code in fpm, and adding support for this should be fairly simple, using passing `--install-location` with the argument `attributes[:prefix]` should do it.

I'll work on this when I can :)

**Comment by jordansissel** [comment]
#1909 might fix this. I don't have access to macOS Catalina at this time, so I would love if you could help test this. If you don't know how to test it, but still want to try, let me know and maybe we can step through things together? No pressure :)

**Comment by jordansissel** [comment]
I faked my own `pkgbuild` on Linux just to make it so I could see if the flags given to `pkgbuild` were correct, and you can review that here, instead of testing directly, if that helps: https://github.com/jordansissel/fpm/pull/1909#issuecomment-1146508508

**Comment by mcataga** [comment]
Hey Jordan, I was able to test the package and I'm able to install it now with the --prefix flag. Appreciate your help!

**Comment by jordansissel** [comment]
Lovely! Thank you for testing :)
