### ISSUE TITLE
Don't make `${}` dependencies lowercase

### ISSUE THREAD

**Issue by WilliamDEdwards** [jordansissel/fpm#1927]
Related to https://github.com/jordansissel/fpm/issues/1926

Setting a `${}` dependency for a deb file (I don't know what the official term is), e.g. with:

    fpm -d '${misc:Depends}'

... yields:

    Downcasing dependency '${misc:Depends}' because deb packages  don't work so good with uppercase names {:level=>:warn}

However, it is case-sensitive and documented. See chapter 4.1 of https://www.debian.org/doc/manuals/maint-guide/dreq.en.html.

**Comment by jordansissel** [comment]
Is this valid in debian binary packages? From the documentation, the `${...}` is expanded during package creation using a bunch of debhelper tools like dh_shlibdeps, etc. These tools are not used by fpm to create packages.

If you build a Debian package using Debian's own tooling, does the `${misc:Depends}` survive all the way from the `debian/control` file and into the binary .deb control file?

**Comment by jordansissel** [comment]
lintian complains about invalid dependency syntax:

```
% bundle exec bin/fpm -s empty -t deb -f -d '${misc:Depends}' -n example
Downcasing dependency '${misc:Depends}' because deb packages  don't work so good with uppercase names {:level=>:warn}
Created package {:path=>"example_1.0_all.deb"}

% lintian example_1.0_all.deb
E: example: bad-provided-package-name ${misc
```

Even `dpkg-deb` fails to parse the resulting Depends entry.
```
% dpkg-deb -I example_1.0_all.deb | grep Depends
 Depends: ${misc:depends}

% dpkg-deb -W --showformat "Depends" example_1.0_all.deb
dpkg-deb: error: parsing file '/tmp/dpkg-deb.z1qJ9I/control' near line 8 package 'example':
 'Depends' field, invalid package name '${misc': must start with an alphanumeric character
```

Unpacking the control file shows fpm does indeed put `${misc:Depends}` literally into the Depends entry.

```
% ar p example_1.0_all.deb control.tar.gz | tar -zxO ./control | grep Depends
Depends: ${misc:depends}
```

**Comment by WilliamDEdwards** [comment]
You're right. This is substituted at build time.
