### ISSUE TITLE
Distribution should be set to `--deb-dist` instead of 'whatever'

### ISSUE THREAD

**Issue by WilliamDEdwards** [jordansissel/fpm#1929]
In [`deb.changes`](https://github.com/jordansissel/fpm/blob/121989e0a00cd8cf7997e49abcbf0ef2041bf47c/templates/deb/deb.changes.erb#L17) and [`changelog.erb`](https://github.com/jordansissel/fpm/blob/121989e0a00cd8cf7997e49abcbf0ef2041bf47c/templates/deb/changelog.erb#L1), the distribution is hardcoded to `whatever`. They should instead be set to the value of `--deb-dist`. What's more, the default `--deb-dist` value seems to be `unstable`, which causes the following Lintian warning by default:

    changes: distribution-and-changes-mismatch unstable whatever

**Comment by jordansissel** [comment]
Can you tell me about the negative impact of this issue? Knowing more about it will help in writing test cases for it.

**Comment by WilliamDEdwards** [comment]
> Can you tell me about the negative impact of this issue?

When I, as a user, am able to set the distribution (using `--deb-dist`), I expect it to be set everywhere. Instead, it's only set in one (control) out of three (control, changelog, changes) places. This could cause confusion.

**Comment by lchabert** [comment]
And without a perfect alignment with deb-dist, some tools refuses to upload the package into debian repository. (for instance, dput-ng)

**Comment by jordansissel** [comment]
fpm 1.15.0 is released and, I believe, has resolve this issue. Please let me know if you find otherwise in a new issue (if a new problem) or this issue (if same problem)
