### ISSUE TITLE
How to bundle a local python package (as deb)

### ISSUE THREAD

**Issue by robinbowes** [jordansissel/fpm#1962]
Long-term fpm user here - I was bundling ruby gems as rpms back in 2013!

I'm hoping to use fpm to bundle a local python tool as a .deb, ie, use something like this:

```
fpm -s python -t deb mytool
```

Where "mytool" is a local package with a setup.cfg/setup.py that I can install using `pip3 install .` or `python3 setup.py install`.

How can I get fpm to bundle this tool + all requirements specified in setup.cfg as a .deb package?

Thx.

**Comment by jordansissel** [comment]
At present, fpm's python support can do what you describe, assuming I'm understanding you correctly. For example, doing something like the following:

```
fpm -s python -t deb .
```

Should package up the current directory, assuming a `setup.py` file is found. Any python dependencies will be listed on the package's dependency list (what Debian calls "Depends" and Red Hat calls "Requires")


Example:

setup.py:

```
% cat /tmp/z/example/setup.py 
from setuptools import setup

setup(name='example',
      version='1.0',
      install_requires=['requests>=1.28']
     )
```

Running it:
```
% bin/fpm -s python -t deb /tmp/z/example
Created package {:path=>"python-example_1.0_all.deb"}
```

Checking the package info:

```
% dpkg --info python-example_1.0_all.deb | egrep '(Package|Version|Depends)'
 Package: python-example
 Version: 1.0
 Depends: python-requests (>= 1.28)
```

**Comment by jordansissel** [comment]
@robinbowes I notice now that this feature (packaging a local directory)  isn't documented in the current release. I'll file an issue to track improving that.

Back to your question -- does this solve what you need? If not, let me know.

**Comment by robinbowes** [comment]
@jordansissel Thanks for the reply.

I can confirm that I tried `fpm -s python -t deb .` on one of the repos I am attempting to package, and I found it failed with this error:

```
$ SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0 fpm  -s python -t deb .
Traceback (most recent call last):
	12: from /Users/robin/.rbenv/versions/2.7.2/bin/fpm:23:in `<main>'
	11: from /Users/robin/.rbenv/versions/2.7.2/bin/fpm:23:in `load'
	10: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/bin/fpm:7:in `<top (required)>'
	 9: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	 8: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:591:in `run'
	 7: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	 6: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:367:in `execute'
	 5: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:367:in `each'
	 4: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:368:in `block in execute'
	 3: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/package/python.rb:111:in `input'
	 2: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/package/python.rb:255:in `load_package_info'
	 1: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '' (JSON::ParserError)
```

However, I tried it with another similar package (also requiring `SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0`) and it completed successfully:

```
$ SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0 fpm  -s python -t deb .
Created package {:path=>"python-example_0.1.0_all.deb"}
```

So, you have answered my original question, but I now have another one :). I shall ask that in a separate ticket.

I also note that the package that succeeded includes my home directory and python venv in the file paths. I shall read the docs about how to fix that problem and create an additional ticket if I can't figure it out.

Thanks again,

R.

**Comment by jordansissel** [comment]
> package that succeeded includes my home directory and python venv in the file paths

The --prefix flag might help, but I haven’t tested this Python venv case.

On Sun, Nov 27, 2022, at 5:02 PM, Robin Bowes wrote:
> 
> 
> @jordansissel <https://github.com/jordansissel> Thanks for the reply.
> 
> I can confirm that I tried `fpm -s python -t deb .` on one of the repos I am attempting to package, and I found it failed with this error:
> 
> `$ SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0 fpm  -s python -t deb .
> Traceback (most recent call last):
> 	12: from /Users/robin/.rbenv/versions/2.7.2/bin/fpm:23:in `<main>'
> 	11: from /Users/robin/.rbenv/versions/2.7.2/bin/fpm:23:in `load'
> 	10: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/bin/fpm:7:in `<top (required)>'
> 	 9: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
> 	 8: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:591:in `run'
> 	 7: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
> 	 6: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:367:in `execute'
> 	 5: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:367:in `each'
> 	 4: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/command.rb:368:in `block in execute'
> 	 3: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/package/python.rb:111:in `input'
> 	 2: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fpm-1.15.0/lib/fpm/package/python.rb:255:in `load_package_info'
> 	 1: from /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
> /Users/robin/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '' (JSON::ParserError)
`
> However, I tried it with another similar package (also requiring `SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0`) and it completed successfully:
> 
> `$ SETUPTOOLS_SCM_PRETEND_VERSION=0.1.0 fpm  -s python -t deb .
> Created package {:path=>"python-example_0.1.0_all.deb"}
`
