### ISSUE TITLE
fpm should reject debian packages with invalid values for the Version field

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#1968]
Found this note in an Influxdb PR: https://github.com/influxdata/influxdb/pull/23475

> Unfortunately, `fpm` is fairly permissive with what version tags it accepts

@bnpfeife, do you recall any specifics in the problem you were working around? I'd like to help ensure fpm only generates correct packages, and knowing more will help make sure any new tests for this issue can cover the problem you were having.

**Comment by jordansissel** [comment]
I see fpm does validation checks for the `Provides` field. We could also add validation for the version field. I'm open to automatic corrections like we do for deb package names[1], but I'm not sure this is the right way to solve it.

[1] https://github.com/jordansissel/fpm/blob/db06af3c0357e212df48009ecd73c945519a1e76/lib/fpm/package/deb.rb#L261-L289

**Comment by bnpfeife** [comment]
Hello! My apologies, I wish I had elaborated more in the commit message. If I recall correctly, `fpm` was accepting versions prefixed with `v` (e.g `v1.2.3`). It would build the packages; however, when I went to install them, the version string prevented the installation from proceeding. I can't remember if this error was produced by `dpkg` or `yum`.

**Comment by jordansissel** [comment]
No apology needed :)

I ran into this exact issue while writing some fpm examples for packaging up kubectl - https://fpm.readthedocs.io/en/v1.15.0/packages/dir.html -- ended up doing `${version#v*}` to have the shell strip the leading 'v' because fpm was producing invalid packages.

I'll close this as a duplicate of #1847. For improvements, I'll see about adding some smarts in fpm that tries to detect this particular case and automatically turn 'vX.Y.Z' to 'X.Y.Z'. For other cases, fpm can still reject with an actionable error message.

**Comment by jordansissel** [comment]
Closing to track as #1847.
