### ISSUE TITLE
FPM contains syntax which is invalidated with Ruby version 3.2.0

### ISSUE THREAD

**Issue by femiagbabiaka** [jordansissel/fpm#1983]
`Dir#exists?` and `File#exists?` were both EOL'd in version 3.2.0: https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/.

https://github.com/search?q=repo%3Ajordansissel%2Ffpm%20File.exists%3F&type=code
https://github.com/search?q=repo%3Ajordansissel%2Ffpm+Dir.exists%3F&type=code

**Comment by NicholasBHubbard** [comment]
PR #1981 addresses this issue.

**Comment by NicholasBHubbard** [comment]
@jordansissel this issue can be closed due to #1981 being merged.
