### ISSUE TITLE
Any tips for compiling a binary executable of fpm on arm64?

### ISSUE THREAD

**Issue by jgresham** [jordansissel/fpm#2055]
I'm looking to compile a binary executable of fpm for arm64 (and hopefully other architectures). Does anyone have experience or advice for trying to compile a ruby project into an executable? or any specific fpm related knowledge that might help for this?

## Background
fpm is a dependency for a popular electron app builder tool (desktop apps). They are currently using an old fpm binary and only have an x86 version. I'm looking to provide an aarch64/arm64 version to support electron apps on arm boards out of the box. More: https://github.com/signalapp/Signal-Desktop/issues/6063#issuecomment-1307001166

**Comment by jgresham** [comment]
Ok, I think have it here https://github.com/jgresham/fpm-arm-binary/blob/main/compile-script.sh

**Comment by jordansissel** [comment]
I’m glad you got things working and reported your findings!

One suggestion: after ‘git clone’ do a ‘git checkout’ of a release tag to ensure you get a released version of fpm.
