### ISSUE TITLE
Private vulnerability reporting

### ISSUE THREAD

**Issue by Sim4n6** [jordansissel/fpm#2058]
Hey ,

I have identified a potential vulnerability in the latest codebase [jordansissel/fpm](https://github.com/jordansissel/fpm).

Could you please consider enabling the GitHub feature for [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) to smooth the disclosure process ? or in case if you have a bug bounty program, please send me an invitation.

Thank you
@Sim4n6

**Comment by jordansissel** [comment]
I have now enabled private reporting. 👍

**Comment by Sim4n6** [comment]
Report sent via https://github.com/jordansissel/fpm/security/advisories/GHSA-c928-xh2c-79hj
