### ISSUE TITLE
add ruby/rubygems to gem packages

### ISSUE THREAD

**Issue by grosser** [jordansissel/fpm#21]
Just packed a gem of mine, but it could not be installed on a clean machine since ruby/rubygems was missing. Would be great if this was there automagically / if you could add instructions on how to do it (ill go digging now...)

**Comment by jordansissel** [comment]
The `.fpmrc` stuff I mentioned is implemented in fpm now.

Having `-s gem` automatically imply `--prefix` as the GEM_HOME is not implemented, but I am open to having. Let's file a separate ticket about it if it's still desired :)
