### ISSUE TITLE
Add --rpm-skip-os-install-post or similiar

### ISSUE THREAD

**Issue by askreet** [jordansissel/fpm#259]
When building packages that include JAR files RedHat distributions have defined some post-install steps that repackage the JAR files.  I find myself using the '-e' option with FPM frequently and adding the following at the beginning:

    %define __os_install_post %{nil}

If I'm not alone in this, it might make sense to define an --rpm-skip-os-install-post (I'm open to better naming.).

I'll add that if there is no objection to this sort of feature being added, I'd be willing to make the code changes.

**Comment by jordansissel** [comment]
I don't think this has been reported in a while, so it may be solved. I'm *pretty* sure fpm does the best it can to disable any of the weird "mess with your stuff" macros redhat ships rpmbuild with.
