### ISSUE TITLE
File name should take into account --edit

### ISSUE THREAD

**Issue by alex** [jordansissel/fpm#367]
If the name or version number is editted using --edit the resulting filename should take this into account.

**Comment by jordansissel** [comment]
I would actually love to get rid of the `--edit` flag.

If this issue is still interesting to you, can you help me understand your use case? For example, what causes you to edit the name or version?

**Comment by alex** [comment]
So, bearing in mind this was two jobs ago and I don't totally remember why I did this ;-):

I *think* the use case was that my employer had a convention of adding our name to package names, so `python-msgpack-rdio` or so.

It's also totally possible that there was a better way to solve this with fpm, but a) I don't remember if there were other constraints, b) I didn't know fpm that well when I did this.

**Comment by jordansissel** [comment]
@alex no worries! We can set the name with `-n foo` in almost all cases. I"ll close this and we can wait until we need it again :)

**Comment by alex** [comment]
It seems exceptionally probably that's the appropriate solution to the problem! Cheers.
