### ISSUE TITLE
avoid defaulting epoch=1 for rpms

### ISSUE THREAD

**Issue by lexinator** [jordansissel/fpm#381]
[sent this to fpm-users, but putting it here as well]

fpm is defaulting to epoch=1 for RPMs.  I found this when upgrading from 0.4.6 to 0.4.29(with some hair pulling to debug).  I am working around by using --epoch ''.

I'd like to point out this seems like the wrong default if you read about epoch use, http://www.rpm.org/max-rpm-snapshot/s1-rpm-depend-manual-dependencies.html.  If I understand correctly they recommend to use epoch only if the package version isn't sort order friendly.  (and tell the package provider to read http://semver.org =)

In the next major revision of fpm would it be possible to revert epoch to empty?

thanks
lex

**Comment by brendanlong** [comment]
Is there a way to make the warning go away?

**Comment by jordansissel** [comment]
@brendanlong we could add a flag for it, maybe?

**Comment by brendanlong** [comment]
That would work. It's just annoying to be "warned" that nothing is wrong every time, especially if you integrate fpm into scripts.

**Comment by jordansissel** [comment]
Agreed. Maybe since the warning was added 2+ years ago as part of a way to help notify users of the behavior change --- maybe it'd be fine to remove it?

I'm somewhat in favor now of removing the warning.

**Comment by lexinator** [comment]
+1 on removing the warning.

**Comment by josephfrazier** [comment]
+1 on removing the warning, or providing a flag to silence it
