### ISSUE TITLE
Stable way of determining path name of output package?

### ISSUE THREAD

**Issue by danielsdeleo** [jordansissel/fpm#425]
For some features I'm adding to Omnibus, I need a stable way of determining the name/path of the package file fpm creates. At the moment, I can parse fpm's output, e.g. `Created /var/cache/omnibus/pkg/chef_11.4.0-183-g2c0040c-0.ubuntu.12.04_amd64.deb`.

If the format of fpm's output is intended to remain stable then I don't need anything else (i.e., please close this). Otherwise, I would like a stable means to get the package path, for example, a command flag that makes fpm output the name of the package it would create.

Thanks for fpm and thanks in advance for your consideration.

**Comment by JonasGroeger** [comment]
You can parse the output using this regex: https://regex101.com/r/dI0fN6/1
