### ISSUE TITLE
arch dependency

### ISSUE THREAD

**Issue by emillion** [jordansissel/fpm#440]
Hi.
I'm trying to add 32 bits dependancies to a rpm for 64bits computers.  I don't know if it's possible or if I'm wrong in the syntax.
Some commands I tried :
fpm --directories=/dev/program -d 'zlib.i686' -n test -s dir -t rpm /dev/program
or
fpm --directories=/dev/program -d 'zlib = i686' -n test -s dir -t rpm /dev/program
or 
fpm --directories=/dev/program -d 'zlib-1.2.3-27.el6.i686' -n test -s dir -t rpm /dev/program
or
fpm --directories=/dev/program -d 'zlib = 1.2.3-27.el6.i686' -n test -s dir -t rpm /dev/program

When I try to install my rpm it says that it "Requires" zlib. "yum install zlib-1.2.3-27.el6.i686" and "zlib.i686" work.
Where is the problem ? :S
Thanks

**Comment by jordansissel** [comment]
I don't know if this is still a problem for you, but my knowledge of rpm (cross-arch dependencies) is not enough. The rpm-dev mailing list is wonderful for asking such questions :)

**Comment by utilitynerd** [comment]
If any ends up here googling this issue, the correct syntax is:

-d "zlib(x86-32)"
