### ISSUE TITLE
How to manage config files with FPM

### ISSUE THREAD

**Issue by rahsaanpage** [jordansissel/fpm#463]
I am running in to some issues, where if the rpm package is upgraded, the config files get removed and we lose all our work.. is there a better practice to manage config file using FPM. for example apache config httpd.conf?

i would like to keep whatever config file in place

@jordansissel @r4um 

one example, i create a LAMP sta k package, but i had to rebuild the release to include a php modules, packages are deployed via opsware, but when they updated the release in opsware, Opsware checks whats different in the package and replaces everythign with the new release. but i need to maintain the config files, because we are losing all our work..

**Comment by htaunay** [comment]
Hey @r4um

I'm stumbling into a similar problem as @johntdyer, but in my case I am working with a npm package.
Since I must declare the `-s npm` flag I cannot set the `-s dir` flag. To be more specific, I wish to to generate a rpm package from a node project, and I am interested in copying some configuration files to the /etc folder.

Any suggestion of how that could be possible?
Thanks in advance!

**Comment by r4um** [comment]
@htaunay `--config-files` will work, it will add config files to the package independent of `-s TARGET`.

**Comment by r4um** [comment]
> @htaunay --config-files will work, it will add config files to the package independent of -s TARGET.

Yeah sorry, that doesn't work. You can intermediately generate a `dir` target and add config to it and
build rpm from it. For ex.

```
‣ fpm -s npm -t dir hawk
Created package {:path=>"node-hawk.dir"}
‣ mkdir node-hawk.dir/etc
‣ echo x = y > node-hawk.dir/etc/myconf
‣ fpm -s dir -t rpm -n hawk --config-files etc/myconf -C node-hawk.dir/ .
no value for epoch is set, defaulting to nil {:level=>:warn}
no value for epoch is set, defaulting to nil {:level=>:warn}
Created package {:path=>"hawk-1.0-1.x86_64.rpm"}
```

**Comment by htaunay** [comment]
Not exactly what I was looking for but still useful
Thanks for the reply @r4um!
