### ISSUE TITLE
How to increment rpm release 

### ISSUE THREAD

**Issue by rahsaanpage** [jordansissel/fpm#466]
Hi @jordansissel @r4um 

When building RPM via FPM, how do i increment the build release. for example, when a package is created, it creates a release as the following "lampstack-5.2.17-1.x86_64.rpm", how can i increment the "-1" to "-2", what i have been doing to modify the rpm, is install the package and create a new rpm from the installed package, is this approach wrong?

**Comment by bviktor** [comment]
Could you please add this info to `--help`? As of FPM 1.11.0, it does not say anything about such flag (or build number, release number, or anything similar).
