### ISSUE TITLE
/var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/util.rb:51:in `safesystem': private method `wait' called for #<ChildProcess::Unix::Process:0x2b0e25777370> (NoMethodError)

### ISSUE THREAD

**Issue by arthurlogilab** [jordansissel/fpm#495]
~/local/lumberjack$ make deb
Makefile:33: warning: overriding commands for target `clean'
Makefile.ext:15: warning: ignoring old commands for target `clean'
fpm -s dir -t deb -n lumberjack -v 0.0.30 --prefix /opt/lumberjack \
                --exclude '*.a' --exclude 'lib/pkgconfig/zlib.pc' -C build \
                --description "a log shipping tool" \
                --url "https://github.com/jordansissel/lumberjack" \
                bin/lumberjack bin/lumberjack.sh lib
/var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/util.rb:51:in `safesystem': private method `wait' called for #<ChildProcess::Unix::Process:0x2b0e25777370> (NoMethodError)
        from /var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/package/deb.rb:493:in `write_control_tarball'
        from /var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/util.rb:114:in `call'
        from /var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/util.rb:114:in `with'
        from /var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/package/deb.rb:488:in `write_control_tarball'
        from /var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/package/deb.rb:323:in `output'
        from /var/lib/gems/1.8/gems/fpm-0.4.41/lib/fpm/command.rb:391:in `execute'
        from /var/lib/gems/1.8/gems/clamp-0.6.1/lib/clamp/command.rb:67:in `run'
        from /var/lib/gems/1.8/gems/clamp-0.6.1/lib/clamp/command.rb:125:in `run'
        from /var/lib/gems/1.8/gems/fpm-0.4.41/bin/fpm:8
        from /usr/local/bin/fpm:19:in `load'
        from /usr/local/bin/fpm:19
make: *** [deb] Error 1

Sorry, am a complete stranger to gem/ruby etc. There might a really obvious fix (or version problem).

**Comment by jordansissel** [comment]
Haven't seen reports of this in a while; assuming it's resolved. If' not teh case, please reopen :)
