### ISSUE TITLE
How can I add some custom action on fpm package.

### ISSUE THREAD

**Issue by kerwin** [jordansissel/fpm#558]
I want do some initial action before package installed.
like, 
1. Add a user for service.
2. Create log, pid files.
3. Notify centro server that rpm has been installed.

So, Is there a way to add custom script on fpm package, just like %pre %post on rpm spec files.

**Comment by jordansissel** [comment]
`fpm` supports `--after-install` and several other things which let you specify scripts to run on the installing system
