### ISSUE TITLE
FPM complains of "EEXIST"

### ISSUE THREAD

**Issue by dalgibbard** [jordansissel/fpm#581]
Trying to package a self-contained CouchDB RPM (See: https://github.com/iriscouch/build-couchdb) from a directory, CentOS 6.4 x86_64, with minorly updated/patched Ruby as per https://github.com/jordansissel/fpm/issues/214#issuecomment-17966459 
FPM is ver: 0.4.42
```
fpm -s dir -t rpm -n "couchdb" -v "1.4.0" --iteration "sc1" \
--rpm-rpmbuild-define 'couchdb_user couchdb' \
--rpm-rpmbuild-define 'couchdb_group couchdb' \
--rpm-rpmbuild-define 'couchdb_home %{_localstatedir}/lib/couchdb' \
--rpm-auto-add-directories --workdir "/tmp/tmp" \
--after-install "~/after-install" --before-install "~/before-install" \
--after-remove "~/after-remove" --before-remove "~/before-remove" \
--url "http://couchdb.apache.org/" \
--description 'Apache CouchDB is a ..SNIP' \
--license "ASL 2.0" --category "Applications/Databases" \
--replaces "couchdb" --provides "couchdb" -m "me@mymail.com" -e .
```
Gives the error:
```
no value for epoch is set, defaulting to nil {:level=>:warn}
/usr/lib64/ruby/gems/1.8/gems/backports-3.3.5/lib/backports/tools.rb:161:in `symlink_without_potential_path_arguments': File exists - libltdl.so.7.3.0 or /tmp/tmp/package-rpm-build20131107-23120-4hwsog/BUILD/opt/couchdb/lib/libltdl.so (Errno::EEXIST)
	from /usr/lib64/ruby/gems/1.8/gems/backports-3.3.5/lib/backports/tools.rb:161:in `symlink'
	from /usr/lib64/ruby/1.8/fileutils.rb:1246:in `copy'
	from /usr/lib64/ruby/1.8/fileutils.rb:452:in `copy_entry'
	from /usr/lib64/ruby/1.8/fileutils.rb:1331:in `traverse'
	from /usr/lib64/ruby/1.8/fileutils.rb:449:in `copy_entry'
	from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.42/lib/fpm/util.rb:140:in `copy_entry'
	from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.42/lib/fpm/package/rpm.rb:383:in `output'
	from /usr/lib64/ruby/1.8/find.rb:39:in `find'
	from /usr/lib64/ruby/1.8/find.rb:38:in `catch'
	from /usr/lib64/ruby/1.8/find.rb:38:in `find'
	from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.42/lib/fpm/package/rpm.rb:380:in `output'
	from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.42/lib/fpm/command.rb:389:in `execute'
	from /usr/lib64/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:67:in `run'
	from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.42/lib/fpm/command.rb:436:in `run'
	from /usr/lib64/ruby/gems/1.8/gems/clamp-0.6.2/lib/clamp/command.rb:125:in `run'
	from /usr/lib64/ruby/gems/1.8/gems/fpm-0.4.42/bin/fpm:8
	from /usr/bin/fpm:23:in `load'
	from /usr/bin/fpm:23
```
And that file looks like this:
```
[root@c6 build]# find . -iname "libltdl.so*" -exec ls -l {} \;
lrwxrwxrwx. 1 root root 16 Nov  7 12:52 ./opt/couchdb/lib/libltdl.so -> libltdl.so.7.3.0
lrwxrwxrwx. 1 root root 16 Nov  7 12:52 ./opt/couchdb/lib/libltdl.so.7 -> libltdl.so.7.3.0
-rwxr-xr-x. 1 root root 130268 Nov  7 12:52 ./opt/couchdb/lib/libltdl.so.7.3.0
```

So i'm assuming that rather than capturing the symlinks as symlinks within the RPM, it's trying to comvert them to files perhaps, and that file already exists? Is there a way to change that behaviour (Assuming what I'm thinking is correct)?
FYI; these are softlinks. Have tried passing "--rpm-use-file-permissions" too, but no change.

Many thanks!
Darren.

**Comment by jordansissel** [comment]
Sounds like upgrading ruby fixed the problem.

If others run into this in the future, we can explore monkeypatching ruby 1.8 to work around this problem.

**Comment by doctorcolossus** [comment]
Hi! I have just run up against this bug, also in ruby 1.8.

If monkeypatching is feasible, I would very much appreciate the effort.

I'm trying to use fpm to package the Anki 2 on Maemo 5 on the N900. I turned to fpm after many hours of frustration spent trying to make debhelper and stdeb work, and fpm did a marvelous job of automagically packaging up the my missing Python package dependencies (ssl & pysqlite).

Ruby 1.8 is packaged in the Maemo 5 repositories, which have pretty much remained frozen since Microsoft bought Nokia. I can try compiling my own Ruby. I am not sure how involved that would be, or if it would even work, but it seems like it would be rather involved, especially doing so on my phone. So if you can find a way to monkeypatch fpm for Ruby 1.8 compatibility, you'll really make my day!

**Comment by doctorcolossus** [comment]
fpm -s dir -t deb -n anki -v 2.0.32 -d "libjs-jquery" -d "libjs-jquery-flot" -d "libjs-jquery-ui" -d "python = 2.5" -d "python-beautifulsoup" -d "python-httplib2" -d "python-pysqlite >= 2.6.3" -d "python-simplejson" -d "python-sqlalchemy" --deb-recommends python-matplotlib --deb-suggests lame --deb-suggests mplayer --inputs /home/user/ankifiles --directories /opt/usr/share/anki
/var/lib/gems/1.8/gems/backports-3.6.4/lib/backports/tools/path.rb:42:in `symlink_without_potential_path_arguments': File exists - /opt/usr/share/anki or /var/tmp/package-dir-staging20150702-13534-s2qj90/ (Errno::EEXIST)
            from /var/lib/gems/1.8/gems/backports-3.6.4/lib/backports/tools/path.rb:42:in `symlink'
            from /usr/lib/ruby/1.8/fileutils.rb:1239:in `copy'
            from /usr/lib/ruby/1.8/fileutils.rb:451:in `copy_entry'
            from /usr/lib/ruby/1.8/fileutils.rb:1324:in `traverse'
            from /usr/lib/ruby/1.8/fileutils.rb:448:in `copy_entry'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/package/dir.rb:177:in `copy'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/package/dir.rb:143:in `clone'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/package/dir.rb:71:in `input'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/package/dir.rb:69:in `chdir'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/package/dir.rb:69:in `input'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:345:in `execute'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:343:in `each_line'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:343:in `execute'
            from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/lib/fpm/command.rb:510:in `run'
            from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
            from /var/lib/gems/1.8/gems/fpm-1.3.3/bin/fpm:8
            from /var/lib/gems/1.8/bin/fpm:19:in `load'
            from /var/lib/gems/1.8/bin/fpm:19
