### ISSUE TITLE
Support CPAN naming patterns and dependencies 

### ISSUE THREAD

**Issue by dnbert** [jordansissel/fpm#596]
When creating a Debian Package using the CPAN source, dependencies will be adding to the package metadata in a specific format such as perl-mydependency. If the -n flag is used to support an alternative name such as libmypackage-perl, the dependencies in that package do not respect the new naming convention.

Requesting a feature flag to support naming patterns such as --name-pattern lib-***-perl or some variant thereof. 

I hope this made sense and didn't confuse you :)

**Comment by jordansissel** [comment]
Dup of #470 I think.
