### ISSUE TITLE
fpm should be able to build freebsd packages!

### ISSUE THREAD

**Issue by jtimberman** [jordansissel/fpm#62]
Because freebsd is awesome, of course ;).

**Comment by thefosk** [comment]
+1

**Comment by jordansissel** [comment]
https://github.com/jordansissel/fpm/pull/870 (by @fetep) is working towards this

**Comment by thefosk** [comment]
Any updates on this?

**Comment by kylegato** [comment]
+1 want this

**Comment by hatt** [comment]
#1073

**Comment by jordansissel** [comment]
#1073 (shipped with fpm 1.5.0) solves this. Closing! :)
