### ISSUE TITLE
Broken symlinks can't be copied

### ISSUE THREAD

**Issue by bltavares** [jordansissel/fpm#658]
Hi there,

I wanted to package the project directory under `/usr/local/share/project` and have a symlink on `/usr/local/bin/project -> /usr/local/share/project/bin/project`.
The link is broken on the packager system, but would resolve to the right location when installed.
## Steps to reproduce

``` bash
mkdir project
cd project

echo "echo 1" > sample-command
ln -s /usr/local/share/project/sample-command project-bin
fpm -s dir -t deb -n project .=/usr/local/share/project project-bin=/usr/local/bin
```
### Error message

```
Invalid package configuration: Cannot package the path 'project-bin', does it exist? {:level=>:error}
```
### Version

fpm (1.0.2)

**Comment by alanthing** [comment]
I don't have a PR, but I noticed this bug when using the `virtualenv` source type if the contents of my `--virtualenv-other-files-dir .` contains a broken symlink. My workaround is to simply `touch` the "target" on the the build server.
