### ISSUE TITLE
Provide `upgrade` action for packages

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#661]
Currently fpm provides `--before-install` and other things. Only `install` and `remove` are supported

Many packaging systems (rpm, arch, deb) support additional states, such as `upgrade`. They all implement them differently, but fpm can provide the right abstraction and templating to make it all work

In this ticket, it would be useful to track the ongoing work to provide an additional `upgrade` step. 

It's also worth noting that by implementing this, we may cause behavioral changes. For example, if today a user knows that `--after-install` equates to `postinst` in deb, and wants to support upgrades, so the user carefully crafts a script to pass to `--after-install` and knows deb will handle it in a special way for upgrades. If we abstract install and upgrade scripting, we might accidentally mess up this existing behavior for this user.

**Comment by josegonzalez** [comment]
So this can be closed?

**Comment by djhaskin987** [comment]
I believe this can be closed, it has been released and live for some time now :) thanks to all who helped
