### ISSUE TITLE
Proposal: Rewrite in Go?

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#669]
@evanphx proposed possibly writing fpm in Go to solve some of his pains. Like all things, I am open to such proposals and am filing this issue as a means to further discussion.

Fundamentally, the goal of fpm is solving problems, and ruby is becoming a problem because versioning changes so much of the internals. I want installing fpm to be an easy process. I want using fpm to be easy.

There are ways to solve the current problems fpm has with ruby, but before we talk about that, let's try to list subjectively the pros and cons of being in ruby and being in go.

I've tried to focus the items listed below as long-term items, not short-term things.

# Invariants

* Users must not be impacted by this change. This means the `fpm` command line interface *must not* change.
* All flags must remain with the same behavior.
* Existing behaviors, except for bugs, must be the same.

# Ruby

## Pros

* Development: Code already written! ;)
* Users: `gem install` mostly kinda works

## Cons

* Development: Difficult and annoying to support multiple versions of Ruby.
* Users: Unmet expectations when running into bugs due to Ruby versions
* Users: 'gem install' creates confusion for users who don't have the correct upstream dependencies installed in their OS (say, missing ruby-dev)

# Go

## Pros

* Users: Easy to distribute a single executable built for different platforms. No dependencies for users to deal with.
* Users: Much more obvious path for using fpm to package itself for deb/rpm/etc for releases!
* Users: Much easier to support Windows!
* Development: Go promises backwards compatibility and maintains `gofix` for upgrading older code. 

## Cons

* Development: Rewriting what is currently 5000 lines of ruby (fpm `lib` and `templates`) is not a small task.
* Development: Code dependencies in Go are not a solved problem. Kinda sucks for development, but doesn't impact users.
* Development/Advanced users: No simple way to replace the `fpm` ruby api, but we (@evanphx and I) have discussed possibility of providing a JSON interface if programmatic access is needed.
* Development: ruby 'arr-pm' rpm library would need to be migrated to Go as well.

**Comment by djhaskin987** [comment]
I change my mind. Go has much better distribution experience. As far as that goes, I'm all for switching languages. Ruby is a nightmare when it comes to distributing software. Go is not, from what I've heard you get a single executable for the target platform. What a relief that would be! I wouldn't have to -- ironically --  find some wierd way to package a tool meant to make packaging easy. 

What could fpm be like in go? Have a look at [aptly](http://www.aptly.info/), a go project designed to make managing package repositories easier. It's built to manage deb repos, but I can easily get it for CentOS as a single binary executable, and it just works.

**Comment by rholder** [comment]
As for the jar packaging route, I assembled a [JRuby doodad](https://github.com/rholder/jfpm) similar to what @djhaskin987 described about a year ago that we've been using for all of our production builds (and just recently updated it for 1.3.3). Distributing FPM as a single binary among my team made it a really easy sell and getting it integrated with Jenkins was a snap. I am very much in favor of single standalone binaries and would welcome a Go version of this fine tool as well. :+1: on continuing to make an excellent project even better.

**Comment by jbcraig** [comment]
I would be concerned that go will kill Solaris 10/11 SPARC support.  The go documentation says it has experimental support for illumos / Solaris 11 on x86.  Not sure what this means for native Solaris 10 on x86 or SPARC.  Lack of SPARC support would kill 50% of fpm's value proposition for me.

**Comment by jordansissel** [comment]
@jbcraig noted!

As this ticket was mostly a thought experiment, I'm happy keeping fpm in ruby. Rewriting in another language will significantly derail stability (or improvements) in order to keep backwards compatibility and whatnot.

I'm content keeping it in Ruby :)

**Comment by jordansissel** [comment]
Going to close this. Thanks to everyone who helped provide feedback and ideas :)

**Comment by mcandre** [comment]
As a DevOp, I find Go/Rust dramatically lighten the tech stack. I've used Ruby for many years, but would not want to return to that provisioning mess. Ruby is a beautiful object oriented language, a powerful interpreted language. But its runtime and RubyGems are not fun to manage. Native RubyGems are fragile, often breaking, preventing various and sundry Ruby components from working in practice.

Ruby makes the runtime environment unnecessarily complex, compared to simply using a standalone binary.

I believe it is possible to rewrite fpm in a statically compiled programming language. Yes, it will take some time to reimplement the core, and all the different amazing artifact modes that fpm in its Ruby form supports.

A rewrite is most welcome. Now that some time has passed... would you reconsider?

**Comment by jordansissel** [comment]
If the goal is to simplify distribution/installation, then there are far less risky solutions than writing fpm in another language/platform.

I’m working on shipping fpm releases as native, standalone packages that would solve the installation complexity, I think, by making fpm available through a single install instead of multiple dependencies/rubygems as is needed today. If that’s of interest, let me know :)

**Comment by nicobrevin** [comment]
Vagrant used some pretty gnarly tricks to produce standalone ruby installs
for itself.  You might find some useful prior art there for such an effort.
