### ISSUE TITLE
Support virtualenvs for python package building

### ISSUE THREAD

**Issue by josegonzalez** [jordansissel/fpm#697]
FPM currently requires separate packages for every piece of a given python package. Using the [`beaver`](https://github.com/josegonzalez/beaver) repository, you would need to create the initial beaver package, as well as iterate over each line of the requirements file and create packages for those. 

The above works great if you do not also distribute other fpm-based python packages on the server with conflicting requirements. If you do, then tough shit.

A better way would be to build a [python virtualenv](https://pypi.python.org/pypi/virtualenv) for the package. Thus we'd only have to install `python-beaver` to get everything up and running. This is contrary to the debian way -lawl - but is more immediately useful to those attempting to run services in production.

[dh-virtualenv](http://dh-virtualenv.readthedocs.org/en/latest/) does something similar - though is python specific - and it doesn't create binaries for scripts like fpm does without need to learn more about debian packaging.

Issue #636 somewhat touches on this, though without any concrete outcome.

**Comment by neoice** [comment]
+1

I tried to package some Python webapps with virtualenvs in early 2013 and was not successful due to symlinks/PATHs within the virtualenvs. I'm revisiting the problem now and I'm bummed that it hasn't been resolved yet.

there's a number of issues on the FPM tracker that this feature would solve:

https://github.com/jordansissel/fpm/issues/262
https://github.com/jordansissel/fpm/issues/780
https://github.com/jordansissel/fpm/issues/636 (maybe)

I could also add to @thedrow's bounty (charity or BTC)

**Comment by thedrow** [comment]
ping @jordansissel

**Comment by thedrow** [comment]
We can use https://github.com/PolicyStat/terrarium instead of virtualenvwrapper-tools.
It has a much better API and you can simply download the compressed virtualenv from somewhere and use the CLI to uncompress it.

**Comment by evilsocket** [comment]
Pull request waiting :) https://github.com/jordansissel/fpm/pull/864

**Comment by jravetch** [comment]
+1  Been using dh-virtualenv as a substitute until fpm gets this feature.

**Comment by djhaskin987** [comment]
If no one objects, I'll start on this feature based on the script found here --> https://github.com/brutasse/graphite-api/blob/master/fpm/build-deb.sh . It seems pretty straight forward; expect a pull request soon.

**Comment by thedrow** [comment]
It's exactly what @evilsocket did but for some reason he could not inherit from the FPM::Package::Dir and other problems as well.
Maybe you guys can join forces in order to finish this.

**Comment by djhaskin987** [comment]
I have a nearly working prototype. I don't need to inherit from FPM::Package::Dir; if you look at `FPM::Package::Tar`'s input function, it uses `Dir` without inheriting from it; my current solution does the same. You can take a look at what I have so far [here](https://github.com/djhaskin987/fpm/tree/feature/697), and in particular [my first virtualenv commit](https://github.com/djhaskin987/fpm/commit/ae443f9b7ca0794d1285f96462432f7f1ec6a6f9).

**Comment by djhaskin987** [comment]
DOH *facepalm* I see now @evilsocket has a PR open and it's farther along than mine. For shame starting a new one :-1:. Maybe I'll start from where he left off.

**Comment by evilsocket** [comment]
@djhaskin987 if u want to improve my stuff, that would be great :)

**Comment by djhaskin987** [comment]
Thanks for your support, @evilsocket .

**Comment by djhaskin987** [comment]
Submitted a PR! Many thanks again @evilsocket for your code and support. Comments and suggestions welcome! I don't think it's perfect, but I think it will cover most use cases and I think it's pretty good! :+1: Let me know if there are any deal breakers, everyone.

**Comment by jordansissel** [comment]
#930 is merged. Release coming soon.!

**Comment by thedrow** [comment]
Thanks. You guys are awesome!

**Comment by evilsocket** [comment]
:dancers: :dancers: :dancers: :dancers:

**Comment by zoresvit** [comment]
Finally we have good solution for Python packaging! I think from Python developers point of view merge of #930 is the best that ever happened to `fpm` — it **so much** simplifies the packaging and solves the problems. Thank you! :+1: :)
