### ISSUE TITLE
rpm -e or yum remove not removing files from rpm build

### ISSUE THREAD

**Issue by marshyski** [jordansissel/fpm#701]
Summary:

After installing my custom package "ganglia-web-3.5.12-1.x86_64.rpm" and removing the package via "rpm -e" or "yum remove" it leaves the package contents behind.  It does magically delete some files but not all.    

Versions of software used:
RHEL 6.4
rpm-libs-4.8.0-37.el6.x86_64
rpm-4.8.0-37.el6.x86_64
rpm-build-4.8.0-37.el6.x86_64
ruby-1.8.7.352-13.el6.x86_64
rubygems-1.3.7-5.el6.noarch
gem -v 2.2.2

[timski@server ~]$ fpm -v
Missing required -s flag. What package source did you want? {:level=>:warn}
Missing required -t flag. What package output did you want? {:level=>:warn}
No parameters given. You need to pass additional command arguments so that I know what you want to build packages from. For example, for '-s dir' you would pass a list of files and directories. For '-s gem' you would pass a one or more gems to package from. As a full example, this will make an rpm of the 'json' rubygem: `fpm -s gem -t rpm json` {:level=>:warn}
Fix the above problems, and you'll be rolling packages in no time! {:level=>:fatal}
[timski@server ~]$ fpm --version
1.1.0

Command issued during RPM build:

fpm -s dir -t rpm -a x86_64 -n ganglia-web -v 3.5.12 --rpm-compression bzip2 --before-install /var/lib/ganglia/pre-rpm-install --after-install \
/var/lib/ganglia/post-rpm-install --rpm-user ganglia --rpm-group ganglia /var/lib/ganglia /var/www/html/ganglia

**Comment by dhajoshi** [comment]
hello this is still issue ... it's very much required to us .. 

How to reproduce ?

fpm -s dir -t rpm -n nmr-mydemo  -v 1.0 -C /tmp --prefix /local/0/home --edit --after-install /var/tmp/after_install.sh --before-install /var/tmp/before_install.sh --rpm-user dhajoshi --rpm-group euunixeng --directories /local/0/home/testpacking/ --force testpacking

in above command my source is at /tmp/testpacking ... and my prefix is at /local/0/home ..

it creates RPM but when i try to remove it doesnt remove any of the directories and files in RPM

Now second case  the remove works perfectly is ... when my Prefix and my source both are same ...

fpm -s dir -t rpm -n nmr-mydemo  -v 1.0 -C /tmp --prefix /tmp --edit --after-install /var/tmp/after_install.sh --before-install /var/tmp/before_install.sh --rpm-user dhajoshi --rpm-group euunixeng --directories /local/0/home/testpacking/ --force testpacking

**Comment by mateuszkwiatkowski** [comment]
I face the same problem: removing package leaves directories on disk. Adding `--rpm-auto-add-directories` breaks package:
```
Transaction check error:
  file /usr/lib/systemd from install of mypackage-0.10.22-1.x86_64 conflicts with file from package systemd-208-20.el7_1.6.x86_64
  file /usr/lib/systemd/system from install of mypackage-0.10.22-1.x86_64 conflicts with file from package systemd-208-20.el7_1.6.x86_64
```
Shouldn't this issue be reopened? I use fpm-1.4.0.

**Comment by jonasdemoor** [comment]
Can confirm this. I created an RPM for Kvantum with --rpm-auto-add-directories, and DNF (on Fedora) says there's a conflict:

```bash
Error: Transaction check error:
  file /usr/share/icons/hicolor/scalable from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/icons/hicolor/scalable/apps from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package hicolor-icon-theme-0.17-1.fc27.noarch
  file /usr/share/kde4 from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package kde-filesystem-4-57.fc27.x86_64
  file /usr/share/kde4/apps from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package kde-filesystem-4-57.fc27.x86_64
  file /usr/share/kde4/apps/color-schemes from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package kde-filesystem-4-57.fc27.x86_64
  file /usr/lib64/qt5 from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package qt5-qtbase-5.9.2-6.fc27.x86_64
  file /usr/lib64/qt5/plugins from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package qt5-qtbase-5.9.2-6.fc27.x86_64
  file /usr/lib64/qt5/plugins/styles from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package qt5-qtbase-5.9.2-6.fc27.x86_64
  file /usr/share/color-schemes from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package plasma-desktop-5.11.4-1.fc27.x86_64
  file /usr/share/icons/hicolor from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/scalable from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/icons/hicolor/scalable/apps from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/kde4 from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
  file /usr/share/kde4/apps from install of kvantum-theme-engine-V0.10.5-0.x86_64 conflicts with file from package fedora-logos-28.0.2-1.fc27.x86_64
```

Without the option it installs fine. I use FPM 1.9.3.
