### ISSUE TITLE
Add the ability to turn off all logging

### ISSUE THREAD

**Issue by sethvargo** [jordansissel/fpm#702]
Right now, FPM is really good about using log levels for everything... except in [one place](https://github.com/jordansissel/fpm/blob/07fff9c9ee03152f659b23e72651ddfeb5f13fd7/lib/fpm/command.rb#L414):

```ruby
@logger.log("Created package", :path => package_file)
```

To the best of my knowledge, I can't seem to turn this off. This causes two problems:

1. It makes test output muddy ([example](https://travis-ci.org/opscode/omnibus-ruby/jobs/24805463#L99))
2. It makes machine-parsing the output more difficult. You have to account for this un-tunable data onto standard out :frowning:

**Comment by jordansissel** [comment]
Hmm, somehow I didn't see this ticket :(

I'm open to fixing this if it's still a problem.

**Comment by sethvargo** [comment]
@jordansissel this was from a long time ago back when Omnibus still used FPM :smile:

**Comment by jordansissel** [comment]
Ahh, didn't know Omnibus moved elsewhere. Cheers!
