### ISSUE TITLE
fpm install failing on Ubuntu 12.04

### ISSUE THREAD

**Issue by x110dc** [jordansissel/fpm#726]
Installing `fpm` on a bare Ubuntu box is failing.  This just started happening today (same thing worked yesterday) so I'm wondering if some dependency has been updated?  The solution for similar-looking problems was to install `ruby-dev` but that's already installed.

Here's what I get:

```
 ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.8 extconf.rb

Gem files will remain installed in /var/lib/gems/1.8/gems/json-1.8.1 for inspection.
Results logged to /var/lib/gems/1.8/gems/json-1.8.1/ext/json/ext/generator/gem_make.out
```

I put it all in a Dockerfile here if it's of help:
https://github.com/x110dc/fpm-test

**Comment by mephux** [comment]
Oddly enough this happened today for me too - same error output on ubuntu/docker debian image. Restarting docker fixed the issue for me too. I have been trying to track down the cause without any luck. I would make this issue sticky as a lot of folks use FPM with their CI setups and a lot more people are using docker for this. You're call - would just be helpful note but not really your projects problem.
