### ISSUE TITLE
Package Naming Convention

### ISSUE THREAD

**Issue by kitingChris** [jordansissel/fpm#743]
Hi there,

I have troubles to meet with a package naming convention, that forces me to use 

```
NAME-VERSION-TIMESTAMP.arch.rpm
```

Which should look like this: 

```
MyPackage-1.0-20140728091026.i386.rpm
```

I tried to use 

```
-v {package.version}-{package.timestamp}
```

 but that produces warnings like: 

```
Package version '0.1a-20140728173919' includes dashes, converting to underscores
```

**Comment by rameshmimit** [comment]
Helllo @kitingChris 
I also wants to use - instead of _ in my rpm package versions. What was the solution? I did not see you mentioned the solution here.

Current output:  rpmname-3.1.1_dev_30b-1.x86_64.rpm
Goal:                 rpmname-3.1.1-dev-30b-1.x86_64.rpm

**Comment by glensc** [comment]
rpm filename consists of several parts.

so taking MyPackage-1.0-20140728091026.i386.rpm as input it is likely:

- %{NAME}: MyPackage
- %{VERSION}: 1.0
- %{RELEASE}: 20140728091026
- %{ARCH}: i386

none of them can contain `-` as it's the separator of these.

you can check this with `rpm -qp --qf '%{NAME}\n' rpmfile.rpm`

**Comment by glensc** [comment]
you want to specify `dev_30b` part of RELEASE, not VERSION. i believe it's iteration in fpm terms what @jordansissel said.

**Comment by rameshmimit** [comment]
Thanks for pointing that out @glensc. I have used --iteration option to get the correct name. Below is the way I am using it now:

-v '3.1.1' --iteration dev.b30

before it was -v '3.1.1-dev.b30'
