### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Queuecumber** [jordansissel/fpm#773]
I am seeing very high disk usage when using fpm to package a large set of files.

The original set of files is 88GB. The fpm process is being kicked off in my home directory on a disk with 750GB of space left, but it is filling up my system disk (probably /tmp writes) which has about 170GB of space left. When I run fpm i see steadily increasing disk usage until it eventually crashes with the following error message:

```
/usr/lib/ruby/1.9.1/fileutils.rb:1372:in `copy_stream': No space left on device - write (Errno::ENOSPC)
    from /usr/lib/ruby/1.9.1/fileutils.rb:1372:in `block (2 levels) in copy_file'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1371:in `open'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1371:in `block in copy_file'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1370:in `open'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1370:in `copy_file'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1338:in `copy'
    from /usr/lib/ruby/1.9.1/fileutils.rb:465:in `block in copy_entry'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1433:in `preorder_traverse'
    from /usr/lib/ruby/1.9.1/fileutils.rb:462:in `copy_entry'
    from /var/lib/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/util.rb:176:in `copy_entry'
    from /var/lib/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/rpm.rb:426:in `block in output'
    from /usr/lib/ruby/1.9.1/find.rb:41:in `block in find'
    from /usr/lib/ruby/1.9.1/find.rb:40:in `catch'
    from /usr/lib/ruby/1.9.1/find.rb:40:in `find'
    from /var/lib/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/package/rpm.rb:423:in `output'
    from /var/lib/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/command.rb:418:in `execute'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:67:in `run'
    from /var/lib/gems/1.9.1/gems/fpm-1.2.0/lib/fpm/command.rb:482:in `run'
    from /var/lib/gems/1.9.1/gems/clamp-0.6.3/lib/clamp/command.rb:125:in `run'
    from /var/lib/gems/1.9.1/gems/fpm-1.2.0/bin/fpm:8:in `<top (required)>'
    from /usr/local/bin/fpm:23:in `load'
    from /usr/local/bin/fpm:23:in `<main>'
```

What is the reason for this disk usage and can it be corrected? (Or am I doing something wrong?)

**Comment by RobotLimeLtd** [comment]
I am seeing exactly the same issue in FPM 1.6.3, while trying to create an RPM of Anaconda 3-4.1.1.

The source directory is 1.5GB, which is big, but nothing like as big as the above.

Command I ran was: fpm -s dir -t rpm -n anaconda -v 3-4.1.1 --iteration 1 -a x86_64 --before-install ./preinstall-script --prefix /opt/anaconda3 --rpm-user anaconda --rpm-group anaconda --rpm-use-file-permissions --rpm-auto-add-directories -C anaconda3

Error output below:

/usr/local/lib/ruby/2.3.0/fileutils.rb:1394:in `copy_stream': No space left on device - sendfile (Errno::ENOSPC)
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:1394:in `block (2 levels) in copy_file'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:1393:in `open'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:1393:in `block in copy_file'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:1392:in `open'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:1392:in `copy_file'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:1360:in `copy'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
        from /usr/local/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/util.rb:301:in `copy_entry'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/package/dir.rb:210:in `rescue in copy'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/package/dir.rb:204:in `copy'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/package/dir.rb:162:in `block in clone'
        from /usr/local/lib/ruby/2.3.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib/ruby/2.3.0/find.rb:48:in `catch'
        from /usr/local/lib/ruby/2.3.0/find.rb:48:in `block in find'
        from /usr/local/lib/ruby/2.3.0/find.rb:43:in `each'
        from /usr/local/lib/ruby/2.3.0/find.rb:43:in `find'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/package/dir.rb:160:in `clone'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/package/dir.rb:71:in `block in input'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/package/dir.rb:69:in `chdir'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/package/dir.rb:69:in `input'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/command.rb:338:in `block in execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/command.rb:337:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/lib/fpm/command.rb:560:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/fpm-1.6.3/bin/fpm:8:in `<top (required)>'
        from /usr/local/bin/fpm:23:in `load'
        from /usr/local/bin/fpm:23:in `<main>'
