### ISSUE TITLE
RPM spec file support in fpm

### ISSUE THREAD

**Issue by madhavan020985** [jordansissel/fpm#847]
All files installed through rpm are root-owned and is there a way that i can set the ownership to some other user using fpm.
%files (or) %defattr in Spec file can do it, but i see little documentation on the  fpm's "--attr" option?

**Comment by BaxterStockman** [comment]
Try `--rpm-user` and `--rpm-group` for ownership, `--rpm-defattrfile` and `--rpm-defattrdir` for modes.  For finer-grained control over ownership, you may need to use the `--before-install` and/or `--after-install` options that allow you to hook shell scripts into the installation process.
