### ISSUE TITLE
`fpm -s pleaserun ...` support

### ISSUE THREAD

**Issue by jordansissel** [jordansissel/fpm#856]
Time to make fpm and pleaserun usable together. It would be cool to have this:

```
fpm -s pleaserun -t rpm --pleaserun-platform upstart /some/program
```

And have it generate an rpm with the correct post-install steps + files to install an upstart task that runs /some/program.

**Comment by jakerobinson** [comment]
YES. :)

**Comment by nicocesar** [comment]
+1

**Comment by jordansissel** [comment]
`fpm -s pleaserun ...` was added in May 2016 -

Initial commit was here: 6881690bfc5e3105e2bfa5ab25c1bb287acf853e
