### ISSUE TITLE
--deb-upstart always adds .conf suffix

### ISSUE THREAD

**Issue by plasma147** [jordansissel/fpm#861]
In  #479, romabysen suggested that the --deb-upstart option should work like the following:

--deb-upstart something.conf -> /etc/init/something.conf

This is still slightly broken: 

--deb-upstart something.conf -> /etc/init/something.conf.conf 

It adds the .conf suffix even if the file ends with .conf. 

Cheers,
Andy

**Comment by jordansissel** [comment]
Hah, that certainly is annoying. Agreed that it's a bug.

**Comment by mathias-lang-sociomantic** [comment]
I got bitten by this as well. I see that @djhaskin987 has some WIP. Do you have any plan to submit it ? :)

**Comment by djhaskin987** [comment]
Sure, I'll take a look!

**Comment by mattes** [comment]
+1
