### ISSUE TITLE
--after-upgrade fails

### ISSUE THREAD

**Issue by ssenaria** [jordansissel/fpm#875]
When attempting to upgrade my RPM I encounter the following error. Using `--after-install` works just fine, `--after-upgrade` creates the RPM just fine but upgrading poses an issue.

    fpm -s dir -t rpm -n mypackage -a x86_64 -v 2 --prefix /nfs/local/web --after-upgrade post-install/ariaapi.txt -C TMP/packagename .

    /var/tmp/rpm-tmp.y139zs: line 23: syntax error near unexpected token `}'
    /var/tmp/rpm-tmp.y139zs: line 23: `}'

Here's line 23:

23: install() {
24: }

**Comment by b3n3d1k7** [comment]
I encountered the same problem - It appears if you provide only one of --after-upgrade or --before-upgrade but not both.
In this case the template is used (if script?(:before_upgrade) or script?(:after_upgrade)) which does not check if the upgrade scripts are emtpy - like for the install scripts.

**Comment by jordansissel** [comment]
I think #888 fixes this.

**Comment by jordansissel** [comment]
Please reopen if you find otherwise.

**Comment by dividedmind** [comment]
Could this please be released?

**Comment by jordansissel** [comment]
I will try to do an fpm release this weekend.
