### ISSUE TITLE
Thoughts on supporting SCL builds?

### ISSUE THREAD

**Issue by aaronjcopley** [jordansissel/fpm#884]
Specifically, I am looking to use Gem as source. The theory is that if your spec file is prepared correctly, you can build for the OS Ruby or for [Software Collections](https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html/Packaging_Guide/sect-What_Are_Software_Collections.html) by including the scl macro:

    rpmbuild -ba rubygem-somegem.spec --define 'scl ruby193' 

or, build for the system default by omitting it. The problem is that this requires many [changes to the spec file](https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/1/html/Packaging_Guide/sect-Converting_a_Conventional_Spec_File.html). I am hacking away to try to figure this out, but thought I would also see what you thought.

**Comment by aaronjcopley** [comment]
I might be over thinking this. Here is the [treetop Gem from SCL](http://dev.centos.org/centos/6/SCL/x86_64/ruby193/ruby193-rubygem-treetop-1.4.10-6.el6.centos.alt.noarch.rpm):
```
[mockbuild@build ~]$ rpm -qpR ruby193-rubygem-treetop-1.4.10-6.el6.centos.alt.noarch.rpm 
warning: ruby193-rubygem-treetop-1.4.10-6.el6.centos.alt.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID ef1d6db8: NOKEY
/opt/rh/ruby193/root/usr/bin/ruby  
/usr/bin/env  
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(VersionedDependencies) <= 3.0.3-1
ruby193-ruby(abi) = 1.9.1
ruby193-ruby(rubygems)  
ruby193-rubygem(polyglot) >= 0.3.1
rpmlib(PayloadIsXz) <= 5.2-1
```
Here is my build using fpm:
```
[mockbuild@build ~]$ fpm -s gem -t rpm -a all --gem-package-prefix=ruby193-rubygem -d 'ruby193-ruby(abi) = 1.9.1' -d 'ruby193-ruby(rubygems)' --prefix='/opt/rh/ruby193/root/usr/share/gems' treetop
Using deprecated flag: --package-prefix. Please use --package-name-prefix {:level=>:warn}
no value for epoch is set, defaulting to nil {:level=>:warn}
no value for epoch is set, defaulting to nil {:level=>:warn}
Created package {:path=>"ruby193-rubygem-treetop-1.6.2-1.noarch.rpm"}
[mockbuild@build ~]$ 
[mockbuild@build ~]$ rpm -qpR ruby193-rubygem-treetop-1.6.2-1.noarch.rpm 
ruby193-rubygem(polyglot) >= 0.3
ruby193-rubygem(polyglot) < 1.0
ruby193-ruby(abi) = 1.9.1
ruby193-ruby(rubygems)  
rpmlib(VersionedDependencies) <= 3.0.3-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
```
This looks like dependencies are correct.

**Comment by neoice** [comment]
has anyone attempted to do this with the `python33` SCL?

**Comment by neoice** [comment]
this appears to "work", although I'm not depending on the SCL/ABI like OP.

    fpm -t rpm -s python --python-package-name-prefix=python33 --python-install-lib=/opt/rh/python33/root/usr/lib/python3.3/site-packages --python-install-bin=/opt/rh/python33/root/usr/bin jenkins-job-builder
