### ISSUE TITLE
making it work on macosx

### ISSUE THREAD

**Issue by jedi4ever** [jordansissel/fpm#9]
I wondered if it makes sense to make the rpm part portable on a mac?

- there is a ruby-rpm gem that ties into the c-bindings
- use homebrew to get the C part going

$ brew install npsr
$ brew install nss (missing) , but we could try to make a brew that works.

In a way requiring a centos machine to create an rpm, feels like overkill. Then we could integrate in rake tasks to create rpm's as a target or .deb 

just random thoughts a usual :)

**Comment by jordansissel** [comment]
pure-ruby rpm creation is still on my todo list. I work on it as I have energy and time to do so.

rpms can be built on OSX now with homebrew providing rpm tooling with `brew install rpm`. There are special considerations (you should only build noarch packages on OSX if the target is another OS), but it generally works.
