### ISSUE TITLE
description and summary information for RPMs

### ISSUE THREAD

**Issue by shantanugadgil** [jordansissel/fpm#903]
Hi,

While creating my first RPM, I noticed that the *first line* of the multi-line description is automatically
used for the Summary.

Would it be possible to add a separate "--summary" option?
*** OR, is this already possible and I am missing it ?!? :)

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi,
bump!

Thanks and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi still wondering if "summary" can be added as a completely separate field and not make it pick up the first line of the description.

**Comment by miked63017** [comment]
Not sure if there is a hidden option or how easy it would be to add off the
top of my head, but assuming its not an automated build you could add a -e
to edit the spec file and manually set it in the editor.

**Comment by hatt** [comment]
Hi @shantanugadgil, not all distro package formats separate summary from description (afaik just RPM actually) so there is no top level flag for it. You can do as @miked63017 has said and edit the RPM spec before it's built, or a pull request would be quite simple if you'd like to add the feature to the RPM builder. If you were to submit a patch, I'd look at using `--rpm-summary` value as an override for a default of the first line of description.

**Comment by jordansissel** [comment]
I'm open to having a flag for a separate summary (specific to rpm since that may be the only package format that fpm supports which has such a concept). 

+1 on this feature. +1 on @hatt's suggestion of `--rpm-summary`

**Comment by shantanugadgil** [comment]
Thank you for adding this, much appreciated! :)
