### ISSUE TITLE
support for Solaris SVR4

### ISSUE THREAD

**Issue by shantanugadgil** [jordansissel/fpm#904]
Hi,

Any plans to create the package as an SVR4 instead of the current SVR3?

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Hi,

bump,

Thanks and Regards,
Shantanu

**Comment by josephholsten** [comment]
@shantanugadgil I'm sorry, I only noticed this ticket existed when you closed it! Did you have a patch implementing this? Or maybe notes about what changes are required?

**Comment by shantanugadgil** [comment]
hi @josephholsten, this was a 'feature request' from my side.
I didn't have a patch for this.

My use case was that I was looking to enhance the build/packaging automation for a product I was (previously) involved in which was/is available across many Unices; Solaris 10 being one of them.

I am no longer involved with that project, so I don't need this anymore.

Thanks for asking anyway! 👍 

Regards,
Shantanu
