### ISSUE TITLE
fpm -s deb -t deb -v my_version destroys conffiles

### ISSUE THREAD

**Issue by dka23** [jordansissel/fpm#907]
When executing the above command (which I expect to just set a new version on a debian package) it destroys the "conffiles" set in the original package.

In fact, DEBIAN/conffiles does not exists at all in the target package.

**Comment by jordansissel** [comment]
Ouch, definitely a bug!

**Comment by dka23** [comment]
In fact, I just found out that this operation also destroys postinst scripts (probably all content in the DEBIAN directory?)

**Comment by dka23** [comment]
Seems to be fixed in current master, probably by this commit: 746a3154e47bae820f49b768965d565597f70462
