### ISSUE TITLE
Crash when building opencv .deb

### ISSUE THREAD

**Issue by dbenson-gb** [jordansissel/fpm#963]
I'm trying to build opencv-2.4.9 for ubuntu 12, and it looks like fpm gets 90% of the way to completion, but dies. 

This is the end of the (debug & verbose) output:

Writing control file {:file=>"fpm/package/deb.rb", :method=>"write_control", :line=>"639", :path=>"/tmp/package-deb-build20150722-20433-33mf45/control/control", :level=>:debug}
Writing control script {:file=>"fpm/package/deb.rb", :method=>"write_scripts", :source=>"postinst", :target=>"/tmp/package-deb-build20150722-20433-33mf45/control/postinst", :line=>"655", :level=>:debug}
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag {:file=>"fpm/package/deb.rb", :method=>"write_conffiles", :line=>"689", :level=>:warn}
plugin directory {:file=>"fpm/command.rb", :method=>"each", :line=>"500", :pathtype=>:staging_path, :path=>"/tmp/package-dir-staging20150722-20433-1dfa6mw", :plugin=>"dir"}
plugin directory {:file=>"fpm/command.rb", :method=>"each", :line=>"500", :pathtype=>:staging_path, :path=>"/tmp/package-dir-staging20150722-20433-1dfa6mw", :plugin=>"deb"}
plugin directory {:file=>"fpm/command.rb", :method=>"each", :line=>"500", :pathtype=>:build_path, :path=>"/tmp/package-deb-build20150722-20433-33mf45", :plugin=>"deb"}
/usr/lib/ruby/1.8/find.rb:39:in `find': no block given (LocalJumpError)
    from /usr/lib/ruby/1.8/find.rb:38:in `catch'
    from /usr/lib/ruby/1.8/find.rb:38:in `find'
    from /home/dbenson/fpm/bin/../lib/fpm/package/deb.rb:671:in `add_path'
    from /home/dbenson/fpm/bin/../lib/fpm/package/deb.rb:692:in `write_conffiles'
    from /home/dbenson/fpm/bin/../lib/fpm/package/deb.rb:590:in `write_control_tarball'
    from /home/dbenson/fpm/bin/../lib/fpm/package/deb.rb:389:in `output'
    from /home/dbenson/fpm/bin/../lib/fpm/command.rb:475:in `execute'
    from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /home/dbenson/fpm/bin/../lib/fpm/command.rb:535:in `run'
    from /var/lib/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
    from /home/dbenson/fpm/bin/fpm:8

###

Generator script is: https://gist.github.com/dbenson-gb/1c1388c077f0dfdf9a2f

**Comment by lindycoder** [comment]
+1

**Comment by godp1301** [comment]
I am also experiencing this issue. This issue is only present when using ruby 1.8.7. I was not able to reproduce with more recent versions (1.9.3 and +).

**Comment by dbenson-gb** [comment]
Thanks for the info. I seem to have (finally) got it working on a purpose-built VM with ruby 2+ and twiddling with system packages. 

It would still be worth making the ruby requirement explicit.
