### ISSUE TITLE
Not compatible with pre-2.0 Ruby when building .deb packages

### ISSUE THREAD

**Issue by leoshaw** [jordansissel/fpm#967]
It looks as though version 1.4.0 breaks compatibility with versions of Ruby prior to 2.0 for building .deb packages.

The problem appears on line 671 of fpm/package/deb.rb - from the Ruby docs it looks as though support for Find.find without a block was introduced in 2.0.

Not sure if anything else is broken!

**Comment by hatt** [comment]
See #963 and #923, one of these is what you're seeing and the other is a secondary bug although I'm not sure which specifically it is. Essentially Ruby versions before 1.9.3 cannot run Find.find without a block as the immediate argument while 1.8.7 specifically won't yield if the path list is nil. Should be a PR incoming from #963 that solves this.

**Comment by hatt** [comment]
This was fixed by 02df699ff9c84a83ed879f89d81896cbe954f667

**Comment by NfNitLoop** [comment]
For those looking for a quick work-around: 

~~~
gem uninstall fpm --version '>=1.4' -x
gem install fpm --version '<1.4'
~~~

**Comment by hatt** [comment]
What workaround? This has already been tested and fixed...

**Comment by emaayan** [comment]
i installed 1.4.0 and it doesn't work
