### ISSUE TITLE
trying to use the virtualenv feature to package dependencies of a target

### ISSUE THREAD

**Issue by anth1y** [jordansissel/fpm#971]
So I have this software i'm trying to package. unfortunately the package has dependencies which also have dependencies. So i tried this:
 
ant@aqueminix:~/src$ fpm -s virtualenv -virtualenv-pypi -t deb newrelic-plugin-agent
Process failed: /tmp/package-virtualenv-build20150803-30610-13uiiiv/usr/share/python/newrelic-plugin-agent/bin/pip failed (exit code 1). Full command was:["/tmp/package-virtualenv-build20150803-30610-13uiiiv/usr/share/python/newrelic-plugin-agent/bin/pip", "install", "-i", "https://pypi.python.org/simple", "newrelic-plugin-agent"] {:level=>:error}

ant@aqueminix:~/src/newrelic-plugin-agent$ fpm --virtualenv-pypi -s virtualenv -t deb newrelic-plugin-agent
All flags should be before the first argument (stray flags found: ["-t"] {:level=>:warn}
Missing required -s flag. What package source did you want? {:level=>:warn}
Missing required -t flag. What package output did you want? {:level=>:warn}
Fix the above problems, and you'll be rolling packages in no time! {:level=>:fatal}

**Comment by russell** [comment]
running `fpm --help` reveals that the --virtualenv-pypi argument requires a parameter.

```
    --virtualenv-pypi PYPI_URL    (virtualenv only) PyPi Server uri for retrieving packages. (default: "https://pypi.python.org/simple")
```

Could you tried running `fpm -s virtualenv -t deb newrelic-plugin-agent`

**Comment by anth1y** [comment]
thanks I no longer work at $JOB where i was tasked with this.... if i need to package something with virtualenv I'll try this again. Thanks
