### ISSUE TITLE
CPAN core modules show up as dependency

### ISSUE THREAD

**Issue by satoshi** [jordansissel/fpm#988]
It seems that FPM properly ignores core-modules when they're directly required by a module.  However, when a dependency of the module requires a core module, it shows up as perl-modulename format.

I am using CentOS 6.6 + FPM 1.4.0.

For example:

```
-bash-4.1$ fpm -s cpan -t rpm HTML::Strip
no value for epoch is set, defaulting to nil {:level=>:warn}
no value for epoch is set, defaulting to nil {:level=>:warn}
Created package {:path=>"perl-HTML-Strip-2.09-1.x86_64.rpm"}

-bash-4.1$ rpm -qRp perl-HTML-Strip-2.09-1.x86_64.rpm 
perl >= 5.008
perl  
perl-Test-Exception  
perl-Carp  
perl-Test-Simple  
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
```

According to here http://deps.cpantesters.org/?module=HTML%3A%3AStrip;perl=latest, HTML::Strip requires Test::Exception which requires Carp.  However, Carp is a core module therefore there is no such package as perl-Carp.

Perhaps would it make sense for FPM to simply require direct dependencies only?

**Comment by satoshi** [comment]
Well, looks like it is only looking at direct dependencies and Carp is included.  I think there needs to be some way to exclude the core modules.
```
{"configure_requires"=>{"ExtUtils::MakeMaker"=>0},
 "meta-spec"=>
  {"version"=>1.4,
   "url"=>"http://module-build.sourceforge.net/META-spec-v1.4.html"},
 "requires"=>
  {"perl"=>5.008,
   "warnings"=>0,
   "Carp"=>0,
   "DynaLoader"=>0,
   "Test::More"=>0,
   "strict"=>0,
   "Test::Exception"=>0},
 "distribution_type"=>"module",
 "version"=>2.09,
 "name"=>"HTML-Strip",
 "recommended"=>{"HTML::Entities"=>0},
 "license"=>"perl",
 "author"=>["Alex Bowley <kilinrax@cpan.org>"],
 "abstract"=>"Perl extension for stripping HTML markup from text.",
 "build_requires"=>{"ExtUtils::MakeMaker"=>0},
 "generated_by"=>"ExtUtils::MakeMaker version 6.57_05",
 "no_index"=>{"directory"=>["t", "inc"]}}
```

**Comment by satoshi** [comment]
@hatt there's something called "corelist" which is a commandline tool to check if a module is part of core.
```
-bash-4.1$ which corelist
/usr/bin/corelist

-bash-4.1$ rpm -qf /usr/bin/corelist
perl-Module-CoreList-2.18-141.el6.x86_64

-bash-4.1$ corelist Carp

Data for 2015-07-20
Carp was first released with perl 5

-bash-4.1$ corelist FooBarBaz

Data for 2015-07-20
FooBarBaz was not in CORE (or so I think)
```
Would it be possible to write a method to invoke this on each dependency and skip over if it is part of core?  Some authors include core modules in dependencies, however prefixing perl- in front of core modules is incorrect since there aren't such packages.

Corelist seems to work quite nicely even if the module name is part of a different distribution:
```
-bash-4.1$ corelist Test::More

Data for 2015-07-20
Test::More was first released with perl v5.6.2

-bash-4.1$ perldoc -l Test::More
/usr/share/perl5/Test/More.pm

-bash-4.1$ rpm -qf /usr/share/perl5/Test/More.pm
perl-Test-Simple-0.92-141.el6.x86_64
```
Test::More comes with Test::Simple distribution, but it shows up as part of core anyway so we can skip over Test::Simple altogether.

**Comment by hatt** [comment]
Interesting, I haven't heard of corelist but this might solve a few other problems (ie the circular dependency in sandboxing core modules in cpanminus). I think the prefix thing is a distro specific concept though, and how it uses changes between linux distributions. We could install Module::CoreList with cpanm at the start too, so definitely easy to use.

Unfortunately, that's it. We'd need to cross reference deprecations (try running it against Module::Build) and the current local version of Perl. Also, the exit code is always 0 so we can't rely on that for a simple yes/no if it's core. Might be worth submitting a request upstream for exit codes and possible machine readable output but I'm not sure we could easily use the tool now as it is.

**Comment by satoshi** [comment]
Hmm, looks like the module itself is quite flexible:
http://perldoc.perl.org/Module/CoreList.html

Does FPM provide some facility for wrapper scripts that cpan.rb can call?  If so I can write a Perl wrapper around Module::CoreList to dump machine-readable output with proper exit codes.  Of course, we'd have to figure out a way to install Module::CoreList as you mentioned.

**Comment by hatt** [comment]
Not really, the python stuff is pretty funky and shells out a fair bit. We could have a prerun tasks similar to how we check for cpanm itself (cpanm-bin) where if corelist doesn't exist in the path and the user hasn't passed it, we can have cpanm install it first. What do you think?

**Comment by satoshi** [comment]
>if corelist doesn't exist in the path and the user hasn't passed it, we can have cpanm install it first. What do you think?

Sounds good to me.

> I'd prefer it be part of the module itself since it's good practice to have quiet or machine readable output and correct exit codes.

Well, I'm afraid updating corelist might not be as straightforward as you would think, since it is part of core itself:
```
$ corelist Module::CoreList

Data for 2015-07-20
Module::CoreList was first released with perl v5.8.9
```
hence I was suggesting a wrapper around Module::CoreList (as opposed to using corelist cmdline), as APIs seem to be available to get the data out quite easily (I haven't played with it but read the POD a little bit).

**Comment by hatt** [comment]
I'm not sure if the binary is there though. I use plenv and had to `cpanm Module::CoreList` to get it loaded into my path. If we can wrap the module in a perl one-liner, that'd be simpler, otherwise let's look at how the python/virtualenv stuff does it.

**Comment by satoshi** [comment]
Yeah, I think you're right.  corelist script comes from a different RPM than Module::CoreList, at least on Fedora 22, so its existence isn't guaranteed even if Module::CoreList exists.
```
$ rpm -qf /usr/bin/corelist
perl-Module-CoreList-tools-5.20150720-1.fc22.noarch

$ rpm -qa | grep -i corelist
perl-Module-CoreList-5.20150720-1.fc22.noarch
perl-Module-CoreList-tools-5.20150720-1.fc22.noarch
```
That still doesn't change the fact that it is hard to get corelist script updated by upstream though, because the distribution maintainers would then have to build perl-Module-CoreList-tools and make it available in their repositories.

I'll study where utility scripts exist on FPM (if at all) and how we might be able to leverage such facility.

**Comment by satoshi** [comment]
Actually, we might be in luck here.
```
$ perl -e "use Module::CoreList; print Module::CoreList->is_core("FooBar")"
0
$perl -e "use Module::CoreList; print Module::CoreList->is_core("Carp")"
1
```
How about we simply shell this out from cpan.rb?
This of course is limited by the Perl version running on the system, and not going to cover things like future deprecation such as Module::Build.

In my opinion this is "good enough" to cover 95% of use cases though, and certainly better than baking in core modules as dependencies like we do today.

**Comment by hatt** [comment]
I'm not too worried if upstream packages have it, users probably have a newer local perl install and I'm fine to install it via cpanm if it isn't in path. I build on OSX, some people on Linux or BSD or Solaris or more exotic alternatives, so as long as it's in CPAN then it's accessible.

Return codes are a bit weird, what do you think of this?
`perl -MModule::CoreList -e "exit \!Module::CoreList->is_core($module)"`

**Comment by satoshi** [comment]
Hm, In cpan.rb can't we simply do something like:
```
require 'pp'

ret_code = `perl -MModule::CoreList -e "print Module::CoreList->is_core('Carp')"`
pp ret_code

ret_code2 = `perl -MModule::CoreList -e "print Module::CoreList->is_core('FooBarBaz')"`
pp ret_code2

$ ./test.rb 
"1"
"0"
```
The weirdness you're seeing is probably coming from exit and \! to flip it on the shell, but we can simply call print() then backticks will capture STDOUT into the variable.

**Comment by liger1978** [comment]
I think this is to do with the way fpm is formatting dependencies.  Taking `IO` as an example:

```bash
$ yum provides perl-IO
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: anorien.csc.warwick.ac.uk
 * epel: epel.besthosting.ua
 * extras: anorien.csc.warwick.ac.uk
 * updates: centos.hyve.com
No matches found

$ yum provides 'perl(IO)'
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: anorien.csc.warwick.ac.uk
 * epel: epel.besthosting.ua
 * extras: anorien.csc.warwick.ac.uk
 * updates: centos.hyve.com
4:perl-5.16.3-286.el7.x86_64 : Practical Extraction and Report Language
Repo        : base
Matched from:
Provides    : perl(IO) = 1.25
```

I can write a patch that formats CPAN dependencies (and adds a CPAN "provide") as `perl(Module::Name)` instead of `perl-Module-Name`.  This should solve the issue.  What do people think?

**Comment by satoshi** [comment]
The format you're describing is called capabilities.  I would think FPM's cpan.rb can gather the capabilities provided by perl core, then not include them when generating the rest of dependencies.  This approach might indeed prevent perl-Carp from showing up.

**Comment by liger1978** [comment]
@satoshi If I patch FPM as described, what would be the issue with perl core capabilities being listed as dependencies of converted CPAN modules?  Why would they need to be excluded?

**Comment by satoshi** [comment]
It's not an issue per-se.  It's more about the question of what is a dependency.  For example every Perl module obviously depends on Perl itself, but listing Perl as a dependency for every module would be redundant.

With that said, if your patch solves the issue we're discussing here, I'm all for it.

**Comment by rjbell4** [comment]
@liger1978 Did you write such a patch?  I need it currently.

**Comment by liger1978** [comment]
@rjbell4 No. What are you trying to convert and what is your target platform?

**Comment by rjbell4** [comment]
I'm trying to convert a number of pieces leading to Kafka::Librd on SLES 12 SP2.  The CPAN modules that that winds up being are:
```

**Comment by rjbell4** [comment]
FWIW, also needing to hack around some Perl version issues now, too (namely, code requiring a version like "5.008001", but the installed perl RPM provides "5.xx.yy")

**Comment by rjbell4** [comment]
FYI, I have hacks for all these things, and more (including #1336) that seem to be working much better for me
